### ISSUE TITLE
Managed API is missing documentation (xmldocs)

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#5108] opened 2019-02-07 21:35 UTC
Most of the API in [src/managed/](https://github.com/dotnet/core-setup/tree/master/src/managed) ships in a NuGet package, but is missing API documentation. It would be useful to provide API docs for the public API in

* Microsoft.DotNet.PlatformAbstractions
* Microsoft.Extensions.DependencyModel

**Comment by eerhardt** [comment] 2019-04-03 18:28
Appears to be a duplicate of https://github.com/dotnet/core-setup/issues/4372. Closing in favor of that issue instead.

**Closed by eerhardt** 2019-04-03 18:28 UTC
Labels: area-DependencyModel
