### ISSUE TITLE
Latest CLI throws exception - System.DllNotFoundException : Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#1961] opened 2017-04-05 16:49 UTC
_From @kichalla on April 5, 2017 5:51_

## Steps to reproduce
- Clone the repo http://github.com/aspnet/kestrelhttpserver
- Set the environment variable `KOREBUILD_DOTNET_VERSION` to `2.0.0-preview1-005685` (this tells the build to use this CLI version)
- Run `build.cmd`

## Expected  behavior
Build runs successfully

## Actual behavior
Build fails with error:
```
System.AggregateException : One or more errors occurred.
---- System.DllNotFoundException : Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.AspNetCore.Testing.TestServer..ctor(RequestDelegate app, TestServiceContext context, ListenOptions listenOptions, IHttpContextFactory httpContextFactory) in C:\github\kestrelhttpserver\test\shared\TestServer.cs:line 58
   at Microsoft.AspNetCore.Testing.TestServer..ctor(RequestDelegate app, TestServiceContext context, ListenOptions listenOptions) in C:\github\kestrelhttpserver\test\shared\TestServer.cs:line 38
   at Microsoft.AspNetCore.Server.KestrelTests.EngineTests.<ThrowingInOnStartingResultsInFailedWritesAnd500Response>d__24.MoveNext() in C:\github\kestrelhttpserver\test\Microsoft.AspNetCore.Server.KestrelTests\EngineTests.cs:line 868
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.Init(LibuvFunctions uv)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransport.<BindAsync>d__20.MoveNext()
[xUnit.net 00:00:38.8783866]   Finished:    Microsoft.AspNetCore.Server.KestrelTests
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005685)

Product Information:
 Version:            2.0.0-preview1-005685
 Commit SHA-1 hash:  1f8b86d268

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005685\
```

@davidfowl 

_Copied from original issue: dotnet/cli#6248_

**Comment by kichalla** [comment] 2017-04-05 17:24
This blocks ASP.NET Core build to move to latest CLI

@mikeharder

**Comment by Petermarcu** [comment] 2017-04-05 17:35
@kichalla , is that library being put with the application? @ramarag @gkhanna79 to dig in.

**Comment by gkhanna79** [comment] 2017-04-05 17:52
Libuv was part of the SharedFX and was removed as part of the refactoring @eerhardt did in https://github.com/dotnet/core-setup/commit/dfcb6f272144c7bab58fda96b2d41b47a92a2f34#diff-873c95bf8557aaaff0254fb7a81d49fd. 

@eerhardt How is libuv getting installed post the change above?

**Comment by Petermarcu** [comment] 2017-04-05 17:53
Folks need to reference the package. I expected that this was already referenced from kestrel.

**Comment by eerhardt** [comment] 2017-04-05 17:56
Correct ASP.NET needs to reference Libuv explicitly now.

This is a dupe of https://github.com/dotnet/cli/issues/6072.

**Comment by eerhardt** [comment] 2017-04-06 17:47
I’ve debugged this and figured out a bunch of things.

### This only fails on Desktop
* The error only happens when running tests on desktop net46.  The netcore tests pass on my machine.
* Libuv is not getting placed in the test’s net46 output folder.
* When I attached a debugger to a net46 run of when the tests pass (using my 1.0 installed “dotnet test”), libuv is getting loaded out of the .NET Core Shared Framework

### dotnet.exe appends the Shared Framework path to %PATH%

The reason this scenario worked before is because when a test is run using `dotnet test`, the dotnet.exe host is used to load MSBuild, and then MSBuild invokes `dotnet vstest.console`.  Each time the host invokes a shared framework app, it is [appending the shared framework path to the `%PATH%` environment variable.](https://github.com/dotnet/core-setup/blob/d9b42f8cf23a69509d956230ef7fac4c8c0cdc72/src/corehost/common/pal.windows.cpp#L48-L66).
Before, in 1.0 and 1.1 shared frameworks, `libuv` is present.  And in earlier builds of 2.0, we used 1.x shared framework to invoke `vstest.console`.  But recently, `vstest.console` moved to 2.0, so now we are no longer invoking a 1.x shared framework app, and `libuv` is not in the 2.0 shared framework.  Thus, the test no longer passes.

I've logged https://github.com/dotnet/core-setup/issues/1974 for this issue.

### The tooling doesn't copy libuv to the output folder

The reason libuv isn’t getting copied to the test output folder during build is because no one is setting a RID.  For normal “apps” we have RID inference logic for desktop:

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.RuntimeIdentifierInference.targets#L59-L66

```XML
  <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework' and 
                            '$(OutputType)' == 'Exe' and 
                            '$(OS)' == 'Windows_NT' and
                            '$(RuntimeIdentifier)' == ''">
    <_UsingDefaultRuntimeIdentifier>true</_UsingDefaultRuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(PlatformTarget)' == 'x64'">win7-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(PlatformTarget)' == 'x86' or '$(PlatformTarget)' == ''">win7-x86</RuntimeIdentifier>
  </PropertyGroup>
```
But as you can see this only happens if your OutputType is ‘exe’, which for this test it isn’t.

The test does specify a `<PlatformTarget>`, but not a `<RuntimeIdentifier>`.

Adding the following line makes the tests pass again (because now the win-x64 libuv assembly is getting copied to the output dir):

```XML
    <RuntimeIdentifier Condition="'$(TargetFramework)' == 'net46'">win7-x64</RuntimeIdentifier>
```

Another workaround is to add this line to your project:

```XML
<OutputType>Exe</OutputType> 
```

The underlying issue is a duplicate of an existing sdk issue: https://github.com/dotnet/sdk/issues/909.

Closing as dupe.

/cc @nguerrera

**Closed by eerhardt** 2017-04-06 17:47 UTC
Labels: blocking-partner

**Comment by nguerrera** [comment] 2017-06-07 14:05
@godrose The remaining work for this experience to work without workarounds is tracked by https://github.com/Microsoft/vstest/issues/792
