### ISSUE TITLE
More meaningfull error instead of "The library hostpolicy.dll required to execute"

### ISSUE THREAD

**Issue by jkotas** [dotnet/core-setup#3768] opened 2018-03-02 23:42 UTC
_From @roozbehid-ic on March 2, 2018 17:28_

It seems when .Net Core application doesnt have **appname.deps.json** or **appname.runtimeconfig.deps**, .Net Core shows this error 

    A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'some path'

It hit me several times and I've spent some time just looking for that dll and why it is missing until I found that [other people](https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found) also hit it and the reason was something else.

Some error message before tht about those missing files would save tons of time.

_Copied from original issue: dotnet/coreclr#16708_

**Comment by steveharter** [comment] 2018-03-05 15:39
cc @KathleenDollard I'll work on making this error message better

**Comment by steveharter** [comment] 2018-03-27 19:15
Closing this as duplicate of https://github.com/dotnet/core-setup/issues/3193 which will be in 2.1.0

The [pull request](https://github.com/dotnet/core-setup/pull/3382) has additional information on the changes.

**Closed by steveharter** 2018-03-27 19:15 UTC
Labels: area-Host, enhancement
