### ISSUE TITLE
Installers are not published to Latest blob path for 1.0.x and 1.1.x servicing 

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/core-setup#1950] opened 2017-04-04 18:10 UTC
## Steps to reproduce
Go to Readme page : https://github.com/dotnet/core-setup 
Install 1.1.x or 1.0.x installer for Windows 
## Expected  behavior
Installer should be from latest daily build

## Actual behavior
Downloaded installer is of 1.1.0 RTM and 1.0.0 RTM 

## Environment data

**Comment by dagood** [comment] 2017-04-04 18:46
The blobs in `dotnet/release/1.1.0/Installers/Latest/` have last modified dates that correspond with the latest 1.1.x build. This makes me think the build is using the version `1.1.0` rather than `1.1.x-servicing-x-x` as the copy source, making it copy the 1.1.0 build to Latest during every build.

It looks like `SharedFrameworkNugetVersion` having the wrong value in https://github.com/dotnet/core-setup/blob/a29f0361ef3f30a50dccbc961d6e44533f587234/build_projects/dotnet-host-build/PublishTargets.cs#L114 it would cause this issue, but I can't find any indication in the rest of the build logs that it's wrong.

I want to add build logging to Azure uploads to see what it's actually doing, first.

**Comment by dagood** [comment] 2017-04-05 23:52
From the logs, I see that the first `Installers` copy actually works, e.g.

> Copying blob 'release/1.1.0/Installers/**1.1.2-servicing-001480-00**/dotnet-win-x64.1.1.2-servicing-001480-00.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-x64.latest.exe'

Then it gets stomped over by the [second `Installers` copy](https://github.com/dotnet/core-setup/blob/7d020e76689fa0e312a27294c7c6bc035e5511a7/build_projects/dotnet-host-build/PublishTargets.cs#L117):

> Copying blob 'release/1.1.0/Installers/**1.1.0**/dotnet-win-x64.1.1.0.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-x64.latest.exe'

That source `1.1.0` is `SharedHostNugetVersion`
 * [which is set by](https://github.com/dotnet/core-setup/blob/7d020e76689fa0e312a27294c7c6bc035e5511a7/build_projects/dotnet-host-build/PublishTargets.cs#L40) `c.BuildContext.Get<HostVersion>("HostVersion").LockedHostVersion`
 * [whose prerelease specifier was removed by](https://github.com/dotnet/core-setup/blob/7d020e76689fa0e312a27294c7c6bc035e5511a7/build_projects/shared-build-targets-utils/Utils/HostVersion.cs#L107-L109) `IsLocked = true`
 * which was changed from `false` to `true` in https://github.com/dotnet/core-setup/pull/658.

@gkhanna79 can you explain this flag? I can't figure out why `true` makes sense.

**Comment by gkhanna79** [comment] 2017-04-06 00:00
@dagood The host is divided into 3 parts depending upon the degree of change the various components go through:

1) Hostpolicy - changed with SharedFX
2) HostFXR - changed much less frequently
3) dotnet.exe - changed even more infrequently

Given that (2) and (3) do not change every release, but the installer packages need to carry them every release, we _lock_ the last version we released and restore them. Hence the "Locked*" names.

Based upon what you found out, the copy over seems to be by design and is correct.

**Comment by dagood** [comment] 2017-04-06 14:42
Thanks, that makes sense. The overlap between the SharedFX bits and locked bits strikes me as odd, then--here's the full log of what each copy is doing:

```
--Copying blobs from 'release/1.1.0/Installers/1.1.2-servicing-001480-00/' to 'release/1.1.0/Installers/Latest/'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-osx-x64.1.1.2-servicing-001480-00.pkg' to 'release/1.1.0/Installers/Latest/dotnet-osx-x64.latest.pkg'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-debian-x64.1.1.2-servicing-001480-00.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-debian-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-osx-x64.1.1.2-servicing-001480-00.pkg' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-osx-x64.latest.pkg'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-ubuntu-x64.1.1.2-servicing-001480-00.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-ubuntu.16.04-x64.1.1.2-servicing-001480-00.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-ubuntu.16.04-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-ubuntu.16.10-x64.1.1.2-servicing-001480-00.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-ubuntu.16.10-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-win-arm64.1.1.2-servicing-001480-00.msi' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-win-arm64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-win-x64.1.1.2-servicing-001480-00.msi' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-win-x64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-sharedframework-win-x86.1.1.2-servicing-001480-00.msi' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-win-x86.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-win-arm64.1.1.2-servicing-001480-00.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-arm64.latest.exe'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-win-x64.1.1.2-servicing-001480-00.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-x64.latest.exe'
Copying blob 'release/1.1.0/Installers/1.1.2-servicing-001480-00/dotnet-win-x86.1.1.2-servicing-001480-00.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-x86.latest.exe'

--Copying blobs from 'release/1.1.0/Installers/1.1.0/' to 'release/1.1.0/Installers/Latest/'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-debian-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-host-debian-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-osx-x64.1.1.0.pkg' to 'release/1.1.0/Installers/Latest/dotnet-host-osx-x64.latest.pkg'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-ubuntu-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-ubuntu.16.04-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-host-ubuntu.16.04-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-ubuntu.16.10-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-host-ubuntu.16.10-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-win-arm64.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-host-win-arm64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-win-x64.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-host-win-x64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-host-win-x86.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-host-win-x86.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-debian-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-debian-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-osx-x64.1.1.0.pkg' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-osx-x64.latest.pkg'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-ubuntu-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-ubuntu-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-ubuntu.16.04-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-ubuntu.16.04-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-ubuntu.16.10-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-ubuntu.16.10-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-win-arm64.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-win-arm64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-win-x64.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-win-x64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-hostfxr-win-x86.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-hostfxr-win-x86.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-osx-x64.1.1.0.pkg' to 'release/1.1.0/Installers/Latest/dotnet-osx-x64.latest.pkg'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-debian-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-debian-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-osx-x64.1.1.0.pkg' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-osx-x64.latest.pkg'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-ubuntu-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-ubuntu.16.04-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-ubuntu.16.04-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-ubuntu.16.10-x64.1.1.0.deb' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-ubuntu.16.10-x64.latest.deb'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-win-arm64.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-win-arm64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-win-x64.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-win-x64.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-sharedframework-win-x86.1.1.0.msi' to 'release/1.1.0/Installers/Latest/dotnet-sharedframework-win-x86.latest.msi'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-win-arm64.1.1.0.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-arm64.latest.exe'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-win-x64.1.1.0.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-x64.latest.exe'
Copying blob 'release/1.1.0/Installers/1.1.0/dotnet-win-x86.1.1.0.exe' to 'release/1.1.0/Installers/Latest/dotnet-win-x86.latest.exe'
```

If this is intended, then we are intentionally not delivering new SharedFX installers. If that's true, we can close this issue, but it seems odd to me.

A workaround if we actually do want to put the new SharedFX installers in the Latest dir is to swap the order of the copies so the last overwrite is from the new build. Distinguishing between SharedFX and Host installers would also work, but we would have to determine the logic for that since there aren't distinguishing dirs like "HostInstallers" and "SharedFXInstallers".

**Comment by gkhanna79** [comment] 2017-04-06 21:54
> If this is intended, then we are intentionally not delivering new SharedFX installers. If that's true, we can close this issue, but it seems odd to me.

This is not intended. We only want to copy the binaries that are not expected to change.

> A workaround if we actually do want to put the new SharedFX installers in the Latest dir is to swap the order of the copies so the last overwrite is from the new build

I agree - this is a good approach. Do you want to take a stab at fixing this for the servicing branches (1.0.0 and 1.1.0)?

**Comment by dagood** [comment] 2017-04-06 22:23
Sure. Created PRs, sending to shiproom.

**Comment by dagood** [comment] 2017-04-07 13:46
Builds have been done with the PRs and the current Latest installers are from the new builds. Closing.

@rakeshsinghranchi Can you confirm if what's in Latest now matches what you expect?

**Closed by dagood** 2017-04-07 13:46 UTC
Labels: area-Infrastructure
