### ISSUE TITLE
dotnet-host 2.1.0-preview2-26406-04-1 is not backwards compatible with 2.0.x applications: Failed to resolve library symbol hostfxr_main_startupinfo

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#4007] opened 2018-04-10 19:28 UTC
I'm seeing multiple reports that 2.0.x runtimes no longer launch due to failures in loading libhostfxr.so

https://github.com/travis-ci/travis-ci/issues/9467
https://twitter.com/bradwilson/status/983782235777024000

**Repro**
On a clean machine, configure feeds as described on https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current
`sudo apt-get install dotnet-sdk-2.1.104`
`dotnet --info`

**Expected**
Stable releases of .NET Core should still work and only install stable versions of the `dotnet-host` package.

**Actual**
The installation brings down the prerelease `dotnet-host` package, version 2.1.0-preview2-26406-04-1, which issues this warning before exiting with and error code.
```
Failed to resolve library symbol hostfxr_main_startupinfo, error: /usr/share/dotnet/host/fxr/2.0.0/libhostfxr.so: undefined symbol: hostfxr_main_startupinfo
```

**Workaround**
Downgrade the `dotnet-host` package to an older version
```
sudo apt install dotnet-host=2.0.6-1
```

@steveharter @Petermarcu @leecow - preview2 impacting

cc @bradwilson @akoeplinger

**Comment by pakrym** [comment] 2018-04-10 19:34
Is caused by  [this ](https://github.com/dotnet/core-setup/blob/24ba120b0ca1ba60a24a79b7dc95866cd3e9f799/src/corehost/common/pal.unix.cpp#L85) check. On windows returning null is allowed and it's checked in the condition [here](https://github.com/dotnet/core-setup/blob/d6802d0c09f845cc26020691f155320a1fb37a67/src/corehost/corehost.cpp#L274) but on Linux PAL would log an error.

**Comment by bording** [comment] 2018-04-10 19:39
Installing `dotnet-sdk-2.1.104` also ends up installing the `dotnet-runtime-deps-2.1.0-preview2-26406-04` package.

I don't think you should be publishing preview packages on the same feed as the release packages.

**Comment by steveharter** [comment] 2018-04-10 20:29
So there are two issues here:
1) We are installing a preview version of the host when we shouldn't
2) There is a log message this is causing downstream issues. However, it is new to me that writing to stderr will cause `csc.exe` to fail since the actual process return value here should be success. Plus we write to stderr for informational cases when COREHOST_TRACE=1.

**Comment by steveharter** [comment] 2018-04-10 20:33
>> Installing dotnet-sdk-2.1.104 also ends up installing the dotnet-runtime-deps-2.1.0-preview2-26406-04 package.

@livarcocc @nguerrera can you comment on this please

**Comment by nguerrera** [comment] 2018-04-10 20:41
^ @wli3 Is there something wrong with the deb packages that is causing that? (cc @leecow)

**Comment by pakrym** [comment] 2018-04-10 21:07
> However, it is new to me that writing to stderr will cause csc.exe to fail since the actual process return value here should be success

A lot of applications treat child process printing to stderr as a failure (CI agents, MSBuild etc.) even when exit code is 0.

**Comment by leecow** [comment] 2018-04-10 21:13
So there is 1 bug in the host package which Rakesh has fixed. This had the runtime-deps dependency on dotnet-host rather than dotnet-runtime. Because dotnet-host is the only package (at the moment) that is seen as upgradable by the package managers, the latest is always brought in. 

A possible workaround for folks that have been hit by this is the following: 

`apt-cache madison dotnet-host` : this will return a list of all versions available on the feed
`apt-get install dotnet-host=[version you want from the list returned by madison]`

**Comment by Petermarcu** [comment] 2018-04-10 22:48
I think there is a larger problem here though. The host singleton needs to always work with all previous versions. It can't require an updated host policy or runtime.

**Comment by bording** [comment] 2018-04-10 22:56
I also want to point out that @natemcmaster mentioned on [twitter](https://twitter.com/natemcmaster/status/983804972314738688) that the preview host package has been pulled from the feed, but that's left the 2.1.104 SDK installation broken because it complains about missing dependencies. The 2.0.6 host package has to be manually installed first before you can install the SDK right now.

**Comment by Petermarcu** [comment] 2018-04-10 22:59
All of the preview packages got pulled but the dependency of the 2.1.104 SDK should still be there.

**Comment by bording** [comment] 2018-04-10 23:17
@Petermarcu after using `apt remove` to remove all of the 2.1.104/2.0.6 packages and doing an `apt update`, when I run `apt install dotnet-sdk-2.1.104`, I get the following error:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1.104 : Depends: dotnet-runtime-2.0.6 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
When I run `apt-cache madison dotnet-host`, I still see the preview package:
```
dotnet-host | 2.1.0-preview1-26216-03-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.6-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.5-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.4-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.3-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.0-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    1.1.0-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host | 2.1.0-preview1-26216-03-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.6-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.5-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.4-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.3-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    2.0.0-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages
dotnet-host |    1.1.0-1 | https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial/main amd64 Packages

**Comment by leecow** [comment] 2018-04-10 23:27
Just noticed that - working on getting the Preview 1 package removed.

**Comment by leecow** [comment] 2018-04-10 23:49
Alrighty - run apt-get update then apt-cache madison and you should see no 2.1.0 Preview packages.

**Comment by bording** [comment] 2018-04-10 23:57
@leecow Removing the preview1 package has gotten everything working correctly again.

**Comment by steveharter** [comment] 2018-04-11 14:12
>>  The host singleton needs to always work with all previous versions. It can't require an updated host policy or runtime.

The host singleton (dotnet.exe) does work with all previous versions of hostfxr. The only thing that doesn't work is apphost (<mayapp>.exe) when it is from the 2.1 SDK and trying to use new features (relative path to framework) but only finds an old hostfxr then an error is raised.

**Comment by Petermarcu** [comment] 2018-04-11 15:44
I talked to @steveharter and understand now that the host is tolerant, and doing the right thing functionally. The problem is only that it writes to stderr and some of our tools treat that as an error overall. We're going to explore options for getting an updated host package available.

**Comment by CRCinAU** [comment] 2018-04-12 05:44
This seems to be broken still on the RPM repos. As a hack and workaround, I changed the dotnetdev.repo as follows:

```
[packages-microsoft-com-prod]
name=packages-microsoft-com-prod
baseurl= https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
exclude=*preview*
```

This allows us to rip & install any dotnet packages and not get the preview packages...

**Comment by npakudin** [comment] 2018-04-12 13:48
CRCianAU's workaround helped for a clean CentOS 7

**Comment by rudiv** [comment] 2018-04-13 15:08
To fix an existing CentOS 7 installation that broke as a result of this bug, we removed the following:
`yum remove dotnet-dotnet-runtime-deps-2.1.0-preview2-26406-04 dotnet-host dotnet-sdk-2.1.104`

Then editing /etc/yum.repos.d/dotnetdev.repo and adding in the `exclude` line as @CRCinAU suggested and reinstalling `dotnet-sdk-2.1.104` fixes it.

**Comment by CRCinAU** [comment] 2018-04-13 15:10
A script friendly way to do this on machines you haven't already fixed up as per my suggestion:

```
echo 'exclude=*preview*' >> /etc/yum.repos.d/dotnetdev.repo
yum -y erase dotnet*
yum -y install dotnet-sdk-whatever
```

**Comment by sm-programmer** [comment] 2018-04-13 18:16
I confirm the suggestion made by @leecow regarding the setup in Ubuntu machines works by picking first the `dotnet-host` version by hand. Using Ubuntu 17.10.

**Comment by joalcava** [comment] 2018-04-13 22:30
Any workaround for fedora users? I'm stuck with this.

**Comment by CRCinAU** [comment] 2018-04-14 01:50
@joalcava - You can use the same as I suggested above - but change the *yum* commands for *dnf*.

**Comment by leecow** [comment] 2018-04-14 21:59
Update on this: Debian, Ubuntu, OpenSUSE and SLES feeds should be up and running for Preview 2 with a fix dotnet-host fix to resolve the compat. Still having trouble with the rhel feed used for RHEL, Fedora, CentOS and Oracle need another team to do some surgery to the repo so will need to wait for Monday.

**Comment by bording** [comment] 2018-04-14 22:50
@leecow I can confirm that the version of the dotnet-host preview package that gets installed no longer causes the crash.

However, I still don't understand why it's considered okay that installing a released version of the SDK or runtime installs preview packages in the first place. If I'm installing .NET Core on a production machine, I definitely don't want preview packages installed on it.

**Comment by steveharter** [comment] 2018-04-18 21:14
Closing this for the original issue with the logging to stderr.

There still is the question above around why a release SDK installs the preview host.

**Closed by steveharter** 2018-04-18 21:14 UTC
Labels: area-Host, bug

**Comment by bording** [comment] 2018-04-18 21:16
> There still is the question above around why a release SDK installs the preview host.

@steveharter Is there an issue for this that I can follow?
