### ISSUE TITLE
WindowsDesktop located in incorrect directory in latest daily (5.0.100-alpha1-013704)

### ISSUE THREAD

**Issue by rladuca** [dotnet/core-setup#7651] opened 2019-08-09 17:31 UTC
## Steps to reproduce
Install 5.0.100-alpha1-013704 build of .NET Core

## Expected  behavior
WindowsDesktop lives under dotnet/shared/Microsoft.WindowsDesktop,App and applications load properly.

## Actual behavior
It's under dotnet/shared/shared/Microsoft.WIndowsDesktop.App causing all WindowsDesktop applications to crash immediately.

## Environment data
![image](https://user-images.githubusercontent.com/20006987/62797375-71dee200-ba90-11e9-9908-73ce05d75d82.png)

@dotnet/wpf-developers  @merriemcgaw FYI

**Comment by rladuca** [comment] 2019-08-09 17:32
@ericstj @livarcocc @nguerrera

**Comment by dagood** [comment] 2019-08-09 17:33
Duplicate of https://github.com/dotnet/core-sdk/issues/3883

**Comment by dagood** [comment] 2019-08-09 17:33
This is an issue in SDK zip assembly due to a change requested to support installing the WD sfx with `dotnet-install.ps1`.

**Closed by dagood** 2019-08-09 17:33 UTC

**Comment by rladuca** [comment] 2019-08-09 17:35
Ah thanks, didn't check SDK!
