### ISSUE TITLE
Parallelize Core-Setup publish steps to mitigate PDB conversion time

### ISSUE THREAD

**Issue by MattGal** [dotnet/core-setup#3757] opened 2018-03-01 21:55 UTC
@dagood commented on [Mon Jan 08 2018](https://github.com/dotnet/core-eng/issues/2369)

See https://github.com/dotnet/core-setup/pull/3574

---

@maririos commented on [Thu Jan 11 2018](https://github.com/dotnet/core-eng/issues/2369#issuecomment-357065608)

We are not in a position to own this issue, but please contact @dagood for guidance.
@lt72 @mikem8361 

---

@mikem8361 commented on [Thu Mar 01 2018](https://github.com/dotnet/core-eng/issues/2369#issuecomment-369688915)

We need this issue to track this work.

---

@MattGal commented on [Thu Mar 01 2018](https://github.com/dotnet/core-eng/issues/2369#issuecomment-369744081)

This is being tracked in the above linked issue (in the core-setup repo, dotnet/core-setup#3574 )

---

@MattGal commented on [Thu Mar 01 2018](https://github.com/dotnet/core-eng/issues/2369#issuecomment-369744281)

Moving this one to core-setup so you can track

---

@MattGal commented on [Thu Mar 01 2018](https://github.com/dotnet/core-eng/issues/2369#issuecomment-369744329)

Issue moved to [dotnet/core-setup #3756](https://github.com/dotnet/core-setup/issues/3756) via [**ZenHub**](https://www.zenhub.com/)

**Comment by weshaggard** [comment] 2018-03-06 00:41
duplicate of https://github.com/dotnet/core-setup/issues/3757

**Closed by weshaggard** 2018-03-06 00:41 UTC
Labels: area-Infrastructure
