### ISSUE TITLE
Microsoft.Extensions.DependencyModel 1.1.9 has a reference to Microsoft.DotNet.PlatformAbstractions

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/core-setup#4233] opened 2018-06-14 16:55 UTC
## Steps to reproduce
call Assembly.Load() on Microsoft.Extensions.DependencyModel.

## Expected  behavior
Applications loading Microsoft.Extensions.DependencyModel 1.1.9 should succeed.

## Actual behavior
Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=1.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

## Environment data
"Microsoft.Extensions.DependencyModel": "1.1.9-servicing-001750"

**Comment by eerhardt** [comment] 2018-06-14 17:01
The reason this happened is because I was trying to limit the number of packages we were servicing. We only changed the DependencyModel assembly, and not PlatformAbstractions. So I was trying to keep the new DependencyModel version to reference the previously shipped PlatformAbstractions.

However, we are still using `project.json`, in the 1.1 branch. And in `project.json`, it has a "duality" system between project and package references. It isn't possible to reference a previously shipped version of a project in your "solution". It will always pick the project-to-project reference to build against. (By design, it was made this way to support cloning a repo next to your project, fixing a bug, and then using that cloned version without changing the project.json.)

To fix this, my plan is to ship new versions of both DependencyModel and PlatformAbstractions for `1.1.9`. Keeping these two packages in sync is the simplest solution, and it doesn't fight the build system.

/cc @weshaggard - this is the bug I was referring to.

**Comment by eerhardt** [comment] 2018-07-10 22:18
This is now fixed by #4234

**Closed by eerhardt** 2018-07-10 22:18 UTC
Labels: area-DependencyModel, blocking-servicing, bug
