### ISSUE TITLE
"Failed to initialize CoreCLR, HRESULT: 0x80004005" when $TMPDIR is not writeable/nonexistent

### ISSUE THREAD

**Issue by jacobrillema** [dotnet/core-setup#4149] opened 2018-05-14 07:29 UTC
## Steps to reproduce
```bash
sudo apt-get install dotnet-sdk-2.1.300-rc1-008673
dotnet --version

sudo dotnet --version
```
## Expected  behavior
```bash
dotnet --version
2.1.300-rc1-008673

sudo dotnet --version
2.1.300-rc1-008673
```

## Actual behavior
```bash
dotnet --version
Failed to initialize CoreCLR, HRESULT: 0x80004005

sudo dotnet --version
2.1.300-rc1-008673
```

## Environment data
```bash
dotnet --info
Failed to initialize CoreCLR, HRESULT: 0x80004005

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

uname -a
Linux BSS-IMM 4.4.0-17134-Microsoft #48-Microsoft Fri Apr 27 18:06:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by danmosemsft** [comment] 2018-05-14 18:06
So it works fine under sudo? That's interesting. If you use `strace` is it possible to see what we are failing to access?

**Comment by jacobrillema** [comment] 2018-05-14 18:39
I just tried running 2.1.200 SDK install and it works fine without sudo. I ran the strace again on the RC candidate and here is the area I think it is failing on.

```bash
591 14020 unlink("/mnt/c/Users/jrillema/AppData/Local/Temp/clr-debug-pipe-14020-209726-in") = -1 ENOENT (No such file or directoy>
4592 14020 mknod("/mnt/c/Users/jrillema/AppData/Local/Temp/clr-debug-pipe-14020-209726-in", S_IFIFO|0700) = -1 EPERM (Operation n>4593 14020 futex(0x7fc55a725680, FUTEX_WAKE_PRIVATE, 2147483647) = 0
4594 14020 write(2, "Failed to initialize CoreCLR, HR"..., 49) = 49
```

So that local temp directory is a Windows symbolic link to another drive. Could that be causing the issues? I will try and put that back to a local folder and try again.

**Comment by danmosemsft** [comment] 2018-05-14 18:46
@jacobrillema would it be possible to write a little C program that did just `mknod("/mnt/c/Users/jrillema/AppData/Local/Temp/clr-debug-pipe-14020-209726-in", S_IFIFO|0700)` ? 

If you set the env variable as noted in https://github.com/dotnet/coreclr/pull/15878 it should work around this.

Related discussion https://github.com/dotnet/coreclr/issues/8844

I don't see any note of EPERM + mknod on WSL issues: https://github.com/Microsoft/WSL/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mknod

cc @mikem8361  fyi.

**Comment by jacobrillema** [comment] 2018-05-14 18:52
@danmosemsft Thanks for the all your feedback and the trick with the environment variable fixed it. 

I will give the small C program a try and report back. i tried flipping the temp folder back to a local directory and not a symbolic link and I still got the same error reported in the strace log file.

**Comment by danmosemsft** [comment] 2018-05-14 19:06
Maybe try your C program against that location and also another one on your Windows disk that doesn't involve a symbolic link. 

Depending on what you find you'll probably want to open a bug in  https://github.com/Microsoft/WSL. Please include the repro app, info about how to set up the file system to repro it, and the relevant output of strace. Plus your versions of course.

**Comment by danmosemsft** [comment] 2018-05-14 19:07
@jkotas another case where I wish customers had something better than `Failed to initialize CoreCLR, HRESULT: 0x80004005` Even if it's just a code indicating what phase it failed in that they can search for.

**Comment by jacobrillema** [comment] 2018-05-15 04:36
@danmosemsft Couple updates here. So i noticed in the strace log file when I run the dotnet --version command with sudo the pipe gets created in /tmp, not the user's local temp folder. When i run the following mkfifo command I can confirm this issue.

```bash
cd /mnt/c/Users/jrillema/AppData/Local/Temp

pwd
/mnt/c/Users/jrillema/AppData/Local/Temp

mkfifo testfifo
mkfifo: cannot create fifo 'testfifo': Operation not permitted

cd /tmp

mkfifo testfifo

ls -ltr testfifo
prw-rw-rw- 1 jrillema jrillema 0 May 15 00:33 testfifo
```

So the problem here is out of the box with the new RC this is broken on WSL. The latest 2.1.200 SDK it still works. I will create a case on the WSL team but I am concerned that out of the box this will be problematic for WSL users when 2.1 SDK drops.

The work around that you mentioned before still works so I will go with that for now. Please let me know if you need any more information from this end. Thanks again for all your help on this one!

**Comment by danmosemsft** [comment] 2018-05-15 05:34
@anipik can you please try to repro this? You should use a clean WSL instance.

**Comment by Anipik** [comment] 2018-05-15 05:36
@danmosemsft okay i am on it

**Comment by Anipik** [comment] 2018-05-15 06:49
@danmosemsft i was not able to repro it on a clean WSL.
Steps that i follwed after enabling wsl on my machine
```
wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.300-rc1-008673
```

# Output
```
anipik@MININT-DK46LQL:~$ sudo dotnet --version
2.1.300-rc1-008673 
anipik@MININT-DK46LQL:~$ dotnet --version
2.1.300-rc1-008673
```

# Environment Data
```
anipik@MININT-DK46LQL:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

anipik@MININT-DK46LQL:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

# Difference
The only different part in these is 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73
```

**Comment by jacobrillema** [comment] 2018-05-15 07:03
What Windows version are you running? Also if you run a strace on the commands is the pipe getting created in /tmp or the user's local temp folder?

Microsoft Windows [Version 10.0.17134.48]

**Comment by jkotas** [comment] 2018-05-15 07:17
It looks like the error handling have changed in .NET Core 2.1:

```bash
dotnet --version
export TMPDIR=/nonexistent
dotnet --version
```

In .NET Core 2.0, the bogus TMPDIR was silently ignored.
In .NET Core 2.1, the bogus TMPDIR causes hard failure.

**Comment by jacobrillema** [comment] 2018-05-15 07:27
Ah that is it. I have the following.

```bash
dotnet --version
Failed to initialize CoreCLR, HRESULT: 0x80004005

echo $TMPDIR
/mnt/c/Users/jrillema/AppData/Local/Temp

export TMPDIR=/tmp
dotnet --version
2.1.300-rc1-008673
```

If I change it to /tmp it works! Nice catch @jkotas and thanks for the feedback. I tried this with not opting out of the COMPlus_EnableDiagnostics and it is still working.

Not sure how we should handle that or how to document it. I guess the ownership of the issue is with WSL team? I will update their issue to indicate why this showed up now with .NET Core SDK.

Thanks everybody for your help on this one!

**Comment by jkotas** [comment] 2018-05-15 14:02
@mikem8361 Was the change from silently ignoring the failure to create debug pipes to hard error intentional?

**Comment by danmosemsft** [comment] 2018-05-15 16:41
@jacobrillema can you clarify, in your repro case, you have $TMPDIR set to /mnt/c/Users/jrillema/AppData/Local/Temp, did that not exist? As I see higher up that you cd'd to it. If it does exist, then that suggests that a bad $TMPDIR was not the cause in your case?

Or is this the case
* mknod in WSL against a Windows folder fails and possibly has always failed
* your TMPDIR was pointed to the Windows folder
* recently, we begun failing if the mknod failed against TMPDIR

?

**Comment by jacobrillema** [comment] 2018-05-16 04:47
> FYI I copied this conversation over from the WSL [issue](https://github.com/dotnet/core-setup/issues/4149) created. 

That metadata blog post did specify special files like pipes would be supported. So I went back through to see how I was mounting my /mnt/c drive and sure enough I did not opt in to the new metadata drvfs approach. I created a /etc/wsl.conf with the following:

```bash
[automount]
enabled = true
options = "metadata,uid=1000,gid=1000,umask=22,fmask=111"
mountFsTab = true
```
Note I have mountFsTab set so I can access my SD card. So after enabling this metadata and keeping my original TMPDIR set I was able to get pass the critical error from the .NET SDK. See my results below

```bash
dotnet --version
2.1.300-rc1-008673

mount -l | grep "C:"
C: on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,fmask=111,metadata)

echo $TMPDIR
/mnt/c/Users/jrillema/AppData/Local/Temp

cd $TMPDIR
pwd
/mnt/c/Users/jrillema/AppData/Local/Temp

mkfifo testfifo
ls -tlr testfifo
prw-rw-rw- 1 jrillema jrillema 0 May 16 00:37 testfifo
```
So I was able to get this working with opting into the new drvfs metadata options. Here is the link and search for [special files](https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/) The whole reason I went down this path was to accomodate running a [Beyond Compare](https://www.sep.com/sep-blog/2017/06/07/20170607wsl-git-and-beyond-compare/) diff session from inside WSL. 

I appreciate everybody's help on this one. I will play around a bit more with testing this the next few days to make sure it is working. I would suspect we might be able to close this out here if it works. I am not sure how new WSL installations are handled with the new metadata by default but I am working with an older WSL installation.

**Comment by danmosemsft** [comment] 2018-05-16 04:59
@jkotas do you believe it is worth making CLR start when $TMPDIR is bad? I don't like inexplicable startup failures and this seems to be the only point during startup that if affected.
I don't think the priority is high though

**Comment by jkotas** [comment] 2018-05-16 05:38
Yes, I think it would be worth it. Or at least make it easier to diagnose.

**Comment by bdaniel7** [comment] 2018-10-18 13:10
Hi,

I'm trying to run a TeamCity agent in a container.
This is environment:

The TeamCity and the agent are the latest from the container (2018.1.3 (build 58658))
The container is run in Docker for Windows, using Linux containers (because the production will run on Ubuntu).

root@teamcity-agent3:/opt/buildagent/work/70bf5e8b1cc61bbe/src# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

When I run the build using

`/opt/buildagent/work/70bf5e8b1cc61bbe/src# /usr/bin/dotnet build trains.sln --framework netcoreapp2.1 --configuration Release --runtime ubuntu-x64`

in the container, the build is successful.

However when I run the same command as part of a build step, I get this error:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

Any ideas on why this error occurs?

**Comment by mikem8361** [comment] 2018-10-18 17:12
You could try disabling debugging with `export COMPlus_EnableDiagnostics=0`.  There are some pipes that that are created in /tmp that this disables.

https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md#disabling-managed-attachdebugging

**Comment by bdaniel7** [comment] 2018-10-18 19:02
Thanks,

The setting will be in effect immediately, or do I have to reboot the container (or logout, login)?

**Comment by mikem8361** [comment] 2018-10-18 19:29
Effective the next time you launch a dotnet app after setting the environment variable.

**Comment by bdaniel7** [comment] 2018-10-19 09:48
Unfortunately, it has no effect.
I already tried setting that variable.

When I log in the container and `su buildagent` I can use the `dotnet` commands successfully. But the build step from TeamCity still fails.

**Comment by bdaniel7** [comment] 2018-10-19 11:58
Actually, it works.
Previously I set the variable in the context of the root, and not in the context of the `buildagent` user.

What a dummy I am...

**Comment by lpereira** [comment] 2019-06-05 17:20
By default, `$TMPDIR` is empty on WSL, so `dotnet` should default to `/tmp`, which is on a `lxfs` volume -- thus supporting pipes, FIFOs, and other Unixy things.

Setting `$TMPDIR` to anything under a `drvfs` will make `dotnet` fail with a less than helpful error message (`drvfs` merely proxies Windows volumes to the WSL world, so I don't think this will be supported even under WSL2 -- don't quote me on that, I haven't tested it).

Maybe this should be fixed in the documentation instead?

**Comment by jeffschwMSFT** [comment] 2019-06-12 22:12
Closing in favor of the PRs to help make this experience better: https://github.com/dotnet/core-setup/pull/6692 and https://github.com/microsoft/WSL/issues/4038

**Closed by jeffschwMSFT** 2019-06-12 22:12 UTC
Labels: area-Host
