### ISSUE TITLE
ARM32 builds are not crossgen:ed

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/core-setup#3314] opened 2017-10-15 19:39 UTC
Startup performance on Linux ARM32 suffers today. 

It would be helpful if the core-setup build for linux-arm could produce a crossgen:ed output.  

I do believe ryujit is a must before this can happen but work seems to have progressed in this area. [13804@coreclr](https://github.com/dotnet/coreclr/issues/13804) seems to cover this?!

**Comment by Petermarcu** [comment] 2017-10-16 02:40
This is two issues. The ability to crossgen other assemblies in your application is tracked here: https://github.com/dotnet/cli/issues/1437

We can use this issue to track getting the runtime crossgen'd on arm32.

**Comment by JensNordenbro** [comment] 2017-10-16 18:27
ok @Petermarcu ; I deleted the "crossgen other assemblies"-part in the original posting,

**Comment by Petermarcu** [comment] 2017-10-19 03:52
We've talked a bit about this and the work is:
1. Make sure the arm32 crossgen tool is being provided from coreclr builds.
2. Consume that tool here in coresetup and run the crossgen step on a machine that is configured to support 32bit.
3. Ensure the crossgen'd bits end up in the final tar.gz's and packages

**Comment by steveharter** [comment] 2018-01-10 20:27
Moving to 2.2.0 as dotnet/cli#1437 is 2.2.0

**Comment by JensNordenbro** [comment] 2018-01-10 20:46
Why not move the other issue to 2.1? Startup performance on arm needs love! 

Or will ryujit or readytorun or some other thing I hear of sometimes somehow help the startup performance on arm already at 2.1?

**Comment by steveharter** [comment] 2018-01-11 20:18
Changed back to 2.1.0 for now. It looks like the 2.1.0 label got mass-renamed to 2.2.0 for CLI

**Comment by JensNordenbro** [comment] 2018-01-11 20:22
Great!

**Comment by weshaggard** [comment] 2018-03-06 00:39
@eerhardt is this something you are looking into?

**Comment by eerhardt** [comment] 2018-03-06 01:37
Yes. Once the coreclr enables crossgen to work on Linux arm, I’ll crossgen Microsoft.NETCore.App with it.

**Comment by JensNordenbro** [comment] 2018-03-06 20:24
@eerhardt , is there an issue(s) tracking the progress on "coreclr enables crossgen to work on Linux arm". I see many references to RyuJIT/crossgen and arm but none of them are spot on.

**Comment by eerhardt** [comment] 2018-03-06 20:27
I believe it is https://github.com/dotnet/coreclr/issues/16513

but @RussKeldorph @echesakovMSFT @jashook  would know for sure

**Comment by eerhardt** [comment] 2018-03-23 23:46
Closed with #3892.  An official build of master is running now.

**Closed by eerhardt** 2018-03-23 23:46 UTC
Labels: area-Infrastructure

**Comment by jamespettigrew** [comment] 2018-03-27 08:33
@eerhardt, I may be under the same misapprehension as @JensNordenbro as I have tested today's master build (2.1.0-preview3-26326-02) and see neither any included .ni files nor any improvements in the very slow startup performance.

**Comment by JensNordenbro** [comment] 2018-03-27 11:52
@jamesspettigrew, I have not had the opportunity to test it, but will report back when I have. As i understand it aspnet stuff will not be included and ni files has been absorbed into the readytorun assemblies, but I could be wrong.

**Comment by eerhardt** [comment] 2018-03-27 13:14
The managed assemblies that are crossgen'd in this repo (`dotnet/core-setup`) are being crossgen'd for the `linux-arm` build.  The main assembly left is `System.Private.CoreLib`, which is a fairly large assembly.  It gets crossgen'd in the `dotnet/coreclr` repo, see https://github.com/dotnet/coreclr/pull/17157.

The issue is we haven't had an official build of `dotnet/coreclr` since that change.  So System.Private.CoreLib in the current builds isn't crossgen yet, since we don't have a good build of `dotnet/coreclr`.  Once this happens, you should see startup times come down.

Also note that we don't use the `.ni.dll` extension for ready-to-run crossgen'd assemblies.  We just use `.dll` like usual.

**Comment by eerhardt** [comment] 2018-03-27 13:17
I just looked, and we got an official build of `dotnet/coreclr` out last night.  So the next master build of `core-setup` should have a crossgen'd `System.Private.CoreLib`.

**Comment by JensNordenbro** [comment] 2018-03-27 13:41
@eerhardt, good info! what about asp net core assemblies. Will they still not be crossgened?

**Comment by eerhardt** [comment] 2018-03-27 14:02
I’m not certain when it will happen.

Check out https://github.com/aspnet/Universe/issues/554
