### ISSUE TITLE
dotnet --info show incorrect versions of SDK installed on Windows

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#4179] opened 2018-05-31 16:34 UTC
_From @EdiWang on May 31, 2018 2:52_

## Steps to reproduce
run "dotnet --info"

## Expected  behavior
List all the SDKs installed on Windows

## Actual behavior
List the SDKs that has been uninstalled, but have an empty folder with SDK version numbers still in "C:\Program Files\dotnet\sdk"

![image](https://user-images.githubusercontent.com/3304703/40758582-9caa72e6-64c0-11e8-94e2-2a44d76cbfc9.png)

And you can actually try create a new folder and name it: 2.0.233333, it will show up:

![image](https://user-images.githubusercontent.com/3304703/40758587-a2ffe496-64c0-11e8-99b0-fad627ed51fb.png)

_Copied from original issue: dotnet/cli#9372_

**Comment by livarcocc** [comment] 2018-05-31 16:34
_From @yanxiaodi on May 31, 2018 3:9_

That's interesting...haha. 😄

**Comment by steveharter** [comment] 2018-05-31 17:31
This is by design. The framework itself will attempt to use the folder version, so `--info` uses that same logic. We could change

**Comment by steveharter** [comment] 2018-06-05 20:58
Closing as by design. At runtime or when using `--info` we don't very existence or "crack open" any files within each folder to check if the directory is valid or not.

We do, however, verify the directory has a proper naming convention of major.minor.build.

**Closed by steveharter** 2018-06-05 20:58 UTC
