### ISSUE TITLE
3.0.100-preview-009844 SDK corrupts relative paths

### ISSUE THREAD

**Issue by sandreenko** [dotnet/core-setup#4884] opened 2018-12-20 00:50 UTC
## Steps to reproduce
on windows x64 machine:
1. Install 3.0.100-preview-009844 (https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.exe)
2. Clone CoreCLR (git clone https://github.com/dotnet/coreclr.git);
3. build CoreCLR:
  build.cmd x64 checked
4. See output.
## Expected  behavior
build should succeed.

## Actual behavior
dotnet.exe fails with:
```
                   "F:\git\coreclr\build.proj" (default target) (1) ->
                   "F:\git\coreclr\src\build.proj" (Build target) (2) ->
                   (BuildR2RDumpPackages target) ->
                     F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj'. [F:\git\coreclr\src\build.proj]
                     F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj'. [F:\git\coreclr\src\build.proj]
                     F:\git\coreclr\src\build.proj(30,5): error MSB3073: The command "F:\git\coreclr\Tools\dotnetcli\dotnet.exe build /p:__BuildArch=x64 /p:__BuildOS=Windows_NT /p:__BuildType=Checked tools/r2rdump/R2RDump.csproj" exited with code 1.
```

if you go deeper you will find that the command that fails is:

```
F:\git\coreclr\src>F:\git\coreclr\Tools\dotnetcli\dotnet.exe build /p:__BuildArch=x64 /p:__BuildOS=Windows_NT /p:__BuildType=Checked tools/r2rdump/R2RDump.csproj
Microsoft (R) Build Engine version 16.0.284-preview+g7905402dc6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 27.43 ms for F:\git\coreclr\src\tools\r2rdump\R2RDump.csproj.
F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj'.

Build FAILED.

F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path 'F:\git\coreclr\src\tools\r2rdump\tools\r2rdump\R2RDump.csproj'.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.59
```
when the same command with the full path works normally:
```
F:\git\coreclr\src>F:\git\coreclr\Tools\dotnetcli\dotnet.exe build /p:__BuildArch=x64 /p:__BuildOS=Windows_NT /p:__BuildType=Checked F:\git\coreclr\src\tools\r2rdump\R2RDump.csproj
Microsoft (R) Build Engine version 16.0.284-preview+g7905402dc6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 27.61 ms for F:\git\coreclr\src\tools\r2rdump\R2RDump.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview-009844\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(142,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [F:\git\coreclr\src\tools\r2rdump\R2RDump.csproj]
  R2RDump -> F:\git\coreclr\bin\Product\Windows_NT.x64.Checked\netcoreapp2.0\R2RDump.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.88
```

```

## Environment data

 windows x64

**Comment by sandreenko** [comment] 2018-12-20 00:50
cc @dotnet/jit-contrib

**Comment by rakeshsinghranchi** [comment] 2018-12-20 19:05
@johnbeisner, @livarcocc  - Can you take a look at this issue related to SDK ?

**Comment by EgorBo** [comment] 2018-12-25 22:41
I am experiencing the same issue, dotnet 3.0.100-preview-009844

**Comment by RussKeldorph** [comment] 2019-01-04 17:47
@livarcocc Can you route this?  If this isn't the right repo, please move or let us know where to put it.

**Comment by sandreenko** [comment] 2019-01-15 20:14
a simpler repro:
I tested it on Ubuntu 18.04 but think that it  affects Windows as well.

Steps to reproduce:
1. Download Linux x64 DEB Installer and install it;
2. build a simple console app:
```
mkdir testDotnetBuild
cd testDotnetBuild/
dotnet new console
dotnet build
```

the result should be like:
```
dotnet new console
Getting ready...
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/sergey/workTests/testDotnetBuild/testDotnetBuild.csproj...
  Restoring packages for /home/sergey/workTests/testDotnetBuild/testDotnetBuild.csproj...
  Generating MSBuild file /home/sergey/workTests/testDotnetBuild/obj/testDotnetBuild.csproj.nuget.g.props.
  Generating MSBuild file /home/sergey/workTests/testDotnetBuild/obj/testDotnetBuild.csproj.nuget.g.targets.
  Restore completed in 116.87 ms for /home/sergey/workTests/testDotnetBuild/testDotnetBuild.csproj.

Restore succeeded.

sergey@seandree-Ubuntu:~/workTests/testDotnetBuild$ ls
obj  Program.cs  testDotnetBuild.csproj
sergey@seandree-Ubuntu:~/workTests/testDotnetBuild$ dotnet build 
obj/                    Program.cs              testDotnetBuild.csproj  
sergey@seandree-Ubuntu:~/workTests/testDotnetBuild$ dotnet build testDotnetBuild.csproj 
Microsoft (R) Build Engine version 16.0.284-preview+g7905402dc6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 18.23 ms for /home/sergey/workTests/testDotnetBuild/testDotnetBuild.csproj.
/usr/share/dotnet/sdk/3.0.100-preview-009844/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(142,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/home/sergey/workTests/testDotnetBuild/testDotnetBuild.csproj]
  testDotnetBuild -> /home/sergey/workTests/testDotnetBuild/bin/Debug/netcoreapp3.0/testDotnetBuild.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```
now go one folder up and try to build again:
```
sergey@seandree-Ubuntu:~/workTests/testDotnetBuild$ cd ..
sergey@seandree-Ubuntu:~/workTests$ dotnet build testDotnetBuild
Microsoft (R) Build Engine version 16.0.284-preview+g7905402dc6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 18.03 ms for /home/sergey/workTests/testDotnetBuild/testDotnetBuild.csproj.
/home/sergey/workTests/testDotnetBuild/testDotnetBuild/testDotnetBuild.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path '/home/sergey/workTests/testDotnetBuild/testDotnetBuild/testDotnetBuild.csproj'.

Build FAILED.

/home/sergey/workTests/testDotnetBuild/testDotnetBuild/testDotnetBuild.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path '/home/sergey/workTests/testDotnetBuild/testDotnetBuild/testDotnetBuild.csproj'.
    0 Warning(s)
    1 Error(s)
```

**Comment by dleeapho** [comment] 2019-01-16 17:43
@livarcocc should this be moved to the core-sdk repo?

**Comment by nguerrera** [comment] 2019-02-17 16:58
@peterhuene @rainersigwald Is this by chance the issue in msbuild you mentioned on Friday?

**Comment by peterhuene** [comment] 2019-02-18 22:30
@nguerrera That issue was Microsoft/msbuild#4175 and at first glance does not seem related to this issue since that has to do with globbing.

It's odd that the restore completes just fine with the correct path, but then suddenly the path is wrong.  I wasn't able to repro the issue with `3.0.100-preview-010142` on Windows, at least.

@rainersigwald does this sound like a familiar regression in MSBuild that might have been fixed?

**Comment by nguerrera** [comment] 2019-02-18 23:19
Oh I think I remember this one. Looking for the link.

**Comment by nguerrera** [comment] 2019-02-18 23:21
This was fixed by 
https://github.com/Microsoft/msbuild/pull/4039

**Closed by nguerrera** 2019-02-18 23:21 UTC
Labels: area-SDK, bug, os-windows

**Comment by nguerrera** [comment] 2019-02-18 23:23
The note about restore working jogged my memory. :)
