### ISSUE TITLE
Fail to install dotnet core 2.2/3.0 on SLES 12

### ISSUE THREAD

**Issue by turowicz** [dotnet/core-setup#8347] opened 2019-09-27 13:12 UTC
I get the following error for runtime:

```
joe@linux-j77d:~> sudo zypper install dotnet-runtime-2.2
Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP3_x86_64'.
Refreshing service 'SUSE_Package_Hub_12_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libopenssl1_1 needed by dotnet-runtime-deps-2.2-2.2.7-1.x86_64
 Solution 1: do not install dotnet-runtime-2.2-2.2.7-1.x86_64
 Solution 2: break dotnet-runtime-deps-2.2-2.2.7-1.x86_64 by ignoring some of its dependencies
```

I get the following error for asp.net runtime:

```
joe@linux-j77d:~> sudo zypper install aspnetcore-runtime-2.2
Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP3_x86_64'.
Refreshing service 'SUSE_Package_Hub_12_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libopenssl1_1 needed by dotnet-runtime-deps-2.2-2.2.7-1.x86_64
 Solution 1: do not install aspnetcore-runtime-2.2-2.2.7-1.x86_64
 Solution 2: break dotnet-runtime-deps-2.2-2.2.7-1.x86_64 by ignoring some of its dependencies
```

**Comment by turowicz** [comment] 2019-09-27 13:13
3.0 is broken too:

```
joe@linux-j77d:~> sudo zypper install dotnet-runtime-3.0
Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP3_x86_64'.
Refreshing service 'SUSE_Package_Hub_12_SP3_x86_64'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libopenssl1_1 needed by dotnet-runtime-deps-3.0-3.0.0-1.x86_64
 Solution 1: do not install dotnet-runtime-3.0-3.0.0-1.x86_64
 Solution 2: break dotnet-runtime-deps-3.0-3.0.0-1.x86_64 by ignoring some of its dependencies
```

**Comment by turowicz** [comment] 2019-09-27 13:13
cc @leecow @rakeshsinghranchi @vivmishra

**Comment by dagood** [comment] 2019-09-27 13:58
This is tracked by https://github.com/dotnet/core-setup/issues/8277, and the user who reported that issue listed workaround steps at https://github.com/dotnet/core-setup/issues/8277#issuecomment-532148224.

**Comment by dagood** [comment] 2019-09-27 13:58
Duplicate of https://github.com/dotnet/core-setup/issues/8277

**Closed by dagood** 2019-09-27 13:58 UTC

**Comment by turowicz** [comment] 2019-09-27 15:33
@dagood doesn't that mean that as soon as he tries doing any SSL operations in .NET Core it will blow up?

**Comment by dagood** [comment] 2019-09-27 15:51
Not quite, .NET Core works with openssl 1.0 and 1.1, whichever is available. The workaround tells the package manager to ignore our package's incorrect dependency on 1.1, and this is ok because we know 1.0 is actually installed.

(RPM added logical dependencies recently--the way to express "we can use 1.0 *or* 1.1" in an RPM. But it's too recent: using it would make our package incompatible with nearly every distro due to old package manager dependencies. 😞)

**Comment by turowicz** [comment] 2019-10-01 15:31
ok @dagood as long as it works
