### ISSUE TITLE
Daily build links are all broken

### ISSUE THREAD

**Issue by cocowalla** [dotnet/core-setup#4245] opened 2018-06-17 19:38 UTC
All the daily build links in this repo's main readme.md file are broken.

For example, the Windows x64 installer [link](https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-runtime-latest-win-x64.exe) gives `ResourceNotFound`.

**Comment by leecow** [comment] 2018-06-18 15:07
Something was messed up with the azure account for the storage. Should be good to go now.

**Comment by steveharter** [comment] 2018-06-18 15:32
Dupe of https://github.com/dotnet/core-setup/issues/4200

**Closed** 2018-06-18 15:56 UTC
Labels: area-Infrastructure
