### ISSUE TITLE
Deploy single runtime for .NET Core

### ISSUE THREAD

**Issue by cup** [dotnet/core-setup#8862] opened 2019-11-18 18:21 UTC
I would like to create a new program that relies on the .NET Core.

Previously I have created programs that rely on .NET Framework. In those
cases, I would simply direct a user here:

https://dotnet.microsoft.com/download/dotnet-framework/net48

where they can download and install .NET Framework Runtime. However now it seems
that applications using .NET Core require both ".NET Core Runtime" and
".NET Core Desktop Runtime" as shown here:

https://dotnet.microsoft.com/download/dotnet-core/3.0/runtime

Are both actually required? If no, which one is required? If yes, why are they
not bundled into a single installer like .NET Framework? Do cases exist where
someone would want to install one but not the other?

**Comment by dagood** [comment] 2019-11-18 18:38
> Are both actually required?

Yes, unfortunately. We have improved this in 3.1: https://dotnet.microsoft.com/download/dotnet-core/3.1/runtime

The old installer that only includes the .NET Core Runtime without WindowsDesktop will continue to be available, because people may only need to run console apps (e.g. services) and want to save space or reduce the amount of code on the machine that could need security patches.

Notice that even with .NET Core Runtime and WindowsDesktop bundled, you still need to be careful whether you install x86 or x64, or just install both. That choice depends on how the app was published, not the machine's architecture. We're also looking at bundling those together, tracked in https://github.com/dotnet/windowsdesktop/issues/136.

**Comment by dagood** [comment] 2019-11-18 18:38
Duplicate of https://github.com/dotnet/core-setup/issues/8504

**Closed by dagood** 2019-11-18 18:38 UTC

**Comment by cup** [comment] 2019-11-18 18:49
@dagood can you clarify? It sounds like you are saying that command line programs, AKA console programs can be run with only ".NET Core Runtime" and without ".NET Core Desktop Runtime".

Is that the case?

**Comment by dagood** [comment] 2019-11-18 18:50
@cup It's not a huge deal, but I've got two mails from you with only an issue link and I'm wondering what the goal is. It seems like maybe it's to create extra back-links (like the one above), is that the case? Is there something I can do to help while avoiding unnecessary mails to everyone subscribed to those threads?

> can you clarify? It sounds like you are saying that command line programs, AKA console programs can be run with only ".NET Core Runtime" and without ".NET Core Desktop Runtime".

That's right--as long as you don't need WPF or WinForms, you don't need the Desktop Runtime (aka WindowsDesktop).

**Comment by cup** [comment] 2019-11-18 18:52
> Is there something I can do to help while avoiding unnecessary mails to everyone subscribed to those threads?

If you know a way to create the back-links without mails, I will do that.

> That's right--as long as you don't need WPF or WinForms, you don't need the Desktop Runtime (aka WindowsDesktop).

Thanks!

**Comment by dagood** [comment] 2019-11-18 18:56
> If you know a way to create the back-links without mails, I will do that.

Why do you want the extra links? What does that provide over the "forward" links here? (The link in the comment + the `marked this as a duplicate of` link?)

At a minimum I think it would be friendlier to add context to the back-link-creation dummy comments explaining why the backlink is important and that you will be deleting the comment, so subscribers can delete the spam without wondering what it's about.

**Comment by cup** [comment] 2019-11-18 18:58
@dagood I would prefer not to explain why I want them. However going forward if I see you in a thread I will not post them, thanks.

**Comment by dagood** [comment] 2019-11-18 19:05
My concern is that other users may be annoyed but not complaining about the unwanted emails as a result of this, but it's up to you.

**Comment by dagood** [comment] 2019-11-25 16:54
@cup I realized that I have a way to do this that I've been using without realizing:

> If you know a way to create the back-links without mails, I will do that.

If you edit a comment you already made on an issue thread and add a link, GitHub won't broadcast a notification. (At least, as far as I can tell you can't get notifications for edits). This creates the backlink, and you can edit your comment back and the backlink stays.

**Comment by cup** [comment] 2019-11-25 17:00
hm ok - that only works if youve already made a comment - but thats a good tip

will use that going forward - thanks!
