### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.Win32.Registry'

### ISSUE THREAD

**Issue by nefcanto** [dotnet/core-setup#3703] opened 2018-02-17 06:48 UTC
## Steps to reproduce
Please refer to [this issue](https://github.com/aspnet/Razor/issues/2085).

## Expected  behavior
Tell us where did you search for, and why didn't you find it. At least give us some clue on how to solve this issue. A library is supposed to work out of the box, just like a car, and in case of problems, it should give us more hints to facilitate troubleshooting. It just says that it can't find a library. As much as I see that library exists in the bin folder. So why it can't find it. What's the problem? Why it can find other libraries and can't find this one? Where did it search for? What options do I have? What can I do to solve it? Give us more information please.

## Actual behavior
A simple sentence tells us that something can't be found. While it's just there, like any other DLL it's just there.

## Environment data
.NET Core 2.0.5
.NET SDK 2.1.4
.NET Runtime 2.0.5
Visual Studio Community 2017 15.5.6
Window Server Standard 2012 R2

**Comment by steveharter** [comment] 2018-02-22 16:00
cc @eerhardt

**Comment by eerhardt** [comment] 2018-02-23 02:51
Duplicate of https://github.com/dotnet/core-setup/issues/3489

**Closed by eerhardt** 2018-02-23 02:51 UTC
Labels: area-DependencyModel
