### ISSUE TITLE
linux-armhf 2.0.1-servicing is incompatible with official 2.0.0 version

### ISSUE THREAD

**Issue by nzain** [dotnet/core-setup#3072] opened 2017-08-21 14:46 UTC
Since dotnet core 2.0 was officially released, my app built on win-x64 does not run on linux-arm anymore. Put differently: Where is the matching linux-arm download for dotnet core 2.0.0? (I know that arm support is experimental)

Related: #2862 #1530

## Steps to reproduce
- On your favorite x64 (build) machine download the final dotnet core 2.0.0 release from https://www.microsoft.com/net/download/core
  - `dotnet new web -o foo` to create a new project foo that targets `netcoreapp2.0`
  - add the RID for linux-arm in your csproj: `<RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>`
  - `dotnet publish` and copy to your linux arm device.
- Since there is no official dotnet-linux-arm download (only linux-x64) go to https://github.com/dotnet/core-setup and download the linux-armhf version for glibc based systems.
  - The [download link](https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.0.0/dotnet-runtime-latest-linux-arm.tar.gz) did not change for a while, but the version label indicates `2.0.1-servicing-25615-03` (at the time of writing). I failed at URL hacking :)
  - install (untar, symlink) dotnet on your linux arm device
- run the app on your linux-arm device: `dotnet foo.dll`

## Expected  behavior
The application runs.

## Actual behavior
The framework seems to be incompatible.
```
# dotnet foo.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '2.0.0'.
```

## Environment data (build machine)
```
C:\somewhere> dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

## Environment data (linux-arm device)
```
# dotnet --info
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.1-servicing-25615-03
  Build    : 715604ad09b5fda1445436977e7032e6d29aa8f5
```

## Known Workarounds
- I could `publish -r linux-arm` which produces a native executable alongside the app.dll including the whole framework (what a mess). Each and every dotnet app will take more than 60MB, which is not desirable in our scenario. We want a shared framework and multiple small apps. Edit: running on the shared framework is about 10% faster for our scenario.
- EDIT(not working): ~~I could download the matching 2.0.1-servicing-... version for the win-x64 build machines. All other developers would need the same version, not straight forward. Probably not well compatible with other projects.~~ No effect, problem remains.

**Comment by nzain** [comment] 2017-08-22 20:13
Just to clarify, when working with dotnet core 2.0.0-previewX on both win-x64/linux-arm everything was working as expected.

**Comment by Const-me** [comment] 2017-08-28 20:43
@nzain, could you please write more on how to use your `publish -r linux-arm` workaround?
I’ve encountered the same error trying to run on ARM Linux, my `dotnet --info output` matches exactly.
But for my purposes, a 60 MB app is just fine, I only need to make a single one.

The question is, where exactly you are entering that `publish -r linux-arm`? I’m not building my stuff from command line, I’m using VS 2017 IDE instead.  I’m also familiar with MSBuild XML and custom tasks.

Thanks in advance!

**Comment by nzain** [comment] 2017-08-29 05:11
There is no good link, I could share. The best one I found is [this](https://www.hackster.io/Ra5tko/running-native-net-core-apps-on-raspberry-pi-arm-0bb717) but I never needed step 5. Long story short:

**On your x64 developer machine**
1. Install dotnet core 2.0 SDK
2. `dotnet new console`
3. edit the csproj file and add the `linux-arm` [RID](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md) that should have replaced all those specific OS RIDs
4. Restore for your RID: implicit because it is in your csproj or explicit `dotnet restore -r linux-arm`
5. Publish for your RID, always explicit `dotnet publish -r linux-arm -o deploydir` because... well, because of this ticket. The dotnet runtime host doesn't work on linux-arm right now and thus you cannot publish regular byte code. Using the `-r linux-arm` switch will produce an arm hardfloat 32 bit native executable file that works without the dotnet runtime, because it includes it anyways.
6. Copy the `deploydir` folder to your linux-arm device.

**On your linux-arm device**
7. Install native dependencies. This list is shrinking and the [official docs](https://github.com/dotnet/core/blob/master/Documentation/prereqs.md) are wrong. Looks more like requirements for compiling dotnet itself, which is not what we want. Try to install the following: `libunwind libicu liblttng`. Things like libcurl are probably used by the CLI and you can skip it. If you compile your own linux, I suggest buildroot - easy, even if it is your first time. Worked well for us and you can checkmark the above dependencies. Right now, you don't install the dotnet runtime on your arm device.
8. `chmod +x deploydir/consoleapp1`
9. `deploydir/consoleapp1`

Good luck. By the way, performance with a shared dotnet runtime host is better (about 10% in our eval, eventually this is only startup time). Another reason for this ticket.

**Comment by Petermarcu** [comment] 2017-08-29 14:59
The issue is likely that an app compiled against 2.0.0 won't roll forward to a prerelease version. Sounds like the issue is mainly that we haven't made a shared runtime for 2.0.0 arm32 available. If you had that, would this be resolved?

**Comment by nzain** [comment] 2017-08-29 15:37
@Petermarcu yes, this should resolve the issue. Goal is to use "mainstream" dotnet core on developer machines (currently the stable 2.0 release), because it will be used for many different projects and it should be the stable channel. It would be great to have a matching 32bit runtime for linux-arm available somewhere - this is for only one of our projects. I know that arm support is not official, yet - so a download on the core-setup github repository is totally fine. 

Btw. we did not experience any other problems on linux-arm and while asp.net startup time is terrible on such slow devices, the webservice performance itself (mostly json) is awesome after warmup calls.

**Comment by Petermarcu** [comment] 2017-08-29 21:16
@richlander @leecow we need to somehow add links to the downloads for the unsupported/pre-release type builds that came along with 2.0.0.

@nzain you can download it from here:
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.0.0/dotnet-runtime-2.0.0-linux-arm.tar.gz

**Comment by nzain** [comment] 2017-08-30 14:43
@Petermarcu thanks for the link, that runtime version is compatible with the current sdk. Feel free to close this ticket, when this hidden link has some more visibility.

**Comment by livarcocc** [comment] 2018-02-05 17:57
Closing as the issue seems to be resolved.

**Closed by livarcocc** 2018-02-05 17:57 UTC
Labels: area-SDK
