### ISSUE TITLE
Registry entries left behind after uninstalling DotNetCore.1.0.0.RC2-SDK.Preview1-x64

### ISSUE THREAD

**Issue by leecow** [dotnet/core-setup#40] opened 2016-05-28 17:47 UTC
Don't know if we're leaving these behind of if they are Windows Installer artifacts

HKEY_CLASSES_ROOT\Installer\Dependencies\Dotnet_CLI_1.0.0.002702_x64
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store
- C:\ProgramData\Package Cache\{2adee9e7-1f53-47dc-8e30-49ff0dec528e}\dotnet-dev-win-x64.1.0.0-preview1-002702.exe
- C:\Users\[username]\AppData\Local\Temp\{827CEE61-99A0-4091-974F-915706DF8B20}\.be\dotnet-dev-win-x64.1.0.0-preview1-002702.exe
- C:\Users\[username]\Downloads\DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\Dotnet_CLI_1.0.0.002702_x64

**Comment by brthor** [comment] 2016-06-10 17:56
@leecow What installer did you use, and how did you find that these files were being left behind?

**Comment by piotrpMSFT** [comment] 2016-06-10 18:03
@leecow can you provide @brthor with repro steps to get the results you see above? I assume you installed the preview1 bundle, then uninstalled something via ARP. How did you identify the diff specified above? What ARP entry did you uninstall?

**Comment by leecow** [comment] 2016-06-10 20:05
@brthor @piotrpMSFT This would have been installed via the SDK and/or Runtime MSI and uninstalled through ARP. No diff involved, discovered doing manual spelunking through the registry.

**Comment by brthor** [comment] 2016-06-11 00:06
First time digging into the MSIs, but with help from @jhendrixMSFT and @ericstj , tracked down the issue to the static component id here:
https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/clisdk/provider.wxs#L5

causing these components not to get removed properly on uninstall. I changed it to be auto generated and confirmed that sXs installation of cli still works, and that the keys are individually removed when the appropriate versions are removed via ARP. 

My understanding is that by sharing the same componentId, these components will be ref-counted and not removed properly when any version of the cli is still installed. However even if they're all uninstalled they may still not be removed because of this issue mentioned by @robmen (I did not test this scenario however).

https://github.com/dotnet/cli/pull/2789#issuecomment-216359950


Going to follow up with a PR to cli for this, and investigate the SharedFramework MSIs for the same issue early next week.

**Comment by Petermarcu** [comment] 2016-06-11 18:41
@brthor , @eerhardt let's get this one in. CI is failing on one Linux leg but this has no impact on that so things look green.

**Comment by joshfree** [comment] 2016-06-11 22:26
@brthor can this be verified and closed now?

**Comment by joshfree** [comment] 2016-06-12 17:48
Closing this for 1.0.0-RTM

**Closed by joshfree** 2016-06-12 17:48 UTC
Labels: windows installer
