### ISSUE TITLE
AssemblyLoadContext failing to load Microsoft.AspNetCore.Components

### ISSUE THREAD

**Issue by bryanenroute** [dotnet/core-setup#8682] opened 2019-10-28 19:25 UTC
Here's a link to the code to reproduce the issue:  https://github.com/bryanenroute/assemblyloadcontext-issue

I can load a plugin (IModule) that resides in a basic .NET Core console application assembly, but fails to load a plugin/module that resides in an ASP.NET Core application assembly.

When the ASP.NET Core module goes through assembly resolution, I get LoaderExceptions:

"Could not load file or assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."

Can you assist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06023407-704f-0ace-e89a-eedd9f95a007
* Version Independent ID: f25a6e1a-cb10-867b-0522-a377bf9d016b
* Content: [Create a .NET Core application with plugins - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support)
* Content Source: [docs/core/tutorials/creating-app-with-plugin-support.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/creating-app-with-plugin-support.md)
* Product: **dotnet-core**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by mairaw** [comment] 2019-10-29 01:40
Issue transferred as requested @jkoritzinsky. I'm asking for help for the other one.

**Comment by vitek-karas** [comment] 2019-11-05 13:32
Currently this is by design. `AssemblyDependencyResolver` will not resolve additional frameworks. In this case the host app (`NetCoreConsoleApp`) has only a framework reference to `Microsoft.NETCore.App`. The `AspNetCoreApp` plugin has a framework reference to both `Microsoft.NETCore.App` and `Microsoft.AspNetCore.App`. Since `AssemblyDependencyResolver` doesn't even look at framework references it will do nothing about the `Microsoft.AspNetCore.App` reference.

There are couple of reasons for this behavior:
* Resolving frameworks in `AssemblyDependencyResolver` would make it very easy to load frameworks into secondary ALCs. More importantly it would make it very easy to load multiple copies of frameworks into the same process. This is typically not a good idea as it leads to all kinds of confusing issues and our frameworks are not tested for that case and will probably break in subtle ways.
* Some assemblies simply cannot be loaded multiple times - for example `System.Private.CoreLib.dll` - the runtime will actually actively reject any attempts to load a second copy. This would only lead to more confusion. Combined with this is the fact that some other CoreFX assemblies have very fragile ties to `System.Private.CoreLib.dll` and thus running a slightly different version of CoreLib and the rest of CoreFX for example will lead to all kinds of issues. This is just a long way of saying that even if we would allow loading frameworks more than once, it would not be possible to do so for the root `Microsoft.NETCore.App` framework.
* Normal classlib project doesn't produce `.runtimeconfig.json` which is the one file where we declare framework references. That said, this can be easily tweak via additional msbuild properties, but it would not work out of the box.
* Frameworks are highly unlikely to be unloadable - they were simply not designed for it. Making it easy (And thus probable) to load them into unloadable ALCs would just lead to more confusion.

The current design is that the host app must reference all the frameworks it itself and all its potential plugins might need. This also helps with versioning considerations (the app dictates the versions, making it predictable) and with resource consumption (frameworks are shared between the plugins reducing memory load). Right now there is not combination of frameworks which would not be allowed, so in the extreme case it's perfectly valid to reference all available frameworks from the host app (ASP.NET and WindowsDesktop, and transitively NETCore.App). Note that runtime is lazy, and referencing additional frameworks comes with a very small additional cost if they are not actually used.

**Comment by bryanenroute** [comment] 2019-11-13 16:31
This makes sense, thank you for the explanation.  I added a framework reference to NetCoreConsoleApp project and the assembly resolution issue goes away as anticipated:

`  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>`

Now AspNetCoreApp project module loads, but throws an exception in the project Startup:

`        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddSingleton<WeatherForecastService>();
        }`

The exception is thrown when serviecs.AddRazorPages is invoked:

System.IO.FileNotFoundException: 'Could not load file or assembly 'AspNetCoreApp, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'

It seems like the framework is having trouble determining the load directory... might this be related to [5053](https://github.com/dotnet/project-system/issues/5053)?

**Comment by vitek-karas** [comment] 2019-11-14 12:58
I was able to repro the second failure - unfortunately I don't have a solution. This seems like a core problem of ASP.NET - it won't work if the app is loaded into a secondary ALC. I've able to workaround the Start call, but the website still doesn't work.
I suggest you file the second issue in aspnet/aspnetcore - cc me there and I will add the details as to why it doesn't work and what can/should be done in ASP.NET to make it work.

I think it would also be interesting to understand what is the scenario you're trying to solve here.

**Comment by bryanenroute** [comment] 2019-11-14 16:05
I'm trying to make a .NET Core application/service that can load/unload plugins that primarily communicate with external systems/services.  One plugin might listen for TCP connections via TcpListener while another plugin might act as a client via TcpClient.  Another plugin might communicate with a remote REST service while another plugin might talk to a serial port.

That all works fine for .NET Core/Standard plugins, but I would also like to include more complex modules that host ASP.NET Core service endpoints like gRPC, SignalR, Web API, etc.

Effectively, I would like to run multiple .NET core projects, that would otherwise be stand-alone applications, as plugins operating under one process that can be loaded/unloaded.  In .NET Framework, I accomplished something similar via MAF (Systems.AddIns)... but since that API isn't part of .NET Core, that isn't an option anymore.  I really like the idea of AssemblyLoadContext, but miss the AppDomain and Process isolation options that were available in System.AddIns.

**Comment by vitek-karas** [comment] 2019-11-14 20:56
I haven't look at System.AddIns in detail, but it seems to provide two modes:
* AppDomain isolation - this is similar to AssemblyLoadContext isolation - it doesn't provide any real isolation guarantees outside of the assembly binding ones.
* Process isolation - there's no direct counterpart to this in .NET Core - mostly due to lack of remoting. We don't support remoting because it has reliability and security concerns around it which we didn't want to bring over to .NET Core. Our current recommended solution is to use some existing IPC mechanism - for example named pipes, shared memory and so on, coupled with some well established serializers (JSON, gRPC/protobuf, ...). But I do understand that the lack of "out of the box" solution makes this a relatively costly proposition.

I'm just curious, if you can share this info: what is the purpose of using "plugin like" system, when under the hood you would be using process level isolation? Why not simply start a child process directly? In your case there doesn't seem to be any complex communication between the "host process" and the "plugins" - but I could be wrong.

AppDomain isolation in .NET Framework is barely any better than AssemblyLoadContext in .NET Core - what benefit do you think it has which would help your project?

**Comment by bryanenroute** [comment] 2019-11-18 16:54
In the previous project, we never really used AppDomain isolation... it was either no isolation (best performance) or Process isolation.  We used Process isolation because the host process was usually 64-bit and some plugins required execution in a 32-bit process due to 3rd party library dependencies.

I really like AssemblyLoadContext in .NET Core so that plugins can run different versions of the same reference library (e.g. Newtonsoft.Json) without conflicts, plus unloadability is a nice bonus.  In the new project, I think I can be successful with a combination of MEF and ALC.

On the topic of IPC, it is a little frustrating that there isn't a decent built-in full-duplex IPC API in .NET Core.  The previous project used WCF with NetNamedPipeBinding with great success.  I know you can use System.IO.Pipes, but the API is too primitive (streams only).  In order to be useful, you'd need to layer on something to handle RPC... I know there are some 3rd party libraries that might be up to the task, but it's disappointing there isn't something included with .NET Core that would fill the void of WCF.

**Comment by vitek-karas** [comment] 2019-11-25 09:04
Thanks for the additional info. I'll close this issue in favor of https://github.com/aspnet/AspNetCore/issues/17098.

**Closed by vitek-karas** 2019-11-25 09:04 UTC
Labels: area-Host
