### ISSUE TITLE
HostFxr Fails to resolve hostpolicy from additionalprobingpath on CentOS

### ISSUE THREAD

**Issue by brthor** [dotnet/core-setup#121] opened 2016-06-08 20:48 UTC
See failures here:
http://dotnet-ci.cloudapp.net/job/dotnet_core-setup/job/release_1.0.0/job/debug_centos7.1_x64_prtest/74

Going to skip the test exposing this issue for the time being.

**Comment by gkhanna79** [comment] 2016-06-08 20:57
And it does not repro on other platforms?



Thanks,
Gaurav


-------- Original message --------

**Comment by brthor** [comment] 2016-06-08 21:04
No, CentOS only. @schellap has a good understanding, it seems to have something to do with CentOS rids not falling back to Rhel rids.

**Comment by gkhanna79** [comment] 2016-06-08 21:19
Matt?


Thanks,
Gaurav


-------- Original message --------

**Comment by schellap** [comment] 2016-06-08 21:53
Does this need to be fixed for RTM? Given the "emitEntryPoint" discovery? We do probe the app dir as fallback.

```
Could not find required library libhostpolicy.so in 2 probing paths:
12:06:19         /mnt/resource/j/workspace/dotnet_core-setup/release_1.0.0/debug_centos7.1_x64_prtest/.nuget/packages
12:06:19         /mnt/resource/j/workspace/dotnet_core-setup/release_1.0.0/debug_centos7.1_x64_prtest/.nuget/packages
12:06:19       A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/mnt/resource/j/workspace/dotnet_core-setup/release_1.0.0/debug_centos7.1_x64_prtest/artifacts/centos.7-x64/tests/artifacts/0/StandaloneTestApp/bin'.
```

**Comment by gkhanna79** [comment] 2016-06-08 22:07
> it seems to have something to do with CentOS rids not falling back to Rhel rids.

@ellismg What are your thoughts on this?

> Given the "emitEntryPoint" discovery?

@schellap What is this?

**Comment by ellismg** [comment] 2016-06-08 22:21
We have the fallback for CentOS because there is binary compatibility between RHEL and CentOS.  CentOS is a rebuild of RHEL removing Red Hat specific branding.  Note that we have some additional RIDs in the graph that fall back as well (ol, which is Oracle Linux).

**Comment by gkhanna79** [comment] 2016-06-08 22:29
@ellismg So is there any RID fallback bug for CentOS as alluded to above in the RID fallback graph? Or, is the bug in the host not being able to support it @brthor @schellap ?

**Comment by brthor** [comment] 2016-06-08 22:32
The `emitEntrypoint` being present in a test app is not guaranteed as xunit tests are actually libraries and the host is not required in the output for it to be runnable. If all else fails it could be a workaround for this scenario however (only on CentOS).

**Comment by brthor** [comment] 2016-06-09 16:20
This scenario is only present for the case of standalone test apps (a scenario which may not be important going forward), where hostpolicy.dll needs to be resolved from the `additionalprobingpath`. Given that we have an easy workaround `emitEntrypoint: true`, I don't think this needs to be a blocking bug.

**Comment by gkhanna79** [comment] 2016-06-09 16:23
Thanks @brthor but I am still not clear why is this an issue only on CentOS. Can you please elaborate on it? Is there a RID fallback bug in the fallback graph or the host? If the latter, why does this not show in other platforms?

**Comment by brthor** [comment] 2016-06-09 16:27
Hostfxr uses the current rid in an attempt to find hostpolicy from the graph of the application. In the case of CentOS there is no centos hostpolicy package, only rhel, since they are binary compatible. But since hostfxr doesn't know about rid fallback it fails to find hostpolicy. 

This would only exist on platforms where we don't ship an explicit host package, but rely on rid fallback.

**Comment by gkhanna79** [comment] 2016-06-09 16:31
> But since hostfxr doesn't know about rid fallback it fails to find hostpolicy.

Thanks for the explanation @brthor. How come we didnt run into this earlier and only now?

@schellap This sounds like a bug in hostfxr. Do you have a sense of the fix?

**Comment by brthor** [comment] 2016-06-09 16:35
> Thanks for the explanation @brthor. How come we didnt run into this earlier and only now?

Standalone test apps aren't a widely used scenario and it appears we have a gap there in cli testing (all of our test apps are portable). This scenario will become non-existent if standalone were a publish-time decision, and not build time.

**Comment by gkhanna79** [comment] 2016-06-09 16:46
Sounds good.

**Comment by gkhanna79** [comment] 2017-02-14 23:08
@eerhardt and I chatted about this and he confirmed that this issue is no longer applicable to the new CLI. Also, we have not seen this issue reported in the wild.

Given the above, we will close the issue and reopen it if it surfaces on 2.0 in future.

**Closed by gkhanna79** 2017-02-14 23:08 UTC
Labels: bug
