### ISSUE TITLE
dotnet-runtime-deps on Bionic should depend on libcurl4

### ISSUE THREAD

**Issue by salaros** [dotnet/core-setup#3792] opened 2018-03-07 16:06 UTC
## Steps to reproduce
- install Ubuntu 18.04 Bionic
- add `deb https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod/ artful main` to APT package lists, because there are no packages for [bionic](https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod/) here
- try to install dotnet runtime and SDK

## Expected  behavior
dotnet-runtime-deps-xxx pacakges on bionic must depend on libcurl4 and not libcurl3

## Actual behavior
` dotnet-runtime-deps-2.1.0-preview1-26216-03 : Depends: libcurl3 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

## Environment data
Ubuntu 18.04 Bionic amd64

**Comment by eerhardt** [comment] 2018-03-09 03:34
This looks like a dupe of #3791, which was logged just before this.

**Closed by eerhardt** 2018-03-09 03:34 UTC
Labels: area-Setup
