### ISSUE TITLE
Results of "dotnet --info" dependent upon the case of the path to dotnet

### ISSUE THREAD

**Issue by MarkStega** [dotnet/core-setup#4529] opened 2018-08-31 21:47 UTC
## Steps to reproduce
Define "C:\Program Files\Dotnet" in the system path (where the actual install directory is "C:\Progeam Files\dotnet"

Execute "dotnet --info" at the command line

## Expected  behavior
I expect to see one each of the installed sdks and runtimes regardless of how I define the path to the dotnet installs

## Actual behavior
The sdks and runtimes are show twice with the directory for the first instance showing "Dotnet", the second "dotnet"

## Environment data
Windows 10 Version 1803
.Net Core SDK 2.1.401

**Comment by steveharter** [comment] 2018-09-05 22:11
Duplicate of https://github.com/dotnet/core-setup/pull/4441 which has been fixed in master (3.0)

Has not been ported to 2.1.x

**Comment by steveharter** [comment] 2018-09-05 22:34
@jeffschwMSFT I'll close this issue as duplicate.

**Closed by steveharter** 2018-09-05 22:34 UTC
Labels: area-Host
