### ISSUE TITLE
InvalidOperationException: Cannot find compilation library location for package

### ISSUE THREAD

**Issue by ngohungphuc** [dotnet/core-setup#3614] opened 2018-01-22 16:33 UTC
I have tried @pakrym [solution](https://github.com/dotnet/core-setup/issues/2981) in my project

[ReferenceFeatureProvider.cs](https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/blob/master/src/AwesomeCMSCore/AwesomeCMSCore.Infrastructure/Config/ReferencesMetadataReferenceFeatureProvider.cs)

and in [this](https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/blob/master/src/AwesomeCMSCore/AwesomeCMSCore/Extension/ServiceCollectionExtensions.cs#L78) 

I will get this error InvalidOperationException: Cannot find compilation library location for package 'AwesomeCMSCore.Modules.API'.

![image](https://user-images.githubusercontent.com/13591213/35231483-83b49ec4-ffcb-11e7-96c9-7cddb32bc34a.png)

Is there anyway to work around this

**Comment by ngohungphuc** [comment] 2018-01-23 04:42
In my web api project I have to add

```
<PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>

```

**Comment by steveharter** [comment] 2018-01-23 14:32
@ngohungphuc this should be fixed in the 2.0.3 release of the runtime (November 2017); this doesn't require setting PreserveCompilationContext=false

What version of the runtime do you have?

**Comment by ngohungphuc** [comment] 2018-01-23 14:44
@steveharter my dotnet version is 
2.1.4

**Comment by steveharter** [comment] 2018-01-23 18:48
Are you trying to add a new reference resolver or just use the existing one?

**Comment by ngohungphuc** [comment] 2018-01-24 00:44
which reference resolver you want to mention @steveharter

**Comment by steveharter** [comment] 2018-01-24 17:28
I'm not sure if you are trying to add a new file-reference resolver (note we also have other "resolvers" including package resolvers and project resolvers) or if you are simply trying to use the existing file reference resolver and are having issues with that.

**Comment by eerhardt** [comment] 2018-01-26 17:27
@ngohungphuc - @pakrym's solution (I think you mean @pranavkm) is no longer necessary with ASP.NET Core `2.0.3` or greater.  Can you successfully run your app without that code?

**Comment by ngohungphuc** [comment] 2018-01-27 13:05
@eerhardt I cant

**Comment by eerhardt** [comment] 2018-03-16 14:31
This should be investigated for 2.1.

**Comment by pranavkm** [comment] 2018-03-16 16:06
` <PreserveCompilationContext>false</PreserveCompilationContext>` That might be the cause of the issue. Try setting it to `true`

**Comment by eerhardt** [comment] 2018-03-27 19:12
@ngohungphuc - I pulled the master branch of https://github.com/Awesome-CMS-Core/Awesome-CMS-Core/, and the app seemed to run I think.  I got a 404 not found when hitting the home page.  But I didn't get the error you describe.

Can you give me a solid set of repro steps to investigate this issue?  Assume that I know nothing about your project, and how to set it up to run.  It would be best if you could make a branch or something that all I needed to do was pull the branch, hit F5, and I see the exception.

**Comment by eerhardt** [comment] 2018-03-27 22:22
Closing for now, until we get a solid set of repro steps to repro the issue.

**Closed by eerhardt** 2018-03-27 22:22 UTC
Labels: area-DependencyModel
