### ISSUE TITLE
Enable Windows subsystem EXEs to avoid console creation

### ISSUE THREAD

**Issue by richlander** [dotnet/core-setup#4034] opened 2018-04-17 18:36 UTC
We need a first class experience for selecting among a set of hosts (or host characteristics) to use for a given application.

See: https://github.com/dotnet/core/issues/1452

**Comment by dasMulli** [comment] 2018-04-18 15:04
Likely a duplicate of https://github.com/dotnet/core-setup/issues/196?

**Comment by steveharter** [comment] 2018-04-20 20:11
Closing as dup.

@richlander can you add to https://github.com/dotnet/core/issues/1452 if you have additional thoughts. Thanks

**Closed by steveharter** 2018-04-20 20:11 UTC
