### ISSUE TITLE
CurlHandler fails to initialize if have only shared runtime rather than full SDK

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2279] opened 2017-05-04 05:32 UTC
_From @JohnRusk on May 4, 2017 5:27_

## Steps to reproduce

I run my app, which uses WindowsAzure.Storage (version 8.0.0) and targets .NET Core 1.1.1.  I get this exception:

```
System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> 
System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> 
System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> 
System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.HttpInitializer.EnsureCurlIsInitialized()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at Microsoft.WindowsAzure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.<>c.<.cctor>b__8_0()
```

## Expected  behavior

It should work, regardless of whether I have the full SDK or just the shared runtime.

## Actual behavior

I get the above error if I just have the shared runtime.  It works if I have the full SDK.

## Environment data
Fails if shared runtime only.  Works if SDK is present.
Testing on Ubuntu 16.04

## Note: 

For reference, a variant of this issue appears here: http://stackoverflow.com/questions/42472536/can-a-library-that-depends-on-system-net-http-winhttphandler-be-deployed-to-linu 

_Copied from original issue: dotnet/cli#6513_

**Comment by Petermarcu** [comment] 2017-05-04 05:50
This should probably go to corefx but @Priya91 can decide :) @karelz

**Comment by karelz** [comment] 2017-05-04 07:44
From this exception text `Unable to load DLL 'System.Net.Http.Native'` it looks like the right binaries are not present in the app.
@JohnRusk can you please provide a repro? (ideally minimal one)

**Comment by JohnRusk** [comment] 2017-05-04 23:45
Hi @karelz.  I'll put together a minimal repro next week.

**Comment by Priya91** [comment] 2017-05-05 00:23
@JohnRusk Can you check if system.net.http.native.so is found in dotnet/shared/Microsoft.NETCore.App/<version>? If it's present please provide a repro, if not the native shims have to be found, you may want to check your install.

**Comment by JohnRusk** [comment] 2017-05-17 04:35
@Priya91 that so file is indeed present, although the capitalization of its name is different from what you have in your comment.  First letter of each word is capitialized.

**Comment by JohnRusk** [comment] 2017-05-17 04:55
@karelz cc @Priya91 , here is the repro app. Apologies for the delay in getting it to you.

[CurlHandlerLoadBugRepro.zip](https://github.com/dotnet/core-setup/files/1006599/CurlHandlerLoadBugRepro.zip)

To reproduce my problem, I made a fresh Ubuntu 16.10 VM, then installed the framework only by running the following:

`wget https://dot.net/v1/dotnet-install.sh

chmod 700 dotnet-install.sh

sudo apt-get install libunwind8 

source ./dotnet-install.sh --channel 'release/1.1.0' --version '1.1.1'  --shared-runtime`

Then, after building and publishing the repro app, I ran it on the Ubuntu machine. The repro app attempts to connect to Azure Storage, but you can use the _exact_ dummy params below, because it gets the DLL load error before even reaching Storage.  I'm just using the Storage API as a way to load CurlHandler, because that's where my real app gets the error.

`dotnet CurlHandlerLoadBugRepro.dll dotnet CurlHandlerLoadBugRepro.dll curlhandlerloadbug ILMbnhe83hedlnthehe8nehylehnheuemtpfxhsOweBUK0oBoiiJXVbZAVvUml3CpaU/m3RUjNy9OcGK9kogfA== dummy`

When I do that, I get a TypeInitializationException, as discussed.  That demonstrates the first part of the issue: that a runtime-only install doesn't work.

(To demonstrate that installing the full SDK fixes it:

Get the full SDK by doing `sudo apt-get install dotnet-dev-1.0.3` (note version) following the instructions here https://www.microsoft.com/net/core#linuxubuntu . Then remove $HOME/.dotnet from your path (since that's where the runtime-only install was), and run the app again. This time, it gives an error saying "Server failed to authenticate the request". That shows that the CurlHandler did initialize successfully. I.e. the app did make an REST call but, unsurprisingly given the bogus authentication key in my suggested command line, that call was not authenticated. )

**Comment by Priya91** [comment] 2017-05-18 01:11
@JohnRusk I followed the repro steps that you had provided, and installed just the shared-runtime and compiled the app on windows, and did a ```dotnet publish -f netcoreapp1.1```, copied the published folder and did ```dotnet CurlHandlerLoadBugRepro.dll curlhandlerloadbug ILMbnhe83hedlnthehe8nehylehnheuemtpfxhsOweBUK0oBoiiJXVbZAVvUml3CpaU/m3RUjNy9OcGK9kogfA== dummy```, I get the exception,

```
```

**Comment by Priya91** [comment] 2017-05-18 01:13
@ramarag Says there's an env variable that you can set, that'll print trace messages from the dotnet host. From there we can know if loading the so files failed. @ramarag Can you point to the docs on that?

**Comment by ramarag** [comment] 2017-05-18 01:31
@JohnRusk set COREHOST_TRACE=1 before you run the app. dotnet.exe will print the locations it probes to find all the required assemblies. Please do this for both success and failure cases and share it out

**Comment by JohnRusk** [comment] 2017-05-18 23:43
@ramarag the logs for both success and failure are attached.  If you set your diff tool to ignore the difference in the paths to the dotnet directory, there are just about 4 remaining differences.

[loadLogs.zip](https://github.com/dotnet/core-setup/files/1012686/loadLogs.zip)

@Priya91 I have repeated my tests, and it still happens for me.  I've notice two things that might be relevant:
- You used a different version of Ubuntu from me.  I used 16.10,  and you used 14.04 LTS
- The repro only works with a fresh install of Linux, that has _not_ previously had the SDK installed. I.e. if I install the SDK, then the problem is resolved and the .so file can be loaded, as discussed above. If I then remove the SDK, using the script here https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-debian-packages.sh the _problem is still resolved_.  I.e. removing the SDK did not put the machine back into the state where the issue can be reproduced.  Only by making a fresh Azure VM was I able to reproduce the problem.

Would you like me to upload a zipped copy of my publish directory, so you can see if there are any differences between my publish dir and yours? It's 2 MB in size.

**Comment by ramarag** [comment] 2017-05-19 00:43
there is nothing wrong with the host and way it loads the assembly

@Priya91 i believe a native dependency is missing when the shared FX is installed which is being corrected when the SDK is installed, do you know what the dependency might be ?

@rakeshsinghranchi ideas ?

**Comment by rakeshsinghranchi** [comment] 2017-05-24 01:57
Below are the set of dependencies exhibited by shared fx package :
 libc6 (>= 2.14), libcurl3 (>= 7.16.2), libgcc1 (>= 1:4.1.1), libgssapi-krb5-2 (>= 1.10+dfsg~), liblttng-ust0, libstdc++6 (>= 4.8), libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4), libssl1.0.0

**Comment by julielerman** [comment] 2017-08-04 11:37
FWIW, I'm getting dependency errors on one of the packages mentioned by @rakeshsinghranchi when trying to install the runtime for latest 2.0.0 on Debian 9. Is that due to the 24 hour delay? Downloaded deb files from Daily Builds page on under the 2.0.X column.

```
root@debian:/home/julie/Downloads# dpkg -i dotnet-runtime-latest-debian.8-x64.deb 
Selecting previously unselected package dotnet-runtime-2.0.0.
(Reading database ... 143458 files and directories currently installed.)
Preparing to unpack dotnet-runtime-latest-debian.8-x64.deb ...
Unpacking dotnet-runtime-2.0.0 (2.0.0-1) ...
dpkg: dependency problems prevent configuration of dotnet-runtime-2.0.0:
 dotnet-runtime-2.0.0 depends on liblttng-ust0; however:
  Package liblttng-ust0 is not installed.
 dotnet-runtime-2.0.0 depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.
 dotnet-runtime-2.0.0 depends on libicu52; however:
  Package libicu52 is not installed.

dpkg: error processing package dotnet-runtime-2.0.0 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dotnet-runtime-2.0.0
```

**Comment by JohnRusk** [comment] 2017-10-04 06:06
I believe this issue may have been fixed by https://github.com/dotnet/cli/pull/7377 

I believe that because it looks that like that PR is solving the same problem.  I do not have time to verify that it actually does resolve the exact issue in this thread here.

**Comment by rakeshsinghranchi** [comment] 2017-11-01 00:50
@julielerman , Install instruction for Debian.9 is here : https://www.microsoft.com/net/learn/get-started/linuxdebian

**Comment by steveharter** [comment] 2018-01-12 20:07
Closing as assumed fixed

**Closed by steveharter** 2018-01-12 20:07 UTC
Labels: bug, needs more info
