### ISSUE TITLE
No `.a` file in nethost packages

### ISSUE THREAD

**Issue by NextTurn** [dotnet/core-setup#7114] opened 2019-07-08 15:59 UTC
## Expected  behavior

In https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/native-hosting.md#new-host-binary-for-finding-hostfxr

> The library would be a dynamically loaded library (`.dll`, `.so`, `.dylib`). For ease of use there would be a header file for C/C++ apps as well as `.lib`/`.a` for easy linking.

## Actual behavior

There is no `.a` file in linux/osx packages.

Do you have any plan to provide static libraries? `.a` files are not for DLL implicit linking.

## Environment data

Microsoft.NETCore.App.Host.(linux-x64/osx-x64)

-or-

runtime.(linux-x64/osx-x64).Microsoft.NETCore.DotNetAppHost

**Comment by omajid** [comment] 2019-07-08 16:13
Duplicate https://github.com/dotnet/core-setup/issues/5105

**Comment by vitek-karas** [comment] 2019-07-08 20:54
@omajid  I don't think this is duplicate of the mentioned issue. This is solely about the `nethost.dll` nothing else.

@NextTurn for now we don't have plans to provide statically linked `lib`/`a` files, only the dynamic libraries. For the dynamic libraries we include the `.lib` file on Windows as it makes it easy to link against. There's no need for `.a` file on Linux for that purpose. This is probably my bad when I was writing the document in question I didn't know that Linux/Mac doesn't need the `.a` file to link against a dynamic library (`.so`/`.dynlib`).

So I assume this is really a request to provide a static library version of the nethost, right?

If that is the case, can you please describe why the dynamic library is not enough?
I'm simply trying to understand your request better.

I think it should be possible to add the static libs as well, but I don't know the linkers on cross-plat that well and it would probably complicate our build to some degree as well (there's also other potential problems like the fact that the static libs can't be signed AFAIK).

**Comment by NextTurn** [comment] 2019-07-09 01:30
Not like that. I was just asking if there is a mistake in the design docs. :)

But I did wonder if it's possible to build staic libraries.

**Closed** 2019-07-11 04:50 UTC
Labels: area-Host

**Comment by handicraftsman** [comment] 2019-10-23 08:14
It is not enough when embedding into Rust/Cargo-based applications or libraries - you need to link to additional shared library, and you cannot access artifact directory from build.rs.

A workaround (for distribution purposes) might be downloading libnethost.so alongside with .NET Core SDK (which should not be done on client-side machines) instead of copying it, but it will require an additional linking mechanism like dlopen, and SDK should not be distributed to clients. Currently i want to make my `coreclr-sys` library only download .NET Core Runtime when it cannot be found and an environment variable is set, but thanks to Cargo limitations i cannot just distribute `libnethost.so` alongside with `coreclr-sys` outputs.

**Comment by NextTurn** [comment] 2019-10-23 08:29
> A workaround (for distribution purposes) might be downloading libnethost.so alongside with .NET Core SDK

@handicraftsman An alternative workaround is to download *libnethost.so* from [Microsoft.NETCore.DotNetAppHost](https://www.nuget.org/packages/Microsoft.NETCore.DotNetAppHost/) Nuget package.

**Comment by NextTurn** [comment] 2019-10-23 10:04
@vitek-karas I just successfully built *libnethost.a* by simply changing the CMake target from `SHARED` to `STATIC`, and it worked like a charm. Are there other problems to consider?

**Comment by dagood** [comment] 2019-10-23 15:33
Well, we would need to build both--I don't know if *adding* is any harder than *changing* but something to consider. Another bit of work is adding the new file to the nupkgs/zips.

> (there's also other potential problems like the fact that the static libs can't be signed AFAIK)

We don't sign Linux bits, right? Only the containers e.g. nupkg.

We do sign things on macOS, but I'm not exactly sure what would be required for a new `.a` file. (Which containers it ends up in seems like it would matter?)

**Comment by NextTurn** [comment] 2019-10-23 15:50
> I don't know if *adding* is any harder than *changing* but something to consider.

The static library target will only be added to nethost.

> Another bit of work is adding the new file to the nupkgs/zips.

It occurs to me that the new static library can't be directly added into the AppHost package on Windows, since there is already a *.lib* file for DLL implicit linking.

**Comment by handicraftsman** [comment] 2019-10-23 18:15
CMake can effectively reuse same .o files for both static and shared library versions if setups are same iirc.

**Comment by NextTurn** [comment] 2019-10-24 11:14
Opened #8659
