### ISSUE TITLE
Improve the error when application file does not exist and SDK is not installed

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/core-setup#3490] opened 2017-12-04 19:30 UTC
## Steps to reproduce
Run `dotnet <bad file path>` on a machine without the SDK.

```
docker run --rm -it microsoft/dotnet:2.0-runtime
dotnet dummy.dll
```

## Expected  behavior
Error message should say something like "dummy.dll does not exist" as it does when the SDK is installed.

When the SDK is installed, the error is better:
```
dotnet test.dll
The application to execute does not exist: 'C:\tmp\task\test.dll'
```

## Actual behavior

The error message gives no indication that the missing file is the issue.

```
root@e5b6d671926a:/# dotnet dummy.dll
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

## Environment data
```
 dotnet --info

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by steveharter** [comment] 2018-01-31 19:46
I am unable to repro with 2.1. If I add an extra argument in front of `dummy.dll` I will get the "Did you mean to run dotnet SDK commands" message.

Why is docker mentioned? Does docker add additional arguments that would force the "Did you mean to run dotnet SDK commands..." message?

Without the SDK:
```
dotnet dummy.dll
The application to execute does not exist: 'C:\tmp\dummy.dll'
```

If you add an extra argument without the SDK you will get:
```
dotnet xyz dummy.dll
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409```

**Comment by natemcmaster** [comment] 2018-02-01 18:50
I mentioned docker because I've had 5 different users on https://github.com/aspnet/aspnet-docker/issues/322 report being confused by the error message in .NET Core 2.0.x. If this is fixed by changes in the host in 2.1, that's great.

**Comment by steveharter** [comment] 2018-02-01 19:03
OK closing. Please re-open if there is a repro that I'm not aware of (such as docker providing an argument that requires the SDK).

The logic is fairly straightforward: if an argument is provided it checks if it is special (-h, --info, exec) and can be handled without forwarding the SDK. If it must forward to the SDK and if the SDK is not found, then the "Did you mean to run dotnet SDK commands" message is shown. If no argument is given, it assumes "exec" and handles it without the SDK.

**Comment by steveharter** [comment] 2018-02-01 20:06
Actually this issue appears to be a dupe of https://github.com/dotnet/dotnet-docker/issues/361 which has since beehn fixed.

**Comment by MichaelSimons** [comment] 2019-10-14 13:56
@steveharter - This issue was reported again in https://github.com/dotnet/core/issues/3604.  I have seen this basic issue logged a few times now.  I think the message is confusing when the user is not intending to run an SDK command - e.g. the dll they are trying to execute is missing or mis-spelled.  Would it make sense to adjust the message to account for this scenario?

**Comment by dagood** [comment] 2019-10-14 15:01
@vitek-karas @elinor-fung thoughts?

Basically, this is misleading when trying to run an FDD app but either misplacing the DLL or getting the name or path wrong:

```
root@6f87t213c05f:/# dotnet Some.NonExistent.dll
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

https://github.com/dotnet/core/issues/3604 is a repro on 3.0. I'm reopening because the reason this was closed was it was thought to be fixed in 2.1.

For reference, the SDK's output:

```
PS C:\> dotnet Some.NonExistent.dll
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-Some.NonExistent.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by steveharter** [comment] 2019-10-15 17:24
FWIW (I haven't worked on this since 2.x) typing `dotnet exec dummy.dll` returns `The application to execute does not exist: 'dummy.dll'`. So the code is assuming that `dummy.dll` may be a SDK command so it tried to forward to SDK, but since the SDK doesn't exist it displays "It was not possible to find any installed dotnet SDKs".

**Comment by dagood** [comment] 2019-10-15 17:41
That makes sense--so it sounds like the behavior is by design, but maybe this design should be changed because it's causing confusion (in particular when authoring a Dockerfile where it's not always easy to know what the DLL *is* called).

We do need to take care with the "typing `dotnet build` without the SDK installed gives me an actionable error" scenario. Wouldn't be good for that to stop mentioning the SDK and only say it couldn't find a file called `build`.

**Comment by MichaelSimons** [comment] 2019-10-15 18:22
I am in agreement with @dagood.  This is tripping up a number of customers that are trying to execute an application rather than an SDK command.  I'd like to see a change in the wording to account for this scenario.  Does something along the following lines seem reasonable?

```
PS C:\> dotnet Some.NonExistent.dll
Could not execute because the application was not found or the .NET Core SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET Core program, but dotnet-Some.NonExistent.dll does not exist or is misspelled.
  * You intended to execute a .NET Core SDK command but it was not possible to find any installed .NET Core SDKs.  Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
```

**Comment by dagood** [comment] 2019-10-15 18:29
```
  * You intended to execute a .NET Core program, but dotnet-Some.NonExistent.dll does not exist.
```

`dotnet-Some.NonExistent.dll`'s `dotnet-` prefix is interesting. IIRC that's the prefix to find the DLL for a dotnet SDK command, but I forget exactly where it's trying to find the DLL. I'm not sure if that line is actually wrong or just a different scenario.

(To be clear, for this scenario we would want it to say `but Some.NonExistent.dll does not exist`.)

**Comment by MichaelSimons** [comment] 2019-10-15 18:31
@dagood - that was a copy and paste error on my part and was not intentional.

**Comment by dagood** [comment] 2019-10-15 18:43
Alright, separate issue then--filed https://github.com/dotnet/cli/issues/12895 for that.

**Comment by shaunluttin** [comment] 2019-11-16 02:16
We ran into this error today when the application file did not exist (due to a misspelling). It took about 1.5 hours to figure out the mistake. A better error message would have helped. 

Here is an example of a problematic Dockerfile: 
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetapp/*.csproj ./aspnetapp/
RUN dotnet restore

# copy everything else and build app
COPY aspnetapp/. ./aspnetapp/
WORKDIR /app/aspnetapp
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime
WORKDIR /app
COPY --from=build /app/aspnetapp/out ./
ENTRYPOINT ["dotnet", "aspnetOOPSapp.dll"]
```

**Closed** 2019-11-21 22:21 UTC
Labels: area-Host

**Comment by elinor-fung** [comment] 2019-11-21 22:24
Change to update error message is in the consolidated repo: dotnet/runtime#163
