### ISSUE TITLE
dotnet.exe fails to run after renaming

### ISSUE THREAD

**Issue by bartgrefte** [dotnet/core-setup#5435] opened 2019-03-11 17:26 UTC
I've got two programs that use dotnet.exe, the traffic of one of them should be redirected through a proxy.

So I thought I'd copy dotnet.exe to dotnet2.exe (in the same folder) like I did with java.exe (also required) and set Proxifier to redirect all the traffic from java2.exe and dotnet2.exe through the proxy.

No problem with java2.exe, however, dotnet2.exe won't run (not even with --help):
C:\Windows\System32>dotnet2 --help
A fatal error was encountered. Cannot execute dotnet when renamed to  dotnet2.

I vaguely remember that I had a setup like that working once, but dotnet won't run (anymore) when using a different filename.

Is dotnet really that sensitive when it comes to the filename and is there a way to get around that?

**Comment by jeffschwMSFT** [comment] 2019-03-12 23:34
There is an explicit check for this in the host: https://github.com/dotnet/core-setup/blob/ede9e16b4b2396475bdc38700ed6205b3df4c0bf/src/corehost/corehost.cpp#L327

@vitek-karas do you know why?

@bartgrefte in .NET Core 2.2+, I would recommend using an apphost and setting the proxy to one or other of the apphosts (which would be your app).  Is that possible?

**Comment by bartgrefte** [comment] 2019-03-13 08:41
I didn't create the programs and I would have to Google what you exactly mean with apphost, no experience with making apps that use dotnet....

All I know is that there is no support at all for using proxies, that's why I'm using Proxifier, which only checks for processes with a particular name, not path. So copying the entire dotnet folder and renaming the folder instead of the process won't help.

The strange thing is, I remember I had this working a while ago, no clue why dotnet is suddenly complaining about the name.

Isn't there an option I can add that ignores that explicit check?

**Comment by vitek-karas** [comment] 2019-03-13 12:19
I don't know why the check is there. My guess is to prevent trying to use `dotnet.exe` as an `apphost` (by copying the file into an app and renaming it). I've reached out to the original author of this change as the commit has next to no details on this.

As for a workaround, unfortunately there's nothing really simple. The simplest I could come up with is:
Assumptions:
* You're using globally installed runtime - that is installed in `C:\Program Files\dotnet`.
* You have the ability to change which `dotnet.exe` is used to run the app in question
* The Proxifier can be told to apply specific behavior to a fully qualified executable (by full path), not just a simple `name.exe`.

Workaround:
* Create a custom folder, can be anywhere really, so let's say `C:\Temp\ProxiedDotNet`
* Copy the `dotnet.exe` into that folder
* Create a subdirectory `.\host\fxr` in the folder
* Copy the latest version from the `C:\Program Files\dotnet\host\fxr\<version>` into the created `fxr` folder. No need for the older versions, just the latest is enough. The version folder should have the `hostfxr.dll` in it.
* Run the app via `C:\Temp\ProxiedDotNet\dotnet.exe app.dll`

Now you should be able to register the `C:\Temp\ProxiedDotNet\dotnet.exe` with the proxy for a special behavior. When executed the app will take all the shared frameworks from the global `C:\Program Files\dotnet` location, just the `dotnet.exe` and `hostfxr.dll` will be "Special".

**Comment by jeffschwMSFT** [comment] 2019-03-13 15:14
Adding @davidfowl for thoughts on how to proxy .NET Core use on a simple box.

**Comment by vitek-karas** [comment] 2019-03-13 20:22
I found out why we block this.

The `dotnet.exe` is signed with Microsoft certificate. It might create confusion if we let people rename it and ship with their app - it might make the app look like it's from Microsoft.

The `apphost` which ships with the SDK and is copied into the app by the build and renamed is not signed. App developer can sign that with their own certificate if they want.

It's not ideal solution, but given the limitations, makes sense.
I'd say we won't change this if the scenario described in this issue is the only one blocked by this.

**Comment by bartgrefte** [comment] 2019-03-14 08:47
"The Proxifier can be told to apply specific behavior to a fully qualified executable (by full path), not just a simple name.exe."
Already had a look at that, Proxifier only checks for process name, not full path.

"The dotnet.exe is signed with Microsoft certificate. It might create confusion if we let people rename it and ship with their app - it might make the app look like it's from Microsoft."
Makes sense.

But there is no option or something else I can use to bypass the filename-check? Or compile dotnet.exe myself without that check build in?

The only alternative I can think of now is to set up a virtual machine and run the 2nd program and Proxifier in there. But running two full Windows installs at the same time is not quite an ideal solution. I don't suppose you know if there are any stripped down WinPE solutions that contain both dotnet and java? At least that way I don't need to run a 2nd fully featured Windows install consuming lot's of system resources.

**Comment by vitek-karas** [comment] 2019-03-14 13:16
I see two possibilities (excluding additional virtual machines, that would definitely work, but is not very friendly):

#### Build your own `dotnet.exe`
You can fork the dotnet/core-setup repo and build it yourself. You can remove the check and rename the output as you wish. Not ideal, but should work.

#### "Inject" `apphost` into the app
I assume this special handling is needed for only very few apps, and so manual steps are "OKish". Create a directory with the same name as the main .dll of the affected app (for example `MyApp.dll`). From command line go to that directory and run `dotnet new console` and then `dotnet publish -r win-x64 --self-contained false` (assuming .NET Core 2.2 or higher).

Now go to the publish output and you should find `MyApp.exe` in it. Take that file and copy it into the original application. Start the app by running the `MyApp.exe` instead of `dotnet MyApp.dll`. It should work just like before. And now you have an executable with a specific name (you can even rename it if you want).

Please note that the executable has the name of the `MyApp.dll` written in itself, so it will only work on that one application. If you need this for other apps you would have to create new executable for each.

**Comment by bartgrefte** [comment] 2019-03-15 18:07
As for building my own dotnet.exe, please don't tell me it is necessary to install over 20GB worth of Visual Studio 2017 files just to recompile dotnet-hosting-2.1.1-win.exe? ..... Well, I hope the uninstaller will do a decent cleanup afterwards.

And the other option: it seems I need to get the SDK first before those commands are recognized, but since the app's install guide lists 2.1.1 specifically, I'm not sure if this option will work since you mentioned 2.2 or higher. So I'm guessing either that command is different with older versions, or that command doesn't exist at all before 2.2. Not sure which.

**Comment by vitek-karas** [comment] 2019-03-15 18:21
Building core-setup: The answer is pretty much yes. I don't think it's 20GB (you just need the desktop applications payload - C# and C++), but it's pretty big.

The other option: You don't need the matching SDK - you just need to produce the special `appname.exe`. It's probably not officially supported to use 2.2 built `.exe` with a 2.1 app, but it should work.

**Comment by bartgrefte** [comment] 2019-03-15 18:45
If I select what https://github.com/dotnet/core-setup/blob/master/Documentation/building/windows-instructions.md indicates, then it shows well over 20GB. ... After looking at the W10 build numbers., that doc seems a bit out of date.

Well, I'll try the dotnet.exe rebuild first, since the other option will have to be redone with every app update and those happen often.

It's a good thing I've got a glass fiber internet connection, wouldn't have done this with adsl, getting the installer files for Visual Studio won't take very long :)

**Comment by vitek-karas** [comment] 2019-03-15 19:40
Re the `appname.exe` option (we call this the `apphost`). You don't need to rebuild it for every new version of the app. The .exe is basically the same code as `dotnet.exe` (almost), with one exception, it has the name of the application .dll written in it - that's the only difference. So as long as the main .dll of the app doesn't change name, the .exe should work.

**Comment by bartgrefte** [comment] 2019-03-16 19:07
Ah, okay, didn't realize that.

Well... I've tried to build my own dotnet.exe, unsuccessfully. The build script first ran into "error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found", it looks like the Visual Studio installer didn't install everything required, it installed 4.6.1 instead of 4.6.

After solving that the build script went further, however, the only dotnet.exe I could find after the process seemed to have finished (source\repos\core-setup\Tools\dotnetcli\dotnet.exe) it still had that rename problem, even though I deleted the if-statement that generates the renamed error.

In the msbuild.log I found errors:
 -- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
No CMAKE_C_COMPILER could be found.
CMake Error in CMakeLists.txt:
No CMAKE_CXX_COMPILER could be found.

When I installed CMake for Windows, I made sure to check the box that added it to the path variable, so I'm unsure as of why the compiler cannot be found.

**Comment by bartgrefte** [comment] 2019-03-16 19:16
The msbuild.log did show "C:\Program Files\CMake\bin\cmake.exe" just before the above errors, so it can find it?
(For some reason I can't edit my previous posts, nothing happens when I click on the edit-button.)

**Comment by vitek-karas** [comment] 2019-03-16 20:58
I think CMAKE can't find the C/C++ compiler. I don't know why... 
You can try to run the build from the "Developer Command Prompt for VS" - after the VS install this should exist as a shortcut in the start menu. Running it opens command line which should be able to run "cl.exe" (the C/C++ compiler).

**Comment by bartgrefte** [comment] 2019-03-17 08:59
Not sure what was missing (gonna check that later), but it is now continuing :). I tried to create a new C++ project, which (fortunately) resulted in a message that something was missing and was automatically installed, now the building process continues even further than before.

I'm currently waiting for the build to finish.

**Comment by bartgrefte** [comment] 2019-03-17 10:08
During the "Waiting for process * to exit..." part of the building process I got a whole bunch of ".net core not working anymore" errors from Windows which I had to click away before the script continued.

After it was over I got another error: 
"C:\Users\Bart\source\repos\core-setup\build.proj" (default target) (1) ->
"C:\Users\Bart\source\repos\core-setup\src\test\dir.proj" (Build target) (22) ->
(RunTests target) -> 
C:\Users\Bart\source\repos\core-setup\src\test\dir.proj(120,5): error : One or more test runs failed.

That plus 76 warnings.

In the end I found 9 dotnet.exe's spread across the created folders. The one in core-setup\bin\obj\win-x64.Debug\combined-framework-host seems to work after renaming :) , when trying some of the others I got a missing directory error (without renaming).

About the thing that was missing, I made screenshots of the installed components for comparison, I thought I had everything checked that was in windows-instructions.md. I found some other things to check after Googling (which were already installed) and then I created a new C++ project which showed something was still missing: C++ Universal Windows Platform Tools.
After that it seems to have worked.

**Comment by vitek-karas** [comment] 2019-03-18 14:25
The ".NET Core not working anymore" errors I've never seen. If you run into it again, can you please maybe grab a screenshot or something...?

The test failure could be caused by a small issue in one of the Windows specific tests - it should be fixed now (see #5492 for more details).

The warnings are unfortunately expected - nobody went to clean it up yet.

The correct build output is `.\bin\win-x64.Debug\corehost\dotnet.exe`. But trying to run it will fail is `dotnet.exe` expects to be installed in a certain directory structure. The path you mention contains a copy of this binary along with other files to form the required structure for testing pruposes.

As for the pretty bad install experience to get the build working - I'm not an expert in that area. For me it felt less painful last time I did that, but that doesn't mean anything... If you know about specific issues with the `windows-instructions.md` please let us know.

**Comment by bartgrefte** [comment] 2019-03-18 18:02
I added a screenshot of one of the dozen or so crashes (in Dutch) that I had to click away.

![dotnetcrash](https://user-images.githubusercontent.com/13036914/54551225-f2038e80-49ad-11e9-8ce0-e1b3b245603c.jpg)


Hmm, you might want to add the warnings to windows-instructions.md ;) , that it is normal they appear.

As for specific issues, can you add a detailed (and updated) list of Visual Studio components that actually need to be installed for the building process to work? 

Visual C++ for example isn't quite specific. I ended up with C++ Universal Windows Platform Tools (which got installed after creating a C++ project and turned out that was the missing piece), VC++ 2017 tools, Visual C++ tools for CMake and C++/CLI support. Not sure about the necessity of the last ones, those were already installed before I got it to work.

The indicated Windows 10 SDK builds are old, I doubt they should be used, if required at all. I only installed the most recent one, which currently is 10.0.17763.0, which turned out that was enough.

And for some reason VS installed .NET Framework 4.6.1 targeting pack while 4.6 was required, maybe useful to mention that as well.

As for the directory structure, makes sense, I'll remember that :)

**Comment by bartgrefte** [comment] 2019-03-30 10:13
One small question, how can I select which version to compile? For example, if I want 2.1.7 instead of a preview version of 3.0.0.

**Comment by vitek-karas** [comment] 2019-04-01 13:48
Releases are tagged; https://github.com/dotnet/core-setup/releases/tag/v2.1.7
From there, you can find the hash of the last commit: cca5d72d48c1dd5633e92a8f2f8f3a4b9f9ff774
So if you checkout that has, you should get the same sources as 2.1.7.

Not sure about the tools requirements, for example VS 2019 would definitely not be supported. But VS 2017 should work.

**Comment by bartgrefte** [comment] 2019-04-03 11:05
Okay, thanks :)

**Comment by jeffschwMSFT** [comment] 2019-04-30 19:48
Closing out this issue, but if you still have questions please let us know.

**Closed by jeffschwMSFT** 2019-04-30 19:48 UTC
Labels: area-Host, question
