### ISSUE TITLE
Missing Method Exceptions from Kestrel when trying to run Web API on Raspberry Pi

### ISSUE THREAD

**Issue by challe** [dotnet/core-setup#1632] opened 2017-03-04 08:09 UTC
## Steps to reproduce
`dotnet new webapi`

Change the `csproj`-file so that it looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
 <PropertyGroup>
   <TargetFramework>netcoreapp2.0</TargetFramework>
   <RuntimeFrameworkVersion>2.0.0-beta-001663-00</RuntimeFrameworkVersion>
 </PropertyGroup>

 <ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-preview1-23656" />
   <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-preview1-23656" />
   <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.2.0-preview1-23656" />
 </ItemGroup>
</Project>
```
Followed by
```
dotnet restore
dotnet publish
```

Now take all of the files that were created in the `bin/Debug/netcoreapp2.0/publish` and copy these files to the Raspberry Pi. Try to run the application by doing:
`usr/bin/dotnet /home/challe/dev/test/test.dll`.

It says that the application has started and that it is listening on port 5000!
Visit http://localhost:5000/api/values in the browser, locally on your Raspberry Pi.

## Expected  behavior
I expected to see the JSON values in the browser.

## Actual behavior
In the terminal, I see:
```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: '!0 System.Span`1.get_Item(Int32)'.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetKnownVersion(Span`1 span, String& knownVersion)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(ReadableBuffer buffer, ReadCursor& consumed, ReadCursor& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

## Environment data
I am currently using the `2.0.0-beta-001663-00` runtime on my Raspberry Pi.

`dotnet --info` output:
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-004853\

**Comment by Petermarcu** [comment] 2017-03-04 15:43
Interesting, there is an effort going on right now to move ASP.NET on top of Span. @KrzysztofCwalina , does there need to be an explicit reference to the Span package at this point?

I think its in this package: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Memory

ASP.NET versions that use that type should be referencing that package.

**Comment by Petermarcu** [comment] 2017-03-04 15:44
I'm guessing this happens everywhere. Not just on your Pi.

**Comment by gkhanna79** [comment] 2017-03-04 20:33
CC @jkotas

**Comment by jkotas** [comment] 2017-03-04 20:46
This is caused by breaking change in System.Memory public surface that @ahsonkhan made to fix https://github.com/dotnet/corefx/issues/13681.

ASP.NET needs to pick up latest version of System.Memory packages to be compatible with latest Microsoft.NETCore.App.

**Comment by jkotas** [comment] 2017-03-04 21:10
@davidfowl What does need to happen for ASP.NET to pick up latest System.Memory?

**Comment by davidfowl** [comment] 2017-03-04 23:07
I'm surprised we're even binding to that method. We need to wait until the corefxlab packages get mirrored into asp.net's feed. That's being worked on...No eta yet /cc @pranavkm

**Comment by Petermarcu** [comment] 2017-03-04 23:10
In the meantime, can @challe reference the package directly or will that break other things?

**Comment by davidfowl** [comment] 2017-03-04 23:32
Referencing the package won't help. You'd need to downgrade your runtime back to netcoreapp1.1

**Comment by Petermarcu** [comment] 2017-03-05 02:28
Can't, this is an architecture we don't have in 1.X. we need to get 2.0 working.

**Comment by Petermarcu** [comment] 2017-03-05 02:29
Should we undo the breaking change until this is properly coordinated?

**Comment by davidfowl** [comment] 2017-03-05 03:37
> Should we undo the breaking change until this is properly coordinated?

We *could* but I like using it as a forcing function to get our mirror fixed.

/cc @Eilon

**Comment by Petermarcu** [comment] 2017-03-05 04:09
It would be great to understand how long this will be broken and back out the change if its going to be more than a day or so. We have a lot of people using 2.0 pre-release builds that will quickly discover this break.

**Comment by jkotas** [comment] 2017-03-05 05:03
https://github.com/aspnet/kestrelHttpServer is the last part that requires updating to get the change absorbed. Revering it would need to propagate through coreclr, corefx and corefxlab.

**Comment by Petermarcu** [comment] 2017-03-05 22:41
Looks like ASP.NET was able to get a build out with all the updated references.  If you get the latest from the MyGet feed this should be fixed. Here is the feed to add to your NuGet.config (I assume you already had it).

https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

Make sure you have at least : Microsoft.AspNetCore.Server.Kestrel 1.2.0-preview1-23736

**Comment by gkhanna79** [comment] 2017-03-06 18:59
Issue moved to [dotnet/corefx #16778](https://github.com/dotnet/corefx/issues/16778) via [**ZenHub**](https://www.zenhub.com/)

**Closed by gkhanna79** 2017-03-06 18:59 UTC
