### ISSUE TITLE
Broken packages for Ubuntu Server 18.04

### ISSUE THREAD

**Issue by jbyl** [dotnet/core-setup#4417] opened 2018-07-30 20:31 UTC
## Steps to reproduce
Follow the steps at [https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/runtime-current](url)

## Expected  behavior
Running `sudo apt-get install aspnetcore-runtime-2.1` installs the package alongside its dependencies.

## Actual behavior
apt fails with the following message:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.2) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

## Environment data
Ubuntu Server 18.04.1

**Comment by leecow** [comment] 2018-07-31 17:25
Package feed has been tested fine so we need to look at your system. Do you have previous versions of .NET currently installed? You can check with `dpkg --get-selections | grep dotnet`.

**Comment by jBylinski** [comment] 2018-07-31 17:48
I’ve just found out I was missing the universe repository, it works fine after adding it to sources.list! Sorry, it’s all working now!

**Comment by mandrewbot3k** [comment] 2018-07-31 22:39
I had the same issue, adding the universe repository fixed it as @jBylinski mentioned

```
sudo add-apt-repository universe
sudo apt-get update

```

**Comment by rakeshsinghranchi** [comment] 2018-08-01 22:38
@leecow , is there a plan to update the .NET Core installation guide for Ubuntu 18.04 ?

**Comment by leecow** [comment] 2018-08-01 22:56
Yep, looks like this is an issue with the default repo setup on Ubuntu Server so we'll find a place to add the appropriate content.

**Comment by joshfree** [comment] 2018-08-01 23:16
Linking to related/duplicate issue https://github.com/dotnet/core/issues/1822

we need to add ```sudo add-apt-repository universe``` to the installation instructions for Ubuntu 18.04

**Comment by KhalilMohammad** [comment] 2018-08-11 14:08
I got same issue , Even after running `sudo add-apt-repository universe` ..Net Core 2.0.9 runtime not installing on ubuntu

**Comment by kartas39** [comment] 2018-11-07 21:32
caused by powershell package.

Depends: libc6, libgcc1, libgssapi-krb5-2, liblttng-ust0, libstdc++6, zlib1g, libssl1.0.0, libicu55
Ubuntu 18.04 actually has libicu**60**

**Comment by dagood** [comment] 2019-02-27 17:14
@leecow can you verify the instructions are updated and this can be closed?

**Comment by dagood** [comment] 2019-11-20 22:04
@leecow verified, closing.

**Closed by dagood** 2019-11-20 22:04 UTC
Labels: area-Setup, documentation
