### ISSUE TITLE
AppHost for WinExe fails silently when framework isn't found

### ISSUE THREAD

**Issue by ericstj** [dotnet/core-setup#4810] opened 2018-11-27 23:35 UTC
## Steps to reproduce
using latest SDK do dotnet new WPF
set the RuntimeFrameworkVersion to some version that is not in installed in dotnet\shared
build app
run built exe

## Expected  behavior
error message that has similar info to commandline experience, eg: 
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '3.0.0-preview1-27024-03' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
...
```

## Actual behavior
silent failure.

/cc @steveharter @vitek-karas @adamyoblick

**Comment by ericstj** [comment] 2018-11-27 23:40
For reference, here's the dialog we get on desktop for a similar situation.
![image](https://user-images.githubusercontent.com/8918108/49118832-c3c13e00-f25a-11e8-9b05-594ab0562733.png)

**Comment by vitek-karas** [comment] 2018-11-28 08:38
Duplicate of #4768

**Closed by vitek-karas** 2018-11-28 08:38 UTC
Labels: area-Host, os-windows
