### ISSUE TITLE
Threadpool stops working inside delegates called from unmanaged code when using hostfxr_initialize_for_dotnet_command_line_fn with hostfxr_run_app_fn

### ISSUE THREAD

**Issue by FabianTerhorst** [dotnet/core-setup#7809] opened 2019-08-22 17:45 UTC
## Steps to reproduce
Call hostfxr_initialize_for_dotnet_command_line_fn with following params
```c
const char* args[1];
args[0] = "Host.dll";
_init(1, args, nullptr, &cxt);
_runApp(cxt); // hostfxr_run_app_fn
```
The application is now unable to use the threadpool

```csharp
ThreadPool.QueueUserWorkItem(state =>
{
Console.WriteLine("Hello from thread pool");
});
```

The ThreadPool.PendingWorkItemCount just increases but never reduces.

When using instead threadpool continues to work. It seems to be related to hosting using hostfxr_initialize_for_dotnet_command_line_fn
```c
_init(config_path, nullptr , &cxt);
rc = _getDelegate(
            cxt,
            hdt_load_assembly_and_get_function_pointer,
            &load_assembly_and_get_function_pointer);
if (rc != 0 || load_assembly_and_get_function_pointer == nullptr)
    std::cerr << "Get delegate failed: " << std::hex << std::showbase << rc << std::endl;
int result = load_assembly_and_get_function_pointer(
            "Host.dll",
            STR("Host, Host"),
            STR("Main"),
            nullptr,
            nullptr,
            (void**) &main);
main(nullptr, null);
```

## Expected  behavior

Threadpool should continue to work.

## Actual behavior

Threadpool isn't working.

## Environment data

docker
```FROM mcr.microsoft.com/dotnet/core-nightly/sdk:3.0.100-preview9 as dotnet```

**Comment by vitek-karas** [comment] 2019-08-22 22:20
I tried this on both Linux and Windows - even on the container you specified, but it seems to work for me. I'm trying this with managed app like this:
```C#
using System;
using System.Threading;

namespace threadpool
{
    class Program
    {
        static int _count;

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.ReadLine();
            for (int i = 0; i < 10000; i++)
            {
                ThreadPool.QueueUserWorkItem(_ => Interlocked.Increment(ref _count));
            }

            while (ThreadPool.PendingWorkItemCount > 0)
            {
                Thread.Sleep(100);
            }

            Console.WriteLine($"Processed {_count}");
            Console.ReadLine();
        }
    }
}
```

For the native host I'm using the test host `nativehost` which is here: https://github.com/dotnet/core-setup/tree/master/src/corehost/cli/test/nativehost
I run something like:
```
./nativehost host_context app none /usr/share/dotnet/host/fxr/3.0.0-preview9-19419-03/libhostfxr.so bin/Debug/netcoreapp3.0/threadpool.dll
```

Which will call `hostfxr_initialize_for_dotnet_command_line` and then `hostfxr_run_app`.

Could you please share your managed app you're trying this on? Or even better (if possible) the native host?

You can also try tracing:
```
dotnet tool install -g dotnet-counters --version 3.0.0-preview8.19412.1 
export PATH="$PATH:/root/.dotnet/tools"
```

Now run the app (with the read-lines in it, so that it's possible to wait).
Run
```
dotnet-counters --list-processes
```
And take note of the PID of the app.
Then run 
```
dotnet-counters monitor -p <PID>
```

You should see lines like this:
```
    ThreadPool Queue Length                         0
    ThreadPool Completed Work Items / sec           0 
```

Now hit Enter in the window with the app running. After that you should see a big spike in the completed work item count above.

**Comment by FabianTerhorst** [comment] 2019-08-22 23:10
Yes sry i missed a important step for reproducing. My host is creating a AssemblyLoadContext and loads the dll via ```resourceAssembly = resourceAssemblyLoadContext.LoadFromAssemblyPath(resourceDllPath);```
In my host the threadpool works as well, but not inside the loaded assembly. And the assembly load context is collectable. I also cache the assembly load context in a dictionary in my host 
```csharp
private static readonly IDictionary<string, ResourceAssemblyLoadContext> _loadContexts =
            new Dictionary<string, ResourceAssemblyLoadContext>();
```
```csharp
public class ResourceAssemblyLoadContext : AssemblyLoadContext
    {
        private readonly AssemblyDependencyResolver resolver;

        private readonly string resourcePath;

        public ResourceAssemblyLoadContext(string resourceDllPath) : base(true)
        {
            resolver = new AssemblyDependencyResolver(resourceDllPath);
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            var assemblyPath = resolver.ResolveAssemblyToPath(assemblyName);
            return assemblyPath != null ? LoadFromAssemblyPath(assemblyPath) : null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            var libraryPath = resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            return libraryPath != null ? LoadUnmanagedDllFromPath(libraryPath) : IntPtr.Zero;
        }
    }
```

**Comment by vitek-karas** [comment] 2019-08-23 04:30
Still having trouble reproing, but I'll work on that some more.

Can you try running the app with just `dotnet app.dll`? Does that work?

The main difference between running the code as an app versus via the delegate is that the "app" version will have all the app assemblies in the `AssemblyLoadContext.Default`, while the one via delegate will only have the framework in the `Default`, and the "app" will be loaded into a separate ALC (created by the runtime), which looks very similar to the one you have.

The "Trick" is that ALC's don't form a hierarchy, there's the `Default` and then everything else. So in the app case, if the custom ALC can't resolve a dependency it will be loaded from `Default`, which includes the app's assemblies. But in the "delegate" case, if the custom ALC of yours can't resolve something, it would also fallback just to `Default`, which only has frameworks.

My guess here would be that there's something weird going on with assembly resolution. But it should repro running with just `dotnet app.dll` as well.

**Comment by FabianTerhorst** [comment] 2019-08-23 08:01
The assembly the host loads is a class library, so it can't be executed directly without the host.

**Comment by vitek-karas** [comment] 2019-08-23 08:03
In that case I don't understand - how can it work at all with `hostfxr_initialize_for_dotnet_command_line` and `hostfxr_run_app`? For that to work the assembly must be an app (as in must have an entry point).

Internally the `hostfxr` does pretty much the same thing is you use `hostfxr_run_app` and if you use `dotnet app.dll`...

**Comment by FabianTerhorst** [comment] 2019-08-23 09:48
The host.dll is a assembly, but the dll the host loads via ```resourceAssembly = resourceAssemblyLoadContext.LoadFromAssemblyPath(resourceDllPath);``` isn't. You mean with app.dll the host and not the dll the host loads?

**Comment by FabianTerhorst** [comment] 2019-08-23 12:14
I couldn't find a lot of documentation or small sample code for hostfxr_initialize_for_dotnet_command_line_fn. Is the only required argument the name of the dll to execute as a assembly?

**Comment by FabianTerhorst** [comment] 2019-08-23 13:41
Its actually not related to the alc but the threadpool isn't working in the function pointer i pass to the cpp code. But its working when not using hostfxr_initialize_for_dotnet_command_line_fn.

**Comment by FabianTerhorst** [comment] 2019-08-23 13:42
My host is registering some functions on startup that im calling from the cpp code to communicate the host to load or unload specific dlls.

**Comment by FabianTerhorst** [comment] 2019-08-23 13:43
I used the same way with the delegate way and also just used load_assembly_and_get_function_pointer to call the static main that registers the function pointers

**Comment by FabianTerhorst** [comment] 2019-08-23 13:54
Thats how i pass my delegates
```csharp
        private const string DllName = "module";
        private const CallingConvention NativeCallingConvention = CallingConvention.Cdecl;

        internal delegate int CoreClrDelegate(IntPtr args, int argsLength);

        [DllImport(DllName, CallingConvention = NativeCallingConvention)]
        internal static extern void CoreClr_SetResourceLoadDelegates(CoreClrDelegate resourceExecute, CoreClrDelegate resourceExecuteUnload);
```
```csharp
_executeResource = ExecuteResource;
GCHandle.Alloc(_executeResource);
_executeResourceUnload = ExecuteResourceUnload;
GCHandle.Alloc(_executeResourceUnload);
CoreClr_SetResourceLoadDelegates(_executeResource, _executeResourceUnload);
```

**Comment by vitek-karas** [comment] 2019-08-23 21:10
Thanks for the additional information, I tried another repro, but no luck still.
I tried only on Windows this time - to make it faster for me - but if this is the right approach I can try to make this happen in Linux as well.

What I did:
* Managed app `Host` (so one that has Main)
  * This loads a native module `HostModule` which exports one function `CoreClr_SetResourceLoadDelegate`
  * It calls that function and passes in a delegate to a managed method (very similar to your sample above)
  * Then it just waits - blocking the main thread
* The native `HostModule` when it gets called it remembers the function pointer it got from managed
  * It then starts a new thread, sleeps on it for a while
  * Then it calls the function pointer to go back to managed (on a different thread now)
* Then the managed callback is called it will:
  * Create a new ALC
  * Load a plugin into it (in isolation)
  * Call the plugin
* The plugin queues lot of work items on thread pool and waits for them to finish.

All of this works as expected when I just run it as an app (so `dotnet host.dll`).  
It also works if I run it using the `hostfxr_initialize_for_dotnet_command_line("host.dll")` and `hostfxr_run_app`.

Can you please point out which parts are different enough from your setup, so that I can tweak my repro some more?

**Comment by FabianTerhorst** [comment] 2019-08-23 23:02
One difference is that my host main isn't blocking, because it's executed in the main thread of the cpp application and the delegates will call on that same thread a bit later.

**Comment by vitek-karas** [comment] 2019-08-23 23:09
Hmm - I don't understand that. What does your host main do? And how is it started? Sorry - I must admit a'm getting a bit lost in all of this ... please bear with me.

If your host is an application, how can it "not" block in main - do you mean you actually exit `Main` and then the native side will call into the runtime again (via the passed delegates)?

**Comment by FabianTerhorst** [comment] 2019-08-23 23:14
Yes it exists Main and then the native side calls the runtime again with the passed delegates.

**Comment by FabianTerhorst** [comment] 2019-08-23 23:15
The host mainthread dies after the Main exists but that wasn't the case with load_assembly_and_get_function_pointer

**Comment by vitek-karas** [comment] 2019-08-23 23:27
OK - I finally understand... 
The short answer is: This is not supported.

If you run it as an application, once the `Main` exits, the runtime goes through a shutdown sequence, turning things off. One of those things is probably the thread pool (I would expect it to release/stop all threads in it). It's true that in .NET Core the shutdown is very "limited", but things still happen.
To be honest I'm surprised things still seem to mostly work - I wouldn't be surprised for other things to break.  
The behavior is basically - running a .NET Core app (in the "app" mode) in a given process, the runtime assumes ownership of that process - and once the app exits, the runtime assumes the process will exit as well. The native host has the ability to change this, but it really should not.

If you run the code via the `load_assembly_and_get_function_pointer` the runtime doesn't go through the shutdown, this mode is intended for "plugin" like cases, so we start the runtime and it basically never stops. So in this mode it should work well.

**Comment by FabianTerhorst** [comment] 2019-08-23 23:38
But this worked before with coreclrhost. I had to switch to hostfxr for supporting AssemblyDependencyResolver. When not executing the host as a assembly it has some platform limitations like ```System.Configuration.ConfigurationManager```.

**Comment by vitek-karas** [comment] 2019-08-23 23:50
That is very possible... the coreclrhost (and the coreclr_initialize based hosting) are "Direct" coreclr hosts which have greater control over the runtime.
The hostfxr hosting is more for "common" cases and makes some things much easier, but it is intentionally not allowing full control over the runtime. This is one such example. Yes, the call to explicitly shutdown the runtime is very likely what causes the difference in behavior.

I would be very interested in what is your higher level scenario to want the bahavior of "running it like an app, but using it like plugins". I vividly remember that when we were discussing some of the limitations of the hostfxr hosting, I personally said "If the host is running an app, the app will assume it sort of owns the process, so allowing for example running two apps in one process doesn't make much sense". Apparently I was at least in some cases wrong - so I would like to understand what is the overall scenario and why this seems to be a solution for it.

As for making it work - since you control the native host and the managed app (it seems), you could add a dummy Main to your app, and in the native host start a new thread and run the app on it - it would basically just block and sit in Main .. forever. That way you get the app-like behavior of true app startup, but the native host still gets to maintain full control over the process. It would be wasting one thread, but that doesn't feel too bad.

**Comment by FabianTerhorst** [comment] 2019-08-23 23:56
My usecase is to provide a c# coding api to a server that is single threaded. The server starts all resources on the main thread and all server apis are called on the main thread as well. The server itself is written in cpp.

**Comment by FabianTerhorst** [comment] 2019-08-25 00:03
For me the workaround with the extra thread that is initializing the runtime works just fine and the server starts a few ms faster now as well because the runtime initializes while server is doing some work on startup as well.

**Comment by vitek-karas** [comment] 2019-08-25 07:19
Great to hear that the workaround is suitable for you.
As for your overall scenario, this is what the `load_assembly_and_get_function_pointer` was designed for. Since it doesn't work fully for you, could you please describe in a bit more detail what are the issues you're aware of with that approach?

**Comment by vitek-karas** [comment] 2019-09-02 06:53
@FabianTerhorst could you please describe in a bit more detail what are the limitations when not executing the assembly as an app? You mentioned something about `ConfigurationManager` - what is the problem there?

**Comment by vitek-karas** [comment] 2019-09-16 15:24
@FabianTerhorst could you please describe shortly what are the limitations you know about when not executing assembly as an app? I want to make sure we track this issue correctly and possibly fix it in the future. Thank you very much.

**Comment by vitek-karas** [comment] 2019-10-11 16:24
If you get around to this - I would still be very interested what are the limitations of the hosting APIs you ran into (as compared to running the code as an app). For now I'm closing the issue as the main problem seems to be solved.

**Closed by vitek-karas** 2019-10-11 16:24 UTC
Labels: area-Host, question
