### ISSUE TITLE
Setting PreserveCompilationContext=false trims Microsoft.AspNetCore.App shared runtime in deps files

### ISSUE THREAD

**Issue by pranavkm** [dotnet/core-setup#3902] opened 2018-03-26 17:18 UTC
## Steps to reproduce
1. Create an webapi \ mvc \ emptyweb application using preview1 (or preview2) Sdk
2. Build the project

The generated deps file will say that the application references both `Microsoft.NETCore.App` and `Microsoft.AspNetCore.App`:

```json
"blah/1.0.0": {
    "dependencies": {
      "Microsoft.AspNetCore.App": "2.1.0-preview1-final",
      "Microsoft.NETCore.App": "2.1.0-preview1-26216-03"
    },
    "runtime": {
      "blah.dll": {}
    },
    "compile": {
      "blah.dll": {}
    }
},
```

3. Delete the bin directory. Edit the csproj `<PreserveCompilationContext>false</PreserveCompilationContext>`. Rebuild the project
4. The generated deps file will say that the app no longer references `Microsoft.AspNetCore.App`:

```json
 "blah/1.0.0": {
   "dependencies": {
     "Microsoft.NETCore.App": "2.1.0-preview1-26216-03"
   },
   "runtime": {
     "blah.dll": {}
   }
 },
```

## Environment data
```
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\Pranav\Downloads\dotnet-sdk-2.1.300-preview1-008174-win-x64\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

## More information:
The bulk of MVC's controller discovery model is based on finding libraries that directly or transitively depend on any one of Mvc's libraries. In 2.1.0-preview2, the Razor.Sdk only sets `PreserveCompilationContext=true` if the app has any files that require runtime compilation. For projects without views, such as webapi or empty web template, the produced deps file claims that the app does not reference `Microsoft.AspNetCore.App` -> `Microsoft.AspNetCore.Mvc`. Consequently no controllers are discovered.

**Comment by pranavkm** [comment] 2018-03-26 17:57
Spoke to @eerhardt, the missing shared runtime isn't necessarily the cause for concern here - a console app's deps file also does not include a reference to the shared runtime `Microsoft.NETCore.App`. The issue is that `DependencyContext.Load` does not merge shared fx deps files. The suggested fix is to add a new overload to `DependencyContext.Load` that walks up the fx chain and merges the runtime deps files. MVC can consume this API once this is available.

cc @rynowak \ @steveharter \ @mkArtakMSFT

**Comment by eerhardt** [comment] 2018-03-28 01:44
Looking more, the `DependencyContext.Load` DOES merge in the shared fx deps files.

The issue is that the `Dependency` information is getting trimmed, so there is no link from the application's library to the MVC library.  Or similarly, if the application references another project that contains controllers, that project won't have a Dependency on the MVC library either.  This trimming logic is in the `dotnet/sdk` repo.  Moving this issue there.

**Comment by eerhardt** [comment] 2018-03-28 01:45
This issue was moved to dotnet/sdk#2092

**Closed by eerhardt** 2018-03-28 01:45 UTC
Labels: area-DependencyModel
