### ISSUE TITLE
Tests should restore a specific version of Microsoft.NETCore.DotNetAppHost, and not the highest version available on MyGet

### ISSUE THREAD

**Issue by ravimeda** [dotnet/core-setup#2127] opened 2017-04-20 18:44 UTC
## Steps to reproduce
Restore `Microsoft.NETCore.DotNetAppHost` package, which is needed for tests located at `/opt/code/TestAssets/TestProjects`
This can be by running `build.sh` or `build.cmd`.

## Expected  behavior
Version matching should not be `*`. Rather should match a specific version. For example, `2.0.0-preview1-002042-00`

## Actual behavior
Restores the highest version matching `2.0.0-preview1-*`
Refer to https://github.com/dotnet/core-setup/blob/master/TestAssets/TestProjects/LightupClient/project.json

## Environment data

**Comment by ravimeda** [comment] 2017-04-20 18:45
FYI @chcosta @weshaggard

**Comment by chcosta** [comment] 2017-04-20 18:47
I think the issue is restoring "Microsoft.NETCore.App", not DotNetAppHost specifically.  The tests reference Microsoft.NETCore.App and then that package pulls in its dependencies , which include DotNetAppHost

**Comment by gkhanna79** [comment] 2017-04-20 20:57
The * enables referencing the version to be restored that built during the build. Thus, it cannot be the specific version.

**Comment by gkhanna79** [comment] 2017-04-20 20:57
CC @eerhardt @ramarag

**Comment by weshaggard** [comment] 2017-04-20 21:23
Yes but once we move to PackageReference vs project.json we should directly reference the specific version we are building to eliminate the trouble we have with the * versioning.

**Comment by eerhardt** [comment] 2017-04-20 21:31
Yes, the main issue here is that the tests *need* to reference the version of the product that was just built.  This was not as feasible in project.json world since you couldn't use parameters.

I agree with @weshaggard that moving to MSBuild will help this issue.

**Comment by mellinoe** [comment] 2017-05-02 02:54
Thanks for letting me know about this. I was banging my head against the wall trying to figure out some problems related to this.

**Closed** 2017-05-04 01:03 UTC
Labels: area-Infrastructure
