### ISSUE TITLE
The ARM build contains x86_64 assemblies

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/core-setup#1908] opened 2017-03-31 16:39 UTC
I have updated the core-setup build from my Yocto layer (https://github.com/Tragetaschen/meta-aspnet) to something more recent (1ccdf2e8cee) and compared to the old commit, the build system now complains about `libhostfxr.so` being in the wrong format. It's actually an x86-64 binary.

I've only slightly modified the core-setup build. Most notably, I'm [setting `__rid_plat` manually](https://github.com/Tragetaschen/meta-aspnet/blob/preview1/recipes-dotnet/corehost/corehost/0001-build.sh-Support-our-build.patch#L22) to `ubuntu.16.04-arm` in `src/corehost/build.sh`. That's because my distribution's /etc/os-release file doesn't contain anything that's supported so my rootfs doesn't have that file

So far I have checked a couple of things:
- I have verified in the build logs, that it's actually buiding for the `ubuntu.16.04-arm` RID
- The `so`s in `artifacts/ubuntu.16.04-arm/corehost` are the actual ARM binaries
- I've unzipped `runtime.ubuntu.16.04-arm.Microsoft.NETCore.DotNetHostResolver.2.0.0-preview1-001872-00.nupkg` from next to the `so`s and verified that it contains the ARM `libhostfxr.so` binary
- the `project.lock.json` in `artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework` only mentions one `libhostfxr.so` from the above DotNetHostResolver nupkg
- The publishing output from that project in `artifacts/ubuntu.16.04-arm/intermediate/sharedFrameworkPublish/shared/Microsoft.NETCore.App/2.0.0-preview1-001872-00/` contains an x64 version of `libhostfxr.so` and that is copied into the final `combined-framework-host` folder

I manually ran the restore/publish commands from the build for the `framework` project and that results in both `libhostfxr.so` and `libhostpolicy.so` being published as x86-64 version.

All other `so`s (like `libclrjit.so` or `System.Native.so` from CoreCLR and CoreFX resp.) are the correct ARM versions.

What else can I do?

For reference, here's the relevant (?) portion of the build log for the `framework` build:
```
[...]
[EXEC       >] [....] [00:06:14.511] /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/.dotnet_stage0/Linux/dotnet "restore" "--verbosity" "verbose" "--disable-parallel" "--infer-runtimes" "--fallbacksource" "/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/corehost"
trace: NuGet Command Line Version: 3.6.0.0
trace: Running non-parallel restore.
trace: Reading project file /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/project.json.
log  : Restoring packages for /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/project.json...
trace: Restoring packages for .NETCoreApp,Version=v2.0...
trace: Resolving conflicts for .NETCoreApp,Version=v2.0...
trace: Acquiring lock for the installation of Microsoft.NETCore.App 2.0.0-preview1-001872-00
trace: Acquired lock for the installation of Microsoft.NETCore.App 2.0.0-preview1-001872-00
log  : Installing Microsoft.NETCore.App 2.0.0-preview1-001872-00.
trace: Completed installation of Microsoft.NETCore.App 2.0.0-preview1-001872-00
trace: Acquiring lock for the installation of Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00
trace: Acquired lock for the installation of Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00
log  : Installing Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00.
trace: Completed installation of Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00
trace: Acquiring lock for the installation of Microsoft.NETCore.Platforms 2.0.0-beta-25129-02
trace: Acquired lock for the installation of Microsoft.NETCore.Platforms 2.0.0-beta-25129-02
log  : Installing Microsoft.NETCore.Platforms 2.0.0-beta-25129-02.
trace: Completed installation of Microsoft.NETCore.Platforms 2.0.0-beta-25129-02
trace: Acquiring lock for the installation of NETStandard.Library 2.0.0-beta-25129-01
trace: Acquired lock for the installation of NETStandard.Library 2.0.0-beta-25129-01
log  : Installing NETStandard.Library 2.0.0-beta-25129-01.
trace: Completed installation of NETStandard.Library 2.0.0-beta-25129-01
trace: Acquiring lock for the installation of Microsoft.Packaging.Tools 1.0.0-beta-25129-01
trace: Acquired lock for the installation of Microsoft.Packaging.Tools 1.0.0-beta-25129-01
log  : Installing Microsoft.Packaging.Tools 1.0.0-beta-25129-01.
trace: Completed installation of Microsoft.Packaging.Tools 1.0.0-beta-25129-01
trace: Scanning packages for runtime.json files...
trace: Merging in runtimes defined in package/Microsoft.NETCore.App 2.0.0-preview1-001872-00.
trace: Merging in runtimes defined in package/Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00.
trace: Merging in runtimes defined in package/Microsoft.NETCore.Platforms 2.0.0-beta-25129-02.
trace: Merging in runtimes defined in package/Microsoft.NETCore.DotNetHostResolver 2.0.0-preview1-001872-00.
trace: Merging in runtimes defined in package/Microsoft.NETCore.DotNetAppHost 2.0.0-preview1-001872-00.
trace: Restoring packages for .NETCoreApp,Version=v2.0 (ubuntu.16.04-arm)...
trace: Resolving conflicts for .NETCoreApp,Version=v2.0 (ubuntu.16.04-arm)...
trace: Acquiring lock for the installation of runtime.ubuntu.16.04-arm.Microsoft.NETCore.App 2.0.0-preview1-001872-00
trace: Acquired lock for the installation of runtime.ubuntu.16.04-arm.Microsoft.NETCore.App 2.0.0-preview1-001872-00
log  : Installing runtime.ubuntu.16.04-arm.Microsoft.NETCore.App 2.0.0-preview1-001872-00.
trace: Completed installation of runtime.ubuntu.16.04-arm.Microsoft.NETCore.App 2.0.0-preview1-001872-00
trace: Acquiring lock for the installation of runtime.ubuntu.16.04-arm.Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00
trace: Acquired lock for the installation of runtime.ubuntu.16.04-arm.Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00
log  : Installing runtime.ubuntu.16.04-arm.Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00.
trace: Completed installation of runtime.ubuntu.16.04-arm.Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-001872-00
trace: Checking compatibility of packages on .NETCoreApp,Version=v2.0.
trace: All packages and projects are compatible with .NETCoreApp,Version=v2.0.
trace: Checking compatibility of packages on .NETCoreApp,Version=v2.0 (ubuntu.16.04-arm).
trace: All packages and projects are compatible with .NETCoreApp,Version=v2.0 (ubuntu.16.04-arm).
info : Committing restore...
log  : Writing lock file to disk. Path: /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/project.lock.json
log  : Generating MSBuild file /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/framework.nuget.targets.
log  : Generating MSBuild file /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/framework.nuget.props.
log  : Restore completed in 1252ms for /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/project.json.

NuGet Config files used:
    /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/NuGet.Config
    /home/kai/.nuget/NuGet/NuGet.Config

Feeds used:
    /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/corehost
    /home/kai/sources/build/tmp/sysroots/f500sx/opt/dotnet-nupkg
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://dotnet.myget.org/F/cli-deps/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json

Installed:
    7 package(s) to /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/project.json
[EXEC       <] [ OK ] [00:06:16.015] /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/.dotnet_stage0/Linux/dotnet "restore" "--verbosity" "verbose" "--disable-parallel" "--infer-runtimes" "--fallbacksource" "/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/corehost" exited with 0
[EXEC       >] [....] [00:06:16.015] /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/.dotnet_stage0/Linux/dotnet "publish" "--output" "/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFrameworkPublish/shared/Microsoft.NETCore.App/2.0.0-preview1-001872-00" "-r" "ubuntu.16.04-arm" "/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework"
Publishing framework for .NETCoreApp,Version=v2.0/ubuntu.16.04-arm
Project framework (.NETCoreApp,Version=v2.0) will be compiled because expected outputs are missing
Compiling framework for .NETCoreApp,Version=v2.0
/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework/project.json(3,25): warning DOTNET1015: The 'compilationOptions' option is deprecated. Use 'buildOptions' instead.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.7458742


publish: warning: host executable not available in dependencies, using host for current platform
publish: Published to /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFrameworkPublish/shared/Microsoft.NETCore.App/2.0.0-preview1-001872-00
Published 1/1 projects successfully
[EXEC       <] [ OK ] [00:06:17.419] /home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/.dotnet_stage0/Linux/dotnet "publish" "--output" "/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFrameworkPublish/shared/Microsoft.NETCore.App/2.0.0-preview1-001872-00" "-r" "ubuntu.16.04-arm" "/home/kai/sources/build/tmp/work/cortexa9hf-neon-target-linux-gnueabi/corehost/2.0-25129-02-r0/git/artifacts/ubuntu.16.04-arm/intermediate/sharedFramework/framework" exited with 0
[...]
```

**Comment by JensNordenbro** [comment] 2017-04-07 08:30
Although not to the point of your question, have you tried building for Linux-arm RID. That rid seems to have progressed lately: [issue 1832](https://github.com/dotnet/core-setup/issues/1832).

According too my intepretation that will be much more inline with the issues of a meta-dist like Yocto. 
Regardless, maybe these guys can help you!

**Comment by Tragetaschen** [comment] 2017-04-07 12:09
Thanks for the pointer!

**Comment by Tragetaschen** [comment] 2017-04-18 09:16
I just checked the official builds that are linked in README.md and those have that problem as well.

In all of
- https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-linux-arm.latest-portable.tar.gz
- https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-ubuntu-arm.latest.tar.gz
- https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-ubuntu.16.04-arm.latest.tar.gz
the `shared/Microsoft.NETCore.App/2.0.0-preview1-002028-00/libhostfxr.so` is a 64-bit shared library.

**Comment by Tragetaschen** [comment] 2017-04-24 12:39
@gkhanna79 Does this deserve a change in the milestone?

**Comment by gkhanna79** [comment] 2017-04-24 17:47
It does - I have assigned it to myself.

CC @eerhardt

**Comment by gkhanna79** [comment] 2017-04-24 20:35
I downloaded the portable zip linked above and can confirm everything is an Arm binary:

```
gkhanna79@gkhanna-lm181 ~/Downloads/arm/host $ readelf -A fxr/2.0.0-preview2-002066-00/libhostfxr.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_Virtualization_use: TrustZone
gkhanna79@gkhanna-lm181 ~/Downloads/arm/host $ cd ..
gkhanna79@gkhanna-lm181 ~/Downloads/arm $ readelf -A ./shared/Microsoft.NETCore.App/2.0.0-preview2-002066-00/libhostpolicy.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_Virtualization_use: TrustZone
gkhanna79@gkhanna-lm181 ~/Downloads/arm $ 
```

**Comment by gkhanna79** [comment] 2017-04-24 20:38
I can confirm that libhostfxr.so that is within SharedFX folder is ELF64:

```
-rwxr-xr-x 1 gkhanna79 gkhanna79 295923 Apr 21 18:22 libhostfxr.so
gkhanna79@gkhanna-lm181 ~/Downloads/arm/host $ readelf -A fxr/2.0.0-preview2-002066-00/libhostfxr.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_Virtualization_use: TrustZone
gkhanna79@gkhanna-lm181 ~/Downloads/arm/host $ cd ..
gkhanna79@gkhanna-lm181 ~/Downloads/arm $ readelf -A ./shared/Microsoft.NETCore.App/2.0.0-preview2-002066-00/libhostpolicy.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_Virtualization_use: TrustZone
gkhanna79@gkhanna-lm181 ~/Downloads/arm $ 
```

**Comment by gkhanna79** [comment] 2017-04-24 20:39
@eerhardt @ramarag I thought we had decided to remove hostfxr from sharedFX folder, no? If so, do you know why that is present?

**Comment by gkhanna79** [comment] 2017-04-24 20:49
Looks like it didn't removed because of a bug in https://github.com/dotnet/core-setup/commit/60230ccc6bc88f5388efa4172134609ae460a11a#diff-906b5578c0cbf081f1f173d5922e4a16 that does not account for platform-specific prefix/suffix to be applied. 

CC @ramarag 

I will get a fix in place for this.

**Comment by gkhanna79** [comment] 2017-04-25 00:53
I have requested @ramarag to drive this fix.

**Closed** 2017-04-25 17:46 UTC
Labels: area-Infrastructure, Discussion
