### ISSUE TITLE
dotnet version picker prefers version 1.0.0 over preview builds of 2.0.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/core-setup#1664] opened 2017-03-08 04:14 UTC
- Install VS 2017
- Install [latest build of the 2.0.0 SDK](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.exe)
- Run `dotnet --info`

EXPECTED: Version number is the 2.0.0 preview version, such as 2.0.0-alpha-005165 (exact number will depend on the build that was installed)
ACTUAL: Version number is 1.0.0

Workaround: Use a global.json, with contents such as:

```json
{
    "sdk": {
        "version": "2.0.0-alpha-005165"
    }
}
```

@livarcocc @gkhanna79

**Comment by gkhanna79** [comment] 2017-03-08 17:38
Isn't this a CLI issue @dsplaisted @livarcocc? I am not aware of the host hardcoding 1.0.0 anywhere for this scenario.

**Comment by livarcocc** [comment] 2017-03-08 19:16
This is how the host picks which CLI to run.

I think the host today, prefers a no-preview version of the CLI over a higher version one that is preview. And that's how 1.0.0 is winning over 2.0.0-alpha-something.

**Comment by gkhanna79** [comment] 2017-03-08 19:20
> I think the host today, prefers a no-preview version of the CLI over a higher version one that is preview.

Yes, this is by design. And if there is no production version available, then the highest pre-release will be picked up.

**Comment by livarcocc** [comment] 2017-03-08 19:51
Shouldn't it just follow semver instead of having this special rule?

**Comment by gkhanna79** [comment] 2017-03-08 19:56
This policy was defined as the scenario for SDK from get-go. @piotrpMSFT may have more context on this than I do.

**Comment by Petermarcu** [comment] 2017-03-11 01:11
Do we really want the presence of a pre-release SDK to take over for people who are all using a Release quality SDK? Installing a preview SxS and having that "take over" with lower quality sounds wrong.

**Comment by blackdwarf** [comment] 2017-03-11 04:02
I agree with @Petermarcu. We have a well-defined and understood (and documented) mechanism that provides support for people that want to try out previews. I would not think that our users would expect that they get the preview SDK when they type `dotnet build` on their 1.0 project.

**Comment by richlander** [comment] 2017-03-14 05:19
We had a related conversation today. We should keep the following characteristics:

- Customers can install pre-release .NET Core versions easily and use the same workflows as normal (like `dotnet new`).
- Customer do not regret installing pre-release .NET Core versions. They can continue to use their stable versions for prod work and can uninstall or upgrade the pre-release version cleanly.

**Comment by gkhanna79** [comment] 2017-03-14 05:25
IIRC, there was a discussion around doing something like `dotnet new --fxver <ver>` that would help such scenarios and the goals above. Where did that eventually land?

**Comment by natemcmaster** [comment] 2017-03-16 19:07
cc @davidfowl @kichalla are you aware of this? It looks like we need to re-add global.json to all aspnet projects to make 2.0.0 CLI work.

**Comment by natemcmaster** [comment] 2017-03-16 19:48
This is painful for dogfooding. global.json more a guideline than an actual rule. The muxer **silently** ignores global.json (https://github.com/dotnet/core-setup/issues/626), and the global.json format is limited to listing a specific version (https://github.com/dotnet/core-setup/issues/679). There is no way to express "use 2.0.0-*".

**Comment by gkhanna79** [comment] 2017-03-17 16:01
> The muxer silently ignores global.json (#626),

CLI resolution policy does not ignore global.json - it simply ignores an invalid version, specified in global.json, to find the next valid version. The policy, as implemented, is to first look for the version in global.json and if not found, look for stable CLI version and if that is also not found, look for a pre-release CLI version.

**Comment by natemcmaster** [comment] 2017-03-17 16:36
All of that is invisible to the user. There is no console output, warnings, or errors when the global.json version is as invalid format or valid but not installed. Hence, the appearance of dotnet.exe silently ignoring global.json.

**Comment by natemcmaster** [comment] 2017-04-27 00:45
Was this fixed in https://github.com/dotnet/core-setup/pull/2055? I'm not seeing this bug anymore in 2.0.0-preview1-005842

**Comment by livarcocc** [comment] 2017-04-27 02:55
Correct. This was fixed. Closing this issue.

**Closed by livarcocc** 2017-04-27 02:55 UTC
Labels: area-SDK
