### ISSUE TITLE
How to make dotnet use a different runtime?

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#2054] opened 2017-04-13 20:09 UTC
_From @hadibrais on April 13, 2017 19:49_

I have installed on my Linux system precompiled .NET CLI tools version 2.0.0-beta-001776-00. The runtime libraries (libcoreclr.so and libclrjit.so) and the .NET libraries are installed in the default directory. I made some small changes to the CoreCLR (specifically to the JIT) and verified that my runtime is working correctly. However, I wanted dotnet and all other managed CLI tools including the C# compiler to use my runtime. To do this, I backed up the existing libcoreclr.so and libclrjit.so and copied my versions of these files to the following directory:

/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-beta-001776-00

hoping that by running dotnet, it will just use the new runtime. Unfortunately, it emits the following error:

Failed to initialize CoreCLR, HRESULT: 0x80004005

This error is emitted for any command and even `dotnet --help` emits the same error.

How to I get dotnet (and all .NET CLI tools) to use my runtime?

_Copied from original issue: dotnet/cli#6314_

**Comment by livarcocc** [comment] 2017-04-13 20:09
What you are changing is not really the CLI, but rather the runtime. I will move your issue to core-setup.

**Comment by gkhanna79** [comment] 2017-04-14 22:58
CC @ramarag

**Comment by steveharter** [comment] 2018-01-12 20:08
@hadibrais any updates? Is this still an issue?

**Comment by hadibrais** [comment] 2018-01-13 15:22
@steveharter I got involved in some other project, but I'll get back to this issue soon and let you know what happens.

**Comment by hadibrais** [comment] 2018-02-04 02:12
@steveharter Yes, this is still an issue. I'm following the technique discussed [here](https://github.com/hadibrais/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#update-coreclr-from-raw-binary-output). I noticed that `dotnet run` is always loading `System.Private.CoreLib.dll` from the nuget directory:

~/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.0.0/runtimes/linux-x64/native/System.Private.CoreLib.dll

rather than from the `publish` folder. This happens irrespective of whether I'm copying my own version of the runtime to the `publish` folder or leave it as it is. I'm not sure whether I'm doing something wrong or there is a bug somewhere.

I'm able to successfully use my own runtime through `corerun`.

**Comment by Petermarcu** [comment] 2018-02-04 07:18
@hadibrais what happens when you run your application from the publish folder instead of using `dotnet run`? `dotnet run` doesn't run your app the way it would run if it were published. What should work is for your to publish self-contained `dotnet publish --self-contained` and then run the app from the publish folder. If you copy your own runtime into that folder, it should load that one.

**Comment by hadibrais** [comment] 2018-02-04 23:42
@Petermarcu Thanks! It's my fault. I was confused between the DLL file and the native EXE file. When I use `dotnet run`, it is loading the DLL file and using the runtime from the nuget directory. But I should be using the native EXE file, which will correctly load the runtime libraries from the `publish` folder. Now I'm getting this exception:
```
Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'SystemNative_FStat2' in shared library 'System.Native'.
   at Interop.Sys.FStat(SafeFileHandle fd, FileStatus& output)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.Diagnostics.FileVersionInfo.TryLoadManagedAssemblyMetadata()
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at coreapp.Program.Main(String[] args)
```
This is the C# code:

```
﻿using System;
namespace coreapp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var coreAssemblyInfo = System.Diagnostics.FileVersionInfo.GetVersionInfo(typeof(object).Assembly.Location);
Console.WriteLine($"Hello World from Core {coreAssemblyInfo.ProductVersion}");
Console.WriteLine($"The location is {typeof(object).Assembly.Location}");
        }
    }
}
```
Note that it is printing "Hello World!" to the console and then crashing at `GetVersionInfo` because `System.Native` does not have an entry point. What is `System.Native` and why is the entry point missing? Not sure if it matters, I built the CoreCLR with `skipcrossgen`.

One thing that I noticed when using `dotnet` is that the `--configuration` option is case-sensitive and it is the same as the name of the output folder. That is, if I pass `release` or `Release`, the name of the output folder would be `release` or `Release`, respectively. This is not convenient. Ideally, the option should be case-sensitive, but the output folder name should be case-insensitive. The CoreCLR build script `build.sh` doesn't have this issue.

I suggest improving the [documentation](https://github.com/hadibrais/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#update-coreclr-from-raw-binary-output) so that others don't face the same issue. I can do it if you like.

**Comment by Petermarcu** [comment] 2018-02-05 05:01
This is just a guess but there are a core set of files that are very coupled together. You either need to be extra careful that when you build, your source matches the sha that built the binaries that you are updating, or you should update most/all of the binaries that are built from coreclr with your new build.

**Comment by hadibrais** [comment] 2018-02-05 15:39
@Petermarcu I did copy all the CoreCLR binaries of my build to the publish `folder`. `typeof(object).Assembly.Location` should return the direction in which `System.Private.CoreLib.dll` resides. So calling `GetVersionInfo` on it should work. I don't understand why it's picking up a library called `System.Native` instead. I noticed that there is a file called `System.Native.so' in the publish folder. It's obviously a native shared library and so it does not contain a managed entry point. Is there a relation between `System.Private.CoreLib.dll` and `System.Native.so'? Why is the assembly loader looking for an entry point in `System.Native.so' instead of `System.Private.CoreLib.dll`?

**Comment by Petermarcu** [comment] 2018-02-06 03:19
@weshaggard any thoughts?

**Comment by weshaggard** [comment] 2018-02-06 18:24
For better or worse there is some tight coupling between coreclr and corefx. I would suggest staring with a newer version of Microsoft.NETCore.App that more closely aligns with the current builds in master.  Did you get the latest SDK see https://github.com/hadibrais/coreclr/blob/master/Documentation/workflow/UsingYourBuild.md#acquire-the-latest-nightly-net-core-sdk?

**Comment by omajid** [comment] 2018-03-16 21:03
This sort of use case might also be addressed by https://github.com/dotnet/source-build/ once that is working well.

**Comment by hadibrais** [comment] 2018-03-19 02:29
@weshaggard I'm not able to get it working. Is there documentation for that tight coupling so that I can learn more about it?

@omajid Looks interesting. So it's not working well yet?

**Comment by weshaggard** [comment] 2018-03-19 18:59
>@weshaggard I'm not able to get it working. Is there documentation for that tight coupling so that I can learn more about it?

There isn't any documentation exactly, the tight coupling is caused by some assemblies in corefx directly building against System.Private.CoreLib in coreclr and so if those versions aren't close enough between the coreclr and corefx builds you are consuming those things will break. 


>@omajid Looks interesting. So it's not working well yet?

It is still a work in progress.

@hadibrais can you tell me which sha of the coreclr repo you are building and which SDK your project is referencing? 

Have you had a look at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md#advanced-scenario---using-a-nightly-build-of-microsoftnetcoreapp at all? Those steps might help you setup your project to be more closely aligned.

**Comment by sdmaclea** [comment] 2018-08-13 19:59
@hadibrais,  @janvorli uploaded https://github.com/dotnet/source-build/blob/master/scripts/bootstrap/buildbootstrapcli.sh for the purpose of for building the SDK for a new platform.  If you look at the script you can see how he has matched the versions of coreclr, corefx, core-setup to the SDK he is building.

**Comment by vitek-karas** [comment] 2019-01-25 15:10
One possible solution is to use `DOTNET_ROOT` environment variable even for `dotnet.exe` as described in #4915 ,

**Comment by jeffschwMSFT** [comment] 2019-05-10 15:56
Closing out this issue, though if this is still an issue please feel free to let us know or open a new issue.  Thanks for the feedback.

**Closed by jeffschwMSFT** 2019-05-10 15:56 UTC
Labels: area-Host, question
