### ISSUE TITLE
Update to use latest SDK for 2.1 RTW

### ISSUE THREAD

**Issue by steveharter** [dotnet/core-setup#4082] opened 2018-04-26 18:02 UTC
In order to write the version metadata to the framework deps.json fils, core-setup will need to take a newer SDK build that has that functionality once RC has shipped.

The latest [RC build](https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1) does have the functionality to write the version metadata, but core-setup will not (should not) be updated until after RC.

cc @weshaggard @livarcocc @dleeapho 

cc @natemcmaster ASP.NET will need to do this also in order to support roll-forward properly.

See https://github.com/dotnet/corefx/issues/29032

**Comment by natemcmaster** [comment] 2018-04-26 19:17
> ASP.NET will need to do this also in order to support roll-forward properly.

I will try to update our SDK, however, in the event we can't, we should be okay without it, right? This is the first time we're shipping aspnet as a sharedfx, so there is nothing to rollforward from.

cc @muratg

**Comment by muratg** [comment] 2018-04-26 22:06
@Petermarcu FYI

**Comment by Petermarcu** [comment] 2018-04-26 22:32
Yeah, I think 2.2 is when it will be critical. That said I think should all get to the RC sdk.

**Comment by weshaggard** [comment] 2018-04-30 23:30
@Petermarcu is testing this out in master https://github.com/dotnet/core-setup/pull/4106.

**Comment by pakrym** [comment] 2018-05-02 17:32
I don't see why should it be based on assembly version at all. Library (package) versions are enough to resolve to correct dlls in additional deps case.

We updated to new SDK in 2.1 branch and would start producing correct framework and additional deps.

My worry is that we are trying to solve the issue with a feature not intended for this use by enabling it half way.

**Comment by steveharter** [comment] 2018-05-02 18:37
We don't consider the version of a package when there are several references to it (between app, additional-deps and frameworks). The reasons are many, but basically a given assembly can exist in more than one package, so it can't be assumed package versions alone are enough.

So the current conflict resolution uses a combination of what order the deps.json files are processed, whether a minor roll-forward has occurred, and the assemblyVersion and fileVersion attributes.

**Comment by karelz** [comment] 2018-05-02 19:41
@pakrym this is the solution we talked about in meetings - using version numbers conflict resolution (same as is used for roll-forward feature).

**Comment by weshaggard** [comment] 2018-05-04 21:20
SDK has been updated with PR https://github.com/dotnet/core-setup/pull/4115.

**Comment by steveharter** [comment] 2018-05-07 19:57
It appears the current SDK (2.1.300-rc1-008673) in core-setup release/2.1 branch is not generating Microsoft.NETCore.App.deps.json with the version metadata.

cc @dsplaisted; https://github.com/dotnet/sdk/pull/2118

**Comment by dsplaisted** [comment] 2018-05-07 20:30
@steveharter What do I need to do to run a build of core-setup to repro this?  Just run build.cmd from the repo root?

**Comment by steveharter** [comment] 2018-05-07 20:38
@dsplaisted yes running build.cmd from the core-setup command line for release/2.1. Here's a snippet of what I get in msbuild.log regarding the "restore" and "publish" steps:
```
       PublishSharedFrameworkAndSharedHost:
         Directory "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0" doesn't exist. Skipping.
         "D:\git\coresetup17\Tools/dotnetcli/dotnet.exe" restore --source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json --source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json --source D:\git\coresetup17\Bin/win-x64.Debug/packages/ --packages D:\git\coresetup17\Bin/obj/win-x64.Debug\SFP.packages\ /p:OSGroup=Windows_NT /p:PortableBuild=true /p:TargetArchitecture=x64 /p:ConfigurationGroup=Debug /p:VersionSuffix=rtm-26504-0 /p:OutputRid=win-x64 /p:TargetFramework=netcoreapp2.1 /p:RuntimeIdentifier=win-x64 /p:RuntimeFrameworkVersion=2.1.0-rtm-26504-0
           Restoring packages for D:\git\coresetup17\src\sharedFramework\framework\framework.csproj...
           Installing NETStandard.Library 2.0.3.
           Installing Microsoft.NETCore.Targets 2.0.0.
           Installing Microsoft.NETCore.Platforms 2.1.0-rc1-26423-06.
           Installing Microsoft.NETCore.DotNetHostPolicy 2.1.0-rtm-26504-0.
           Installing Microsoft.NETCore.App 2.1.0-rtm-26504-0.
           Installing runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy 2.1.0-rtm-26504-0.
           Installing runtime.win-x64.Microsoft.NETCore.App 2.1.0-rtm-26504-0.
           Generating MSBuild file D:\git\coresetup17\Bin/obj/win-x64.Debug\framework\framework.csproj.nuget.g.props.
           Generating MSBuild file D:\git\coresetup17\Bin/obj/win-x64.Debug\framework\framework.csproj.nuget.g.targets.
           Restore completed in 3.8 sec for D:\git\coresetup17\src\sharedFramework\framework\framework.csproj.
         D:\git\coresetup17\Tools/dotnetcli/dotnet.exe publish --no-restore --output D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0 /p:OSGroup=Windows_NT /p:PortableBuild=true /p:TargetArchitecture=x64 /p:ConfigurationGroup=Debug /p:VersionSuffix=rtm-26504-0 /p:OutputRid=win-x64 /p:TargetFramework=netcoreapp2.1 /p:RuntimeIdentifier=win-x64 /p:RuntimeFrameworkVersion=2.1.0-rtm-26504-0
         Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
         Copyright (C) Microsoft Corporation. All rights reserved.
         
           You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
           framework -> D:\git\coresetup17\Bin\win-x64.Debug\framework\netcoreapp2.1\win-x64\framework.dll
           framework -> D:\git\coresetup17\Bin\obj\win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\
         To delete: D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework;D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.exe;D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.dll;D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.pdb;D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.runtimeconfig.json;D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\apphost.exe;D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\hostfxr.dll
         Deleting file "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.exe".
         Deleting file "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.dll".
         Deleting file "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.pdb".
         Deleting file "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.runtimeconfig.json".
         Deleting file "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\hostfxr.dll".
         Moving file from "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\framework.deps.json" to "D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0\Microsoft.NETCore.App.deps.json".
```

**Comment by dsplaisted** [comment] 2018-05-07 22:35
@steveharter Is there a way I can run just the step of the build that publishes the shared framework, and create a .binlog for that?

**Comment by steveharter** [comment] 2018-05-08 15:47
@dsplaisted to run just the publish:
1) cd to src\sharedFramework\framework
2) Run the publish command that msbuild did. E.g. `D:\git\coresetup17\Tools/dotnetcli/dotnet.exe publish --no-restore --output D:\git\coresetup17\Bin/obj/win-x64.Debug\sharedFrameworkPublish\shared\Microsoft.NETCore.App\2.1.0-rtm-26504-0 /p:OSGroup=Windows_NT /p:PortableBuild=true /p:TargetArchitecture=x64 /p:ConfigurationGroup=Debug /p:VersionSuffix=rtm-26504-0 /p:OutputRid=win-x64 /p:TargetFramework=netcoreapp2.1 /p:RuntimeIdentifier=win-x64 /p:RuntimeFrameworkVersion=2.1.0-rtm-26504-0`

**Comment by steveharter** [comment] 2018-05-08 16:08
@dsplaisted on a separate run of the publish, the version numbers were successfully generated. I'm not yet sure why that worked while the `build` from root didn't.

**Comment by steveharter** [comment] 2018-05-08 17:25
@dsplaisted it appears the env var `IncludeFileVersionsInDependencyFile` is not getting set to `true` when building from root. Can you investigate ASAP please?

**Comment by dsplaisted** [comment] 2018-05-08 17:34
@steveharter Yes, I have been investigating

**Comment by dsplaisted** [comment] 2018-05-08 20:01
@steveharter I think the problem is that core-setup.tasks.dll is still [using version 1.1.1](https://github.com/dotnet/core-setup/blob/release/2.1/tools-local/tasks/core-setup.tasks.csproj#L18) of Microsoft.Extensions.DependencyModel.  This means that when the `ProcessSharedFrameworkDeps` task rewrites the file, it uses an outdated version of the DependencyModel APIs, which don't preserve the new version information.

**Comment by dsplaisted** [comment] 2018-05-08 21:30
Updating the version of Microsoft.Extensions.DependencyModel to 2.1.0-preview2-26306-03 (the same as dotnet/sdk is currently using) fixed the issue.  I'm not sure how well that would work with ProdCon or source build.  Since the code [is in the core-setup repo](https://github.com/dotnet/core-setup/tree/release/2.1/src/managed/Microsoft.Extensions.DependencyModel) anyway, you might want to just replace the `PackageReference` with a `ProjectReference`.

**Comment by steveharter** [comment] 2018-05-09 18:26
Thanks @dsplaisted working on either using a project reference or a package version to DependencyModel

**Comment by steveharter** [comment] 2018-05-09 18:29
@weshaggard is using a project reference in core-setup.tasks to DependencyModel acceptable? 

Here's PRs for master and release/2.1 that do that; they successfully generate the version metadata:
https://github.com/dotnet/core-setup/pull/4135
https://github.com/dotnet/core-setup/pull/4136

**Comment by weshaggard** [comment] 2018-05-09 19:27
We cannot take a project reference to the live project because core-setup.tasks is a pre-step to being able to build the rest of the repo. You can update to a later version of the package though.

**Comment by Petermarcu** [comment] 2018-05-10 18:35
I believe this is done. Can we close this?

**Comment by weshaggard** [comment] 2018-05-10 18:36
I think it would be good to validate the E2E before closing.

**Comment by karelz** [comment] 2018-05-10 21:39
@pakrym can you please help verify the E2E scenario?

**Comment by steveharter** [comment] 2018-05-10 22:05
I don't believe there is a completed build yet with these changes (for either master or release/2.1).

Is that correct @weshaggard?

**Comment by steveharter** [comment] 2018-05-11 13:35
There is now a release/2.1 build available with these changes (Micrososoft.NETCore.App 2.1.0-rtm-26510-03)

**Comment by pakrym** [comment] 2018-05-11 20:38
Verified with 2.1.0-rtm-30771 aspnetcore build on Antares and with my test suite.

**Comment by muratg** [comment] 2018-05-11 20:55
Thanks @pakrym.  @Petermarcu FYI.

**Comment by karelz** [comment] 2018-05-11 20:59
Thank you @pakrym!

**Comment by karelz** [comment] 2018-05-14 19:40
Closing as the SDK was updated & verified in release/2.1 branch

**Closed by karelz** 2018-05-14 19:40 UTC
Labels: area-Infrastructure, blocking-RTM
