### ISSUE TITLE
Symbols for System.Linq missing in .NET Core 3.0

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/core-setup#5058] opened 2019-01-30 03:11 UTC
## Steps to reproduce
 1. Download PerfView from https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md (this only needs to be done once). 
	2. Start data collection by running.  It will ask for elevation (grant it) It should bring up a dialog box that shows that it is collecting data.  
 
	PerfView /merge:false collect 
 
	3. In the razor directory you built previously ( in the above scenario # 28) run  the application by running
 
	dotnet bin\Debug\netcoreapp3.0\razor.dll
 
              It should give some text and the indicate that to stop it Press Control C.   Go ahead and press Control C.
 
	4. Stop PerfView collection by hitting the ‘stop collection’ button in PerfView.  
	5. It will have created a ‘PerfView.etl file that shows in the PerfVIew’s window.   Double click on it to open 
	6. Double click on the ‘CPU Stacks’ view this brings up a dialog box with every process running during the collection.
	7. Select the ‘dotnet’ executable that was running ‘razor.dll’ (The program args are there if needed).    This brings up a viewer.  
	8. The view will have nodes that look like <microsoft.aspnetcore.hosting!?>> that have ? in them (meaning it does not have symbols  Select the <microsoft.aspnetcore.hosting!?>> and press Alt-S (lookup symbols).   Do this for the following DLLs
 
	microsoft.aspnetcore.hosting
	system.private.corelib
	system.linq
 
              Each time you hit ‘Alt-S’ it should resolve the symbols (it may seem like it disappeared because that one node turns into many (which get displayed in sorted order).    If the node does NOT change, then that is an error report it.
              For each of these find one of the resolved nodes (you can use the ‘Find’ box at the top to search for it).   Select the node (which should now have a complete method name in it) and type Alt-D (lookup definition).   It SHOULD open a source code window.  If it does not that is a bug.
## Expected  behavior
a.	microsoft.aspnetcore.hosting
b.	system.private.corelib
c.	system.linq
Symbols can be getting resolved for them.

## Actual behavior
1.	Symbols are getting resolved but Source cannot be reached for
a.	microsoft.aspnetcore.hosting
Failed to type ‘Alt-D’ (lookup definition) (Source could not find a source location for the given Frame.)
 
2.	Symbols are not getting resolved for 
a.     system.private.corelib
![image](https://user-images.githubusercontent.com/33921754/51962793-4d2fff00-249c-11e9-9c8d-ff0d0f435af1.png)
b.	system.linq
 ![image](https://user-images.githubusercontent.com/33921754/51962772-43a69700-249c-11e9-9fdf-3656c2c5edee.png)

## Environment data
D16.0/28526.10(16.0.0 preview 3.0) + CLI\SDK: 3.0.100-preview-010184
![image](https://user-images.githubusercontent.com/33921754/51955697-b5241c80-247f-11e9-9dd3-4be6c23981bb.png)

**Comment by dagood** [comment] 2019-01-31 18:35
Closing as fixed: I followed the instructions and didn't repro, and the reason is known. Details below:

> a.	microsoft.aspnetcore.hosting

Ignoring this one, as it isn't part of this repository.

> b.	system.private.corelib
> c.	system.linq

I ran the scenario locally and confirmed these two work now. I'm able to resolve symbols and view sources.

This scenario was initially tested before release day, and symbols weren't published yet. Symbols were published and are now available.

To make symbols available before release day in the future (so we can test this kind of scenario before a release!) I filed https://github.com/dotnet/core-setup/issues/5056.

**Closed by dagood** 2019-01-31 18:35 UTC
Labels: Triaged, area-Infrastructure
