### ISSUE TITLE
Ubuntu Arm Builds

### ISSUE THREAD

**Issue by olegsavelos** [dotnet/core-setup#2280] opened 2017-05-04 08:02 UTC
There was an Ubuntu arm builds available previously.
Anyone aware of where did they go and when we can have them back ?

**Comment by JensNordenbro** [comment] 2017-05-04 14:41
Also generic linux-arm is missing

**Comment by chcosta** [comment] 2017-05-04 23:24
@gkhanna79 

Our build system underwent some major changes recently.  We are working on bringing back arm support in the next few days.

**Comment by JensNordenbro** [comment] 2017-05-08 18:58
generic linux-arm is back. Do you use the same build @olegsavelos ?

**Comment by olegsavelos** [comment] 2017-05-09 07:41
Generic linux-arm did not work for me , not sure if they even should.
@chcosta any news on when ubuntu builds will be back ?

**Comment by gkhanna79** [comment] 2017-05-09 13:57
@olegsavelos Where did you pickup the linux-arm build from and why didn't it work for you? Can you please share the failure details?

**Comment by olegsavelos** [comment] 2017-05-09 16:56
I have tried "Linux (arm) (for glibc based OS)" on ubuntu 16.04 (32bit)
What i get is "cannot execute binary file: Exec format error"
To be frank i am not sure if it should have worked anyway?
I was using previously available builds and they worked but i was still getting "Segmentation fault" when trying ASPNetCore projects.

**Comment by gkhanna79** [comment] 2017-05-10 02:37
@olegsavelos I presume you are running on Ubuntu Arm32 bit, right?

**Comment by olegsavelos** [comment] 2017-05-10 09:28
@gkhanna79 Armv71 on  Ubuntu 16.04.2 LTS .

**Comment by gkhanna79** [comment] 2017-05-10 15:40
We do build with armv7 HF ABI support (see https://github.com/dotnet/core-setup/blob/786a3f40a17b88eecbfb22e504dd37c607856ffa/cross/arm/toolchain.cmake#L10). What  is the ABI of the binaries on the Ubuntu build? Does it use Soft ABI?

@hqueue @hseok-oh @jyoungyun incase they have anything to add as well.

**Comment by olegsavelos** [comment] 2017-05-10 16:37
its armhf in my case.
This is the output from readelf on dotnet executable 

`root@opiz:/usr/src# readelf -h dotnet
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x40a30b
  Start of program headers:          64 (bytes into file)
  Start of section headers:          401840 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         39
  Section header string table index: 36
`
I would expect it to be ELF32 or ELF64 should be able to work?

**Comment by gkhanna79** [comment] 2017-05-10 18:08
It should be ELF32 unless I am missing something.

Also, the following looks wrong as it is indicative of amd64 binary as opposed to arm32:

`Type: EXEC (Executable file) Machine: Advanced Micro Devices X86-64`

I will take a look at this.

**Comment by JensNordenbro** [comment] 2017-05-10 18:57
@olegsavelos; we have been running generic linux-arm on Yocto. I will try again now that they are back. I havn't tried on ubuntu.

**Comment by olegsavelos** [comment] 2017-05-10 20:02
@JensNordenbro the previous builds was partially working for me too, it the new generic ones that fail.

**Comment by ThadHouse** [comment] 2017-05-11 02:16
Noting that the generic builds currently built are for armhf might be a good idea on the readme just in case people are confused. Also, are there any plans to provide builds for arm-softfp or are those of us that need it going to have to build it ourselves?

**Comment by hqueue** [comment] 2017-05-11 05:06
> Noting that the generic builds currently built are for armhf might be a good idea on the readme just in case people are confused.

I also agree on this, because ABI is usually noted explicitly when distributing binaries for arm. Sometimes filename contains ABI information to help user to infer ABI from filename.

**Comment by hqueue** [comment] 2017-05-11 05:09
> We do build with armv7 HF ABI support (see https://github.com/dotnet/core-setup/blob/786a3f40a17b88eecbfb22e504dd37c607856ffa/cross/arm/toolchain.cmake#L10). What is the ABI of the binaries on the Ubuntu build? Does it use Soft ABI?

@gkhanna79 Previously distributed ubuntu.14.04-arm and ubuntu.16.04-arm binaries are built in `hardfp`. No `softfp` binary has been appeared on the daily build page yet.

**Comment by JensNordenbro** [comment] 2017-05-11 13:07
Same problem!

**Comment by gkhanna79** [comment] 2017-05-11 15:30
I will update the entry in the table to reflect ARMHF in my PR at https://github.com/dotnet/core-setup/pull/2350.

**Comment by gkhanna79** [comment] 2017-05-11 18:48
I have confirmed that the issue is now fixed. Please try https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/2.0.0-preview2-25311-09/dotnet-linux-arm.2.0.0-preview2-25311-09.tar.gz

**Comment by gkhanna79** [comment] 2017-05-11 18:49
@olegsavelos @JensNordenbro Can you use the URL above and confirm it works for you?

**Comment by olegsavelos** [comment] 2017-05-11 18:56
@gkhanna79 Worked for me 🥇 Now just need to figure out to figure out Segmentation Fault when running MVC apps. Any directions i should follow ?

**Comment by gkhanna79** [comment] 2017-05-11 18:58
Excellent - thanks for the confirmation! I will close this issue. 

For the segmentation fault, I would suggest grabbing core dump and share it out the callstack for crash in a new issue.

**Closed by gkhanna79** 2017-05-11 18:58 UTC
Labels: arch-arm32, area-Infrastructure

**Comment by JensNordenbro** [comment] 2017-05-12 11:46
@gkhanna79 - basically now the application starts but only when targeting rid linux-arm explicitly.  (during restore and publish). 
If wanted to create a portable distribution (this worked in preview1) without specifing rid, during restore and publish, in advance, I got an exception :

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 
> 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11
> d50a3a'. The system cannot find the file specified.
>   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetFallbackKeyRe
> positoryEncryptorPair()
>    at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1
>  keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
> ...


This is my csproj: [ridless-restore.csproj](https://github.com/JensNordenbro/support/blob/master/ridlessrestore.csproj)

Is it ok?

**Comment by olegsavelos** [comment] 2017-05-12 12:53
I think you have another system lib still being ELF64
`root@opiz:/usr/src/PublishOutput# readelf -h /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25307-02/libhostpolicy.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x52570
  Start of program headers:          64 (bytes into file)
  Start of section headers:          3700344 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         38
  Section header string table index: 35
`
@JensNordenbro MVC with razor don't work for me, will try without it now.

**Comment by gkhanna79** [comment] 2017-05-12 15:19
> /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview2-25307-02/libhostpolicy.so

You are using an older version of the package that had the problem. Please see the link I shared above (https://github.com/dotnet/core-setup/issues/2280#issuecomment-300882518) - libhostpolicy.so is ELF32 ARM binary.

**Comment by gkhanna79** [comment] 2017-05-12 15:22
> application starts but only when targeting rid linux-arm explicitly

Yes, linux-arm is the only RID that will support this. Infact, in .NET Core 2.0, we will be supporting platform agnostic RIDs (e.g. win-*, linux-*, osx-*).

@eerhardt @livarcocc Does the Preview1 CLI account for portable RIDs only for certain platforms/arch combination or for everything? If the latter, do you know why @JensNordenbro ran into the issue at https://github.com/dotnet/core-setup/issues/2280#issuecomment-301055835?

**Comment by eerhardt** [comment] 2017-05-12 16:01
> Does the Preview1 CLI account for portable RIDs only for certain platforms/arch combination or for everything? 

The CLI doesn't care about what's inside a RID.  You can use any platform/arch combination you can make up.

@JensNordenbro -  I tried restoring your project, but I don't have the right myget feeds.  Can you share with me your NuGet.config?

`Microsoft.Win32.Registry` needs to be referenced explicitly in order to use APIs in it.  I wonder if the ASP.NET package is referencing it correctly or not.

**Comment by olegsavelos** [comment] 2017-05-12 16:13
@gkhanna79 You were right i had wrong build :(
Now when running MVC Razor app i get System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.Registry,
I have added a nuget package but it doesn't seem to work.
@eerhardt Can you shed some more light on how to manually referencing it ?

**Comment by eerhardt** [comment] 2017-05-12 16:57
I'd like to get a repro myself as I think we have a bug somewhere (probably in ASP.NET's packages, but I'm not sure).

Try adding

`<PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0-preview2-25310-01" />`

to your project.

**Comment by olegsavelos** [comment] 2017-05-12 17:10
@eerhardt I get 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'Microsoft.Win32.Registry (>= 4.4.0-preview2-25310-01)' for '.NETCoreApp,Version=v2.0 (ubuntu.16.04-arm)'.				
`

**Comment by eerhardt** [comment] 2017-05-12 17:13
What's your .csproj look like?  You may need a different version of that package.

**Comment by olegsavelos** [comment] 2017-05-12 17:16
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <UserSecretsId>aspnet-WebApplication5-3260EDB6-E9BD-482B-9726-119C53910D71</UserSecretsId>
    <RuntimeIdentifiers>ubuntu.16.04-arm</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="4.4.0-preview1-25305-02" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0-preview1-final" />
  </ItemGroup>

</Project>
```

**Comment by eerhardt** [comment] 2017-05-12 17:20
Sorry - try `4.4.0-preview1-25305-02` for the registry's version.

**Comment by olegsavelos** [comment] 2017-05-12 17:26
That worked, but i don't see the dll being copied when i try to publish the app.

**Comment by eerhardt** [comment] 2017-05-12 17:27
Do you still get the same error at runtime?  Can't find the file?

**Comment by olegsavelos** [comment] 2017-05-12 17:28
Yes, the file is not physically present in published directory so that would be the case ?

**Comment by eerhardt** [comment] 2017-05-12 17:29
Yes, if the file isn't there, I'd expect the same runtime error.

Investigating...

**Comment by JensNordenbro** [comment] 2017-05-12 18:04
@eerhardt : https://github.com/JensNordenbro/support/blob/master/nuget.config

**Comment by eerhardt** [comment] 2017-05-12 18:17
I've opened https://github.com/dotnet/core-setup/issues/2377 for this Win32.Registry issue.  It appears to be a bug in our latest builds.

To work around this, you can manually copy `%USERPROFILE%\.nuget\packages\Microsoft.Win32.Registry\4.4.0-preview1-25305-02\runtimes\unix\lib\netcoreapp2.0\Microsoft.Win32.Registry.dll` to your app's publish directory.

**Comment by olegsavelos** [comment] 2017-05-13 08:01
Still getting error even with the file present at root. The version seem to be looked for is 4.0.0.0?
```
``Unhandled` Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetFallbackKeyRepositoryEncryptorPair()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager..ctor(IOptions`1 keyManagementOptions, IActivator activator, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass17_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.DataProtectionServiceCollectionExtensions.<>c.<AddDataProtectionServices>b__2_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitClosedIEnumerable(ClosedIEnumerableCallSite closedIEnumerableCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass17_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at WebApplication5.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\Dabuzz\Documents\Visual Studio 2017\Projects\WebApplication5\WebApplication5\Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication5.Program.BuildWebHost(String[] args) in C:\Users\Dabuzz\Documents\Visual Studio 2017\Projects\WebApplication5\WebApplication5\Program.cs:line 21
   at WebApplication5.Program.Main(String[] args) in C:\Users\Dabuzz\Documents\Visual Studio 2017\Projects\WebApplication5\WebApplication5\Program.cs:line 17
Aborted
`
```

**Comment by fogbridgegit** [comment] 2017-12-10 20:38
i download dotnet-linux-arm.latest.tar.gz on 12/10 and im getting a 
robot@ev3dev:~/dotnetlinux$ ./dotnet
-bash: ./dotnet: No such file or directory

i installed it in a local directory as well as 
robot@ev3dev:~$ /usr/bin/dotnet/dotnet
-bash: /usr/bin/dotnet/dotnet: No such file or directory

is there some preinstallation i need to install?
i did a sudo apt-get upgrade before trying.


here are some diagnostics from my linux system
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=ev3dev
ID_LIKE=debian
HOME_URL="http://www.ev3dev.org/"
SUPPORT_URL="http://www.ev3dev.org/support"
BUG_REPORT_URL="https://github.com/ev3dev/ev3dev/issues"
robot@ev3dev:~$ cat /etc/debian_version
8.5
robot@ev3dev:~$

robot@ev3dev:~$ lscpu
Architecture:          armv5tejl
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model name:            ARM926EJ-S rev 5 (v5l)

**Comment by fogbridgegit** [comment] 2017-12-11 00:31
i tried hacking around by opening the dotnet executable and saw a path in there.  so i copied one of the sym links in the lib directory so it could match that path and something changed.

now i get a segmentation fault.

the path was in the first few lines of the dotnet exe its: /lib/ld-linux-armhf.so.3
when i put everything back the way it was i get the original

 -bash: ./dotnet: No such file or directory  silent crash.

any ideas?

**Comment by eerhardt** [comment] 2017-12-11 15:40
Can you try running `strace /path/to/dotnet` and reply with the output?  That way we can try to figure out which path it is trying to find that is failing.
