### ISSUE TITLE
Improve output of --info when SDK is not installed

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/core-setup#3358] opened 2017-10-27 23:05 UTC
## Steps to reproduce
dotnet --info on a machine without the SDK installed

## Expected  behavior
Not sure, something users understand. Parallel parts of --info when SDK is installed and possibly also say here that the SDK is not installed (as is done on --version)

## Actual behavior

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

## Environment data

**Comment by steveharter** [comment] 2018-01-10 20:10
Considering this duplicate of https://github.com/dotnet/core-setup/issues/3502

**Closed by steveharter** 2018-01-10 20:10 UTC
Labels: enhancement
