### ISSUE TITLE
Issue installing aspnetcore-store in Ubuntu 18.04

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/core-setup#4134] opened 2018-05-09 10:22 UTC
## Steps to reproduce
in a clean setup of Ubuntu 18.04 after installing .net core I run
`sudo apt-get install aspnetcore-store-2.0.8`

## Expected  behavior
Install aspnetcore-store

## Actual behavior
```
//sudo apt-get install aspnetcore-store-2.0.8
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 aspnetcore-store-2.0.8 : Depends: aspnetcore-store-2.0.7 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

------------------------------------------------------

//sudo apt-get install aspnetcore-store-2.0.7
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 aspnetcore-store-2.0.7 : Depends: aspnetcore-store-2.0.6 but it is not installable
E: Unable to correct problems, you have held broken packages.

------------------------------------------------------

//sudo apt-get install aspnetcore-store-2.0.6
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package aspnetcore-store-2.0.6 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'aspnetcore-store-2.0.6' has no installation candidate

```

When i hit tab-tab in terminal. I only get 2.0.7 and 2.0.8
```
sudo apt-get install aspnetcore-store-2.0.
aspnetcore-store-2.0.7  aspnetcore-store-2.0.8
```

## Environment data

**Comment by Sphinxs** [comment] 2018-05-11 03:48
Same here

**Comment by xrkolovos** [comment] 2018-05-11 06:29
Everyone still in Build?

**Comment by karelz** [comment] 2018-05-11 17:46
@xrkolovos @Sphinxs can you please check if the problem is addressed in .NET Core 2.1? (RC was released on Mon 5/7)
I let @rakeshsinghranchi @leecow to decide what should be done for 2.0.x

**Comment by leecow** [comment] 2018-05-12 16:05
This was fixed Thursday:

```
root@41b7fdd96f6c:~# apt install aspnetcore-store-2.0.8
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  aspnetcore-store-2.0.0 aspnetcore-store-2.0.3 aspnetcore-store-2.0.5 aspnetcore-store-2.0.6 aspnetcore-store-2.0.7
The following NEW packages will be installed:
  aspnetcore-store-2.0.0 aspnetcore-store-2.0.3 aspnetcore-store-2.0.5 aspnetcore-store-2.0.6 aspnetcore-store-2.0.7 aspnetcore-store-2.0.8
0 upgraded, 6 newly installed, 0 to remove and 13 not upgraded.
Need to get 38.2 MB of archives.
After this operation, 128 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

Is your .list pointed at the 18.04 repo?

```
root@41b7fdd96f6c:~# cat /etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
```

**Comment by karelz** [comment] 2018-05-12 17:51
If it was fixed, should we close it until there is evidence the fix was incomplete?

**Comment by Sphinxs** [comment] 2018-05-13 01:46
To me it was fixed, but for some reason after I installed .net these packages `libpng12-0:i386 wine-stable wine-stable-amd64 wine-stable-i386:i386` ' are not more necessary ' ( But I still need them ! ) ... I don't know if is it because .net, but thanks for the support ( :

**Closed** 2018-06-14 16:51 UTC
Labels: area-Setup, bug, os-linux
