### ISSUE TITLE
VS and CLI offline package cache have mismatching SHAs

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#1758] opened 2017-03-16 22:31 UTC
_From @muratg on March 2, 2017 18:39_

When dotnet is first executed after a CLI installation, dotnet uncompresses its offline package cache, and does a restore.  This restore creates a SHA. This SHA is different between dotnet initial installation and Visual Studio restore. 

![image](https://cloud.githubusercontent.com/assets/1808428/23521434/d925ea00-ff33-11e6-9017-565157fc3d6a.png)

_Copied from original issue: dotnet/cli#5897_

**Comment by livarcocc** [comment] 2017-03-16 22:31
@ericstj Would you know why the lzma decompressed nupkgs would differ for the CLI?

**Comment by livarcocc** [comment] 2017-03-16 22:31
_From @ericstj on March 2, 2017 19:27_

Because we reconstruct the nupkg ZIPs from a list of files and the zip implementation is platform specific.    In @muratg's example above the files are the same but their compressed representation is different.

**Comment by livarcocc** [comment] 2017-03-16 22:31
_From @ericstj on March 2, 2017 19:34_

FWIW I did try to get them byte for byte identical in v1 and I believe I had it working assuming the folks who originally packed the nupkg did it with the same zip implementation we used.  But all bets are off if someone used a different implementation (eg: pack with desktop, zip the folder using explorer or winzip, etc).  I'll get the order of entries correct but the zip headers might be different (since they are implementation specific), they may have used a different compression level, etc.

**Comment by livarcocc** [comment] 2017-03-16 22:32
@gkhanna79 we discussed this a few weeks ago and the conclusion we arrived to was that the host should not use these SHA's anymore. Moved this here in case you don't have an issue tracking that already. If you do, just close this one as a dup of it.

**Comment by gkhanna79** [comment] 2017-03-17 03:32
Removing the SHA check would be a breaking change for the servicing releases - are we sure we want to make such a change?

CC @leecow @eerhardt @DamianEdwards @davidfowl @rrelyea

**Comment by gkhanna79** [comment] 2017-03-30 02:14
@eerhardt Thoughts?

**Comment by eerhardt** [comment] 2017-03-30 14:33
We've already removed the SHA check in .NET Core 2.0.  So this isn't a problem moving forward.

The only question is:  Is this issue important enough to ship a servicing fix for 1.0/1.1?  Is it blocking any scenario?

If the issue isn't blocking, I'd say we allow this issue to be fixed in 2.0 (which is already is) and not make any changes in 1.0/1.1.

**Comment by gkhanna79** [comment] 2017-03-30 17:28
> If the issue isn't blocking, I'd say we allow this issue to be fixed in 2.0 (which is already is) and not make any changes in 1.0/1.1.

I concur. I am not aware of it being blocking and making this change will be a feature level change in a servicing branch, something that we should **only** do when warranted.

**Comment by DamianEdwards** [comment] 2017-03-30 18:11
I agree

**Comment by muratg** [comment] 2017-03-31 02:16
+1. If this is already fixed in 2.0, I think this bug can be closed. Thanks folks!

**Comment by gkhanna79** [comment] 2017-03-31 15:32
Closing this per the discussion.

**Closed by gkhanna79** 2017-03-31 15:32 UTC
Labels: Followingup
