### ISSUE TITLE
No source information is in the corehost symbols

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core-setup#3303] opened 2017-10-12 19:55 UTC
## Steps to reproduce
`build -Release` the repo
Using the `dotnet.exe` that was built, run an .NET Core application and debug the native corehost binaries (`dotnet.exe`, `hostfxr`, `hostpolicy`) in VS.

## Expected  behavior
I should be able to load symbols for `dotnet.exe`, `hostfxr.dll`, and `hostpolicy.dll`, and when I double click on a method in the call stack for these assemblies I should be taken to the source code.

## Actual behavior
I can load symbols for these assemblies just fine.  But when I try to jump to source code, I get the error:

`"Source Not Available" - Source information is missing from the debug information for this module`

## Notes
I used a Debug build and it worked just fine.

@dagood @steveharter @weshaggard

**Comment by weshaggard** [comment] 2018-01-18 23:10
@mikem8361 do you think this is an issue of public vs private symbols?

**Comment by mikem8361** [comment] 2018-01-18 23:22
That would mean that our builds generate the stripped symbols for Release builds which I'll have to check.

**Comment by mikem8361** [comment] 2018-01-19 00:12
The release dotnet.exe/dotnet.pdb that I built seems to have valid a pdb and VS seems to be able to stepping dotnet.exe.

    'dotnet.exe' (Win32): Loaded 'C:\ssd\core-setup\Bin\win-x64.Release\corehost\dotnet.exe'. Symbols loaded.

**Comment by tannergooding** [comment] 2018-01-19 00:14
Dupe of https://github.com/dotnet/core-setup/issues/3126

**Comment by mikem8361** [comment] 2018-01-19 00:17
#3126 is about a symbols not being on the symbol server for a released version of dotnet. This bug seems to be about problems when Eric built core-setup himself.

**Closed** 2018-01-19 00:17 UTC
Labels: area-Infrastructure
