### ISSUE TITLE
Unable to install dotnet-sdk on Ubuntu 17.10

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/core-setup#4049] opened 2018-04-19 21:06 UTC
@PabloRioseco commented on [Mon Apr 16 2018](https://github.com/dotnet/core/issues/1450)

I am trying to install dotnet-sdk to then be able to work with Visual Studio Code with dotnet in ubuntu 17.10

S.O.: Ubuntu 17.10 64b
Update: Lastest version.

I am performing the following procedure indicated by: https://www.microsoft.com/net/learn/get-started/linux/ubuntu17-10
but when I'm installed sdk, I get an error when installing dotnet-sdk:

`sudo apt-get install apt-transport-https` 
`sudo apt-get update`

`sudo apt-get install dotnet-sdk-2.1.104`
```
Reading list of packages ... Done
Creating dependency tree
Reading the status information ... Done
Do not can instal some pack. This may mean that
you asked for an impossible situation or, if you are using the distribution
unstable, that some necessary packages have not yet been created or are
They have taken out of «Incoming».
The following information can help resolve the situation:

The following packages have unfulfilled dependencies:
  dotnet-sdk-2.1.104: It depends: dotnet-runtime-2.0.6 but it will not be installed
E: Problems could not be corrected, you have retained broken packages.
```

---

@richlander commented on [Mon Apr 16 2018](https://github.com/dotnet/core/issues/1450#issuecomment-381840589)

PTAL @leecow 

---

@leecow commented on [Tue Apr 17 2018](https://github.com/dotnet/core/issues/1450#issuecomment-382236116)

I've confirmed the 17.10 repo is working correctly and was able to install dotnet-sdk-2.1.104 (we released [2.1.105](https://github.com/dotnet/core/issues/1456) today). It may be that you need to do a little house cleaning. The easiest first step is to `sudo apt-get remove dotnet-host`. This will uninstall the host and all dependencies leaving you in a fairly clean state to try in re-install. 

---

@Mayocampo commented on [Thu Apr 19 2018](https://github.com/dotnet/core/issues/1450#issuecomment-382872419)

Hi @leecow , i have the same issue trying to install 2.1.105. Already executed `sudo apt-get remove dotnet-host` but error still there... What other steps can we follow to install core 2.0 ?

(i´m doing this process in order to install JetBrains Rider)... By the way, i'm using Linux Mint Sylvia (so, i suppose that instructions for Ubuntu 17 works seamlessly)

---

@Mayocampo commented on [Thu Apr 19 2018](https://github.com/dotnet/core/issues/1450#issuecomment-382874870)

Followed instructions here
[https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.7-download.md](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.7-download.md)

And still not working

![screenshot-2018-04-19 15-42-24](https://user-images.githubusercontent.com/22798602/39017297-814f79d6-43e8-11e8-82e4-5421f029c0dc.png)

---

@Mayocampo commented on [Thu Apr 19 2018](https://github.com/dotnet/core/issues/1450#issuecomment-382877209)

Also tried to install only dotnet-runtime-2.0.7 and get this error

```
may@maylinux ~ $ sudo apt-get install dotnet-runtime-2.0.7
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 dotnet-runtime-2.0.7 : Depende: libgssapi-krb5-2 (>= 1.14+dfsg) pero 1.13.2+dfsg-5ubuntu2 va a ser instalado
                        Depende: libicu57 pero no es instalable
                        Depende: dotnet-hostfxr-2.0.7 pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
```
So, in english it says that: 
2.0.7 depends on libgssapi-krb5-2 (>= 1.14+dfsg) but 1.13.2+dfsg-5ubuntu2 will be installed
2.0.7 depends on libicu57 but it's not installable (?)
2.07 depends on  dotnet-hostfxr-2.0.7 but it will be not installed...

So.... whats happening here?

**Comment by steveharter** [comment] 2018-04-19 22:38
@leecow are there special steps needed for libicu57?

**Comment by leecow** [comment] 2018-04-20 21:05
A 'generic' 17.10 install should already have libicu57 installed. If not, `apt install libicu57` will do the trick. Hopefully this will be fully ironed out once 17.10 packages are building for the 2.0 release branch. 

/cc @ianhays

**Comment by janni2** [comment] 2018-04-23 12:27
Can confirm with Ubuntu/Mate bionic + MS Repo https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod / artful
That when using "Synaptic Package Manager":
- mark dotnet-sdk-2.1.4 -> broken (due to unresolved dependency to dotnet-runtime-2.0.5)
- mark dotnet-runtime-2.0.5 leads to a green dotnet-sdk-2.1.4 but is broken itself
- selecting libcurl3 removes libcurl4 and SEVERAL dependencies of that like virtualbox, cmake, sagemath :-o
- so I'd guess libcurl is the blocker issue, maybe someone could reproduce this
(The Package Manager shows an error at 1st apply click, just retry when everything is green)

**Comment by fafg** [comment] 2018-04-29 18:38
same to me in xubuntu 18.04

![image](https://user-images.githubusercontent.com/9274235/39409765-d6f41aa0-4be4-11e8-8ece-6ffe382b88aa.png)

**Comment by fafg** [comment] 2018-04-29 19:58
```shellscript
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main" > /etc/apt/sources.list.d/dotnetdev.list'

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.105
```
what I did, from the ubuntu 16 version to 17 the only thing that changes is xenial to artful, and the pattern keep to 18 version to ubuntu, so just change from artful to bionic.

cheers.

**Comment by leecow** [comment] 2018-04-30 23:02
18.04 feed registration info has been added to the [2.0.7 release notes](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.7-download.md) and will make it to dot.net in the next day or so.

**Comment by jaronaz** [comment] 2018-05-07 19:42
was running into this also on ubuntu 16.04, but the solution from @fafg works!

**Comment by ru-sh** [comment] 2018-05-08 21:15
Linux Mint 18.3

```
ruslan-N550JK ~ # apt-get install dotnet-sdk-2.1.105
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1.105 : Depends: dotnet-runtime-2.0.7 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by leoplouvier** [comment] 2018-05-24 16:12
Hi ! I have the same issue on Ubuntu 17.10 installed today on an Azure VM. Is there any work arround ?
Is it possible to install it without the package manager ?

**Comment by CumpsD** [comment] 2018-06-14 21:15
````
 cumpsd   master S:2 U:2  ~/.dotfiles  sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.0) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

 cumpsd   master S:2 U:2  ~/.dotfiles  100  sudo apt-get install dotnet-runtime-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.1 : Depends: dotnet-runtime-deps-2.1 (>= 2.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

 cumpsd   master S:2 U:2  ~/.dotfiles  100  sudo apt-get install dotnet-runtime-deps-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.1 : Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.

 cumpsd   master S:2 U:2  ~/.dotfiles  100  sudo apt-get install libicu57
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libicu57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu57' has no installation candidate

 cumpsd   master S:2 U:2  ~/.dotfiles  100 
```

**Comment by CumpsD** [comment] 2018-06-14 21:29
For reference, I have `libicu55` which comes with Xenial. 57 is not available on Xenial, only starting at Artful.

`libicu55 is already the newest version (55.1-7ubuntu0.4).`

**Comment by Chemik27** [comment] 2018-06-18 20:36
Depends: libicu60 but it is not installable :(

**Comment by CumpsD** [comment] 2018-06-23 21:09
I've cleaned house, reinstalled WSL and now it's fine

**Comment by rgreenblatt** [comment] 2018-07-12 06:58
@Chemik27 I had the same problem. @fafg specifically put the commands for bionic (ubuntu 18.04). To fix this just disable/remove the ppa (https://packages.microsoft.com/ubuntu .... with bionic) and run `sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-CODENAMEHERE-prod CODENAMEHERE main" > /etc/apt/sources.list.d/dotnetdev.list' replacing `CODENAMEHERE` with the code name of your OS (xenial for 16.04). This is the same command @fafg put, just with CODENAMEHERE subbed in. Then just run `sudo apt-get update` and everything should work.

**Comment by blackrek** [comment] 2018-07-31 10:37
i had similar problem for 18.04
in my case had errors:
`The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.2) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.2) but it is not going to be installed
`
at the end of the chain libicu60 requires for me
try use my comment [https://github.com/dotnet/core-setup/issues/4247#issuecomment-409174218](url)

just install the required version of libicu

**Comment by alansav** [comment] 2018-08-06 14:05
I had this issue and found I didn't have the universe repo in my sources.list. You can add this using the following:

```
sudo add-apt-repository universe
sudo apt-get update

**Comment by felixlindemann** [comment] 2018-08-28 19:41
thanks @alansav!
I also had to open several ports on our firewall. So I allowed the ports 42622 - 42640 targeting the external IP 13.80.10.205 on port 11371
 
And here is my final script putting it all together.
``` 
sudo add-apt-repository universe
sudo apt-get update

sudo apt-key adv --keyserver packages.microsoft.com --recv-keys EB3E94ADBE1229CF 
sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main" > /etc/apt/sources.list.d/dotnetdev.list'  
sudo apt-get update 
sudo apt-get install apt-transport-https

sudo apt-get install aspnetcore-runtime-2.1
sudo apt-get update

sudo apt-get install dotnet-sdk-2.1 
```

**Comment by xarxziux** [comment] 2018-08-29 18:36
I ran into the same problem trying to install it on Linux Mint 18.3.  The above instructions didn't work.

Instead I downloaded the libicu60 deb directly from [here](https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libicu60_60.2-3ubuntu3_amd64.deb.html), installed it manually and then installed the SDK.  That appears to have fixed it for me.

**Comment by propriusnz** [comment] 2018-08-30 05:47
I think I've found the solution. I'm using version 16.04, and followed this link: [linux prerequisites](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x). After installing several required packages, I'm able to install dotnet-sdk-2.1 on my Linux.

**Comment by technoobs** [comment] 2018-08-30 05:52
I think I've found the solution. I'm using version 16.04, and followed this link: [linux prerequisites](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x) After installing several required packages, I'm able to install dotnet-sdk-2.1 on my Linux.

**Comment by ivaylo5ev** [comment] 2018-10-05 15:52
I am having the same issue on Debian 9.5 testing. The cause is that `dotnet-runtime-deps` relies on the `libicu57` package which is no longer available for newer versions of linux (like Debian 9, Ubunty 17 and so on). The package itself uses versioning approach that puts the version in the package name. This causes deb package version ranges for dependent packages not to work and systems without this package available will fail to install. 

A way to solve that was to manually install the libicu57 package (for Debian you can get it for older debian releases from here: https://packages.debian.org/stretch/amd64/libicu57/download). Then once downloaded use `sudo dpkg -i [path-to-package]` command to install it. I got my `dotnet-sdk-2.1` working after doing this.

**Comment by gatsbys** [comment] 2019-01-06 03:50
Here do you have all the icu stuff to download the deb packages : http://security.ubuntu.com/ubuntu/pool/main/i/icu/

after select yours you need to download it (this is for net core 2.2) : wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3_amd64.deb -P /tmp/

And then just install it : sudo dpkg -i /tmp/libicu60_60.2-3ubuntu3_amd64.deb .

Then you can follow the Net core 2.2 installation from Microsoft.

**Comment by Dan240598** [comment] 2019-02-17 07:42
Try doing this:

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list

Then this:

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1.105

**Comment by stoufa06** [comment] 2019-04-02 20:22
> Here do you have all the icu stuff to download the deb packages : http://security.ubuntu.com/ubuntu/pool/main/i/icu/
> 
> after select yours you need to download it (this is for net core 2.2) : wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3_amd64.deb -P /tmp/
> 
> And then just install it : sudo dpkg -i /tmp/libicu60_60.2-3ubuntu3_amd64.deb .
> 
> Then you can follow the Net core 2.2 installation from Microsoft.

I have downloaded the package and worked for me

**Comment by Juzwa** [comment] 2019-05-25 12:44
> @Chemik27 I had the same problem. @fafg specifically put the commands for bionic (ubuntu 18.04). To fix this just disable/remove the ppa (https://packages.microsoft.com/ubuntu/18.04/prod or https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod) and run `sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-CODENAMEHERE-prod CODENAMEHERE main" > /etc/apt/sources.list.d/dotnetdev.list'` replacing `CODENAMEHERE` with the code name of your OS (xenial for 16.04). This is the same command @fafg put, just with `CODENAMEHERE` subbed in. Then just run `sudo apt-get update` and everything should work.

Worked for Pop!_OS ubuntu 19.04 (disco). Big thanks!

**Comment by locpv-ibl** [comment] 2019-06-05 11:14
```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg  

sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'  

sudo apt-get update

sudo apt-get install dotnet-sdk-2.2
```
You're welcome!

**Comment by depeter** [comment] 2019-06-05 11:50
Managed to manually install the libicu55 manually by doing this: 

    wget https://mirrors.edge.kernel.org/ubuntu/pool/main/i/icu/libicu55_55.1-7_amd64.deb

and then installing it like this:

    dpkg -i libicu55*.deb


After that I can run the command:

   apt-get install dotnet-sdk-2.2

**Comment by dagood** [comment] 2019-06-05 18:34
We have a change planned for July (date may change) that should fix the root problem here:
"Use OR ('|') dependencies for Debian packages for libicu## dependencies #5812"

Basically, once that's released, as long as your distro provides *any* known version of `libicu##`, our packages will install. You won't need to make sure you get the exact right Microsoft repository set up, or manually grab the specific version that fulfills the dependency.

At the moment, the list of accepted `libicu` versions will be 63, 60, 57, 55, and 52. Please let me know if your preferred distro/release uses a different one!

I'm closing this issue because it's addressed by https://github.com/dotnet/core-setup/issues/5812. Thanks everyone for contributing workarounds and fixes for the problem!

**Closed by dagood** 2019-06-05 18:34 UTC
Labels: area-Setup
