### ISSUE TITLE
Self-contained application won't start because dotnet.exe is missing

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/core-setup#1564] opened 2017-02-19 01:36 UTC
## Steps to reproduce
Create a project with `dotnet new console`

Change the .csproj to this:
````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DebugType>portable</DebugType>
    <OutputType>Exe</OutputType>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="2.0.0-beta-25015-04" />
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="2.0.0-beta-001581-00" />
    <PackageReference Include="System.Console" Version="4.4.0-beta-24913-02" />
  </ItemGroup>

</Project>
````

This .csproj results in a published application that doesn't contain some assemblies it doesn't need. The resulting application is 25MB instead of almost 50MB.

Restore and publish the application
`dotnet restore -r <RID>`
`dotnet publish -c release -r <RID>`

Run the resulting executable
## Expected  behavior
The program outputs `Hello World!`

## Actual behavior
A message similar to `Error: assembly specified in the dependencies manifest was not found -- package: 'runtime.win7-x64.microsoft.netcore.dotnethost', version: '2.0.0-beta-001581-00', path: 'runtimes/win7-x64/native/dotnet.exe'`

This happens on both Windows and Linux.

You can create the same reduced-size application with netcoreapp1.1 by modifying the above .csproj's package versions to 1.1.0, 1.1.0, and 4.3.0 respectively. The issue doesn't occur when doing this.

## Workaround
`touch dotnet.exe`
The application now works as expected

## Environment data
```
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by gkhanna79** [comment] 2017-02-19 02:13
@piotrpMSFT @livarcocc Can you please take the first look at this publishing issue?

**Comment by livarcocc** [comment] 2017-02-19 19:45
@Thealexbarney You are using `<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>` but then you are not adding Microsoft.NetCore.App to your `PackageReferences`.

When you disable the implicit framework, M.NC.App does not get automatically referenced for you. That's why you are missing so many things.

**Comment by Thealexbarney** [comment] 2017-02-19 20:32
I'm doing what's described [here](https://github.com/dotnet/docs/blob/16d7af196144ed0ec97eb1a438646bedcea45c2d/docs/core/preview3/deploying/index.md#deploying-a-self-contained-deployment-with-a-smaller-footprint) by replacing the Microsoft.NetCore.App reference with only the needed dependencies. 

I don't completely know how dependencies are resolved at runtime, but it appears that that it's looking for `dotnet.exe` even after it was renamed to `$assemblyName.exe` during publishing. The application launches just fine after creating a dummy dotnet.exe. Is this possibly caused by the changes that come from Microsoft.NetCore.App 2.0.0 now containing the entire runtime instead of being a metapackage?

**Comment by Petermarcu** [comment] 2017-02-20 03:41
I think this is because in 2.0, the granular packages aren't there anymore. 

@ericstj can confirm. In 2.0, you can only reference the platform and we're coming up with a different way of making sure your application is as small as possible that doesn't require that you manange such granular references.

@richlander @russellhadley , Looks like apps that followed the docs [here](https://github.com/dotnet/docs/blob/16d7af196144ed0ec97eb1a438646bedcea45c2d/docs/core/preview3/deploying/index.md#deploying-a-self-contained-deployment-with-a-smaller-footprint) are going to not publish properly on 2.0. They will then have to go reference all of netcoreapp2.0 and will have a regression in app size from what they worked hard to achieve in 1.1. 

We should talk about options here in 2.0.

@Thealexbarney , for now, I'd go back to the coarse reference of Microsoft.NetCore.App on 2.0 for now.

**Comment by richlander** [comment] 2017-03-08 04:20
@Petermarcu  In general, that makes sense to me as the reason.

I think we're going to need to start a 2.0 branch for docs for some of this before long (like next month). That's a little bizarre given that we just merged over the csproj content, replacing the previous p.j content today.

@blackdwarf For now, I suggest you make a note in the current doc to cover this case. Other ideas?

**Comment by ericstj** [comment] 2017-03-28 15:38
> @ericstj can confirm. In 2.0, you can only reference the platform and we're coming up with a different way of making sure your application is as small as possible that doesn't require that you manange such granular references.

That is correct.  We no longer have the granular System.* references.  Instead just build the self-contained app in the normal way (not bothering with dependencies) then you can enable trimming as described here: https://github.com/dotnet/standard/blob/master/Microsoft.Packaging.Tools/docs/trimming.md.

@blackdwarf can you update the docs?

**Comment by Thealexbarney** [comment] 2017-03-28 15:45
@ericstj Should issues with trimming be reported, or is trimming just not completely implemented yet? I tried it out, and had issues with transitive project dependencies being trimmed when they're actually needed.

**Comment by ericstj** [comment] 2017-03-28 16:19
@Thealexbarney go ahead and file an issue in the standard repo on that if it is a bug.

Here's some relevant info we'd want to know.
Was NuGet package C actually used? (eg: did A or B use types in C)
Was Project B actually used?  (eg: did A use types in B)

Even better would be an isolated repro.

To workaround, in project A you can specify <TrimFilesRootPackages Include="C" /> and that will explicitly root package C, but I'd like to understand why it was trimmed.  

Thanks!

**Comment by Thealexbarney** [comment] 2017-03-28 19:39
@ericstj Well, I tried to reproduce the issue, but it wouldn't even make it to managed code before getting an error, so I filed that issue instead: dotnet/standard#264

**Comment by mairaw** [comment] 2017-03-28 21:52
@ericstj I haven't followed this thread closely, but can you please open an issue at https://github.com/dotnet/docs and work with @GuardRex on the updates needed?

**Comment by gkhanna79** [comment] 2017-04-14 17:50
@ericstj Is there anything actionable on this?

**Comment by ericstj** [comment] 2017-04-14 19:12
@Thealexbarney and I worked out a couple issues with trimming.  I believe this is working now.  If not please open a new issue.

**Closed by ericstj** 2017-04-14 19:12 UTC
