### ISSUE TITLE
Unsigned files in the shared framework

### ISSUE THREAD

**Issue by livarcocc** [dotnet/core-setup#1801] opened 2017-03-21 20:07 UTC
\2.0.0-beta-001808-00\mscorlib.dll NotSigned
\2.0.0-beta-001808-00\netstandard.dll NotSigned
\2.0.0-beta-001808-00\SOS.NETCore.dll NotSigned
\2.0.0-beta-001808-00\System.dll NotSigned

Guys, I found these unsigned files in the shared framework. Any reason why they are not being signed?

@gkhanna79 @Petermarcu @eerhardt

**Comment by gkhanna79** [comment] 2017-03-21 20:12
These files should be getting signed and must be getting signed until recently (else this would have come up earlier).

@dagood @chcosta Do you know why these maybe getting dropped?

**Comment by gkhanna79** [comment] 2017-03-21 20:17
@chcosta I am assigning this to you take a look. Looking at https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=627451&_a=summary, for example, the signing step is green even though the `MicroBuild.Plugins.Signing.Targets` is having a red cross next to it.

**Comment by chcosta** [comment] 2017-03-21 20:29
I would suspect this change - https://github.com/dotnet/core-setup/commit/3573ecb82607fabdda104722d8df32c00263892a

I can prepare a fix.

**Comment by chcosta** [comment] 2017-03-21 21:58
I've merged a fix for this.  I'll take a look at tomorrow's packages to see if the listed binaries are getting signed.

**Comment by chcosta** [comment] 2017-03-22 00:28
mscorlib.dll, netstandard.dll, and System.dll now appear to be test signed.  @dagood , @crummel , do you know the magic to fix this sot hey get real signed?

**Comment by dagood** [comment] 2017-03-22 14:36
I don't have any ideas. The build step's logs say that they're being submitted for real signing and it seems to succeed, but even remoting into the machine (in case the wrong thing got packaged) shows them being test signed. I don't know what's responsible for printing the "for Real signing" message, so I don't know if something's being misrepresented.

**Comment by chcosta** [comment] 2017-03-22 20:09
https://github.com/dotnet/corefx/pull/17398

**Comment by gkhanna79** [comment] 2017-03-22 20:11
> \2.0.0-beta-001808-00\SOS.NETCore.dll NotSigned

@chcosta This file comes from CoreCLR. Do you need to make a similar change there as well?

**Comment by chcosta** [comment] 2017-03-22 20:16
That file appears to be signed.  Can you provide a specific instance where it's not so that I can investigate further?

**Comment by chcosta** [comment] 2017-03-22 20:26
The Microsoft.NETCore.App package contains signed binaries (or will after dotnet/corefx#17398 is merged and consumed in Core-setup).  Looking at the zips, the binaries there do not appear to be signed, which is somewhat surprising to me.

**Comment by gkhanna79** [comment] 2017-03-22 20:28
SOS.NETCore is listed at the start of this thread as unsigned and hence, I brought it up. If it is indeed signed, then I am wondering why @livarcocc came across it as unsigned - do you know?

**Comment by chcosta** [comment] 2017-03-22 23:08
The zips contains crossgen'd binaries which don't get strong-name signed again.  The CoreFx fix should address the signing issue initially reported.  We can close this issue once Core-Setup gets updated to consume the signed CoreFx binaries.

**Comment by chcosta** [comment] 2017-03-23 16:43
@livarcocc , can you provide a link to the package which had an unsigned SOS.NETCore.dll?  I looked at the contents of this package and it appeared to be fine - https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win7-x64.Microsoft.NETCore.App/2.0.0-beta-001808-00

**Comment by chcosta** [comment] 2017-03-31 21:58
I haven't heard anything further on this.  I believe that the issue is fixed (though cli may not have picke dup a newere version of core-setup yet).  Please feel free to reopen if necessary.

**Comment by chcosta** [comment] 2017-04-27 22:34
@mikem8361 as an FYI

**Comment by danmosemsft** [comment] 2017-04-28 16:29
Assigning to @crummel per @gkhanna79 
@crummel let us know if this isn't on track for 5/10 - thanks!

**Comment by gkhanna79** [comment] 2017-04-29 16:00
@crummel Can you please port https://github.com/dotnet/core-setup/pull/2221 to master and release/2.0.0 branches as well?

**Comment by chcosta** [comment] 2017-04-29 19:00
This should be fixed in master https://github.com/dotnet/core-setup/commit/af172161bc0eb9926a0ed9cdc1464e98db8f239d#diff-11b08ec15f36de5e99accd1d8d60e578, it doesn't appear that this was regressed with the buildtools change.

Please do double check

**Comment by gkhanna79** [comment] 2017-04-29 19:59
clrcompression.dll seems to be missing in the commit you linked about @chcosta

**Comment by chcosta** [comment] 2017-04-29 21:53
That's fair. I was under the impression that this was related to  the recent SOS.Netcore.Dll discussion. Carry on

**Comment by chcosta** [comment] 2017-04-30 01:21
clrcompression is authenticode signed in CoreFx.  Nothing which happens in Core-Setup invalidates the certification.  I think this is a redundant operation.  I'm not certain that it hurts anything, it would seem to be a no op

**Comment by eerhardt** [comment] 2017-05-11 18:12
@chcosta @crummel - Is this still an issue?  Can it be closed?

**Comment by chcosta** [comment] 2017-05-17 18:58
I'm going to be validate our binaries and ensure they are all signed correctly later this week.

**Comment by gkhanna79** [comment] 2017-05-19 06:09
@chcosta Should this be closed since you will be using https://github.com/dotnet/core-setup/issues/2199 to validate signing?

**Comment by chcosta** [comment] 2017-05-19 15:33
sounds reasonable.  I'm hoping to get some results today.

**Closed by chcosta** 2017-05-19 15:33 UTC
Labels: area-Infrastructure
