### ISSUE TITLE
Having trouble in Ubuntu 18.04 installing dotnet

### ISSUE THREAD

**Issue by theinterestingstory** [dotnet/core-setup#7778] opened 2019-08-21 01:05 UTC
## Steps to reproduce

Following the instruction for 18.04 Ubuntu on this page: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

## Expected  behavior

To be able to install dotnet.

## Actual behavior

```
Get:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66.6 kB]                    
Err:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 40.76.35.62 443]
  Hashes of expected file:
   - Filesize:66619 [weak]
   - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
   - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
   - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
   - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
Fetched 255 kB in 1s (173 kB/s)                           
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 40.76.35.62 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
E: Some index files failed to download. 
```

I think the repo may be messed up? Or maybe it's me? I don't know.

**Comment by dagood** [comment] 2019-08-21 02:20
Not just you. 😞 Thanks for filing the issue.

@leecow, looks like the hash mismatch issue is happening again. Can you ping the repo admins?

/cc @dleeapho

**Comment by nbns** [comment] 2019-08-21 06:42
kde neon. the same issue when update system

```
Get:16 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66,6 kB]                                                     
Err:16 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages                            
  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
  Hashes of expected file:
   - Filesize:66619 [weak]
   - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
   - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
   - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
   - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
Hit:17 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease                                                                      
Hit:18 http://ppa.launchpad.net/libreoffice/ppa/ubuntu bionic InRelease                                                                           
Hit:19 http://ppa.launchpad.net/papirus/hardcode-tray/ubuntu bionic InRelease                                                                     
Hit:20 http://ppa.launchpad.net/papirus/papirus/ubuntu bionic InRelease                                                                                                                             
Fetched 245 kB in 9s (28,5 kB/s)                                                                                                                  
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.80.10.205 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by dagood** [comment] 2019-08-21 15:11
I sent the repo admins a high-pri mail about this issue, we will hopefully have more info soon.

(There are backlinks, but note that this is also being discussed and tracked at https://github.com/dotnet/core/issues/3221, and that's where most people will probably look first.)

**Comment by mdee77** [comment] 2019-08-21 15:13
same for me. waiting for a fix.

**Comment by marcwittke** [comment] 2019-08-21 15:40
it's working for me now

**Comment by herebebeasties** [comment] 2019-08-21 15:45
@dagood This is a recurring issue. See at least:
 * microsoft/vscode#41094
 * microsoft/vscode#45868
 * dotnet/core#2608
 * dotnet/core#3221
 * microsoft/msphpsql#938

Any chance of some proper root cause analysis and fix for this?

(And jeez, everyone please stop adding "me too" comment spam to things. Eighteen thousand copies of the same error message is really unhelpful for the signal-to-noise ratio in tickets like this.)

**Comment by dagood** [comment] 2019-08-21 15:49
The repo owners confirmed they've fixed this now.

@herebebeasties I would like that, I'll see what info I can post over at https://github.com/dotnet/core/issues/2731 where this question has also come up.

**Closed by dagood** 2019-08-21 15:49 UTC
Labels: area-Setup
