### ISSUE TITLE
Dotnet core installed through snap - cannot run global tools

### ISSUE THREAD

**Issue by stefando** [dotnet/core-setup#4664] opened 2018-10-15 23:11 UTC
## Steps to reproduce

Ubuntu 18.04, installed dotnet core through snap.
```
>dotnet-sdk.dotnet tool install -g  dotnet-outdated
>dotnet-sdk.dotnet tool list -g
Package Id           Version      Commands       
-------------------------------------------------
dotnet-outdated      2.0.0        dotnet-outdated

>dotnet-sdk.dotnet outdated
No executable found matching command "dotnet-outdated"
```

## Environment data
```
>snap list
Name        Version    Rev   Tracking  Publisher    Notes
core        16-2.35.2  5548  stable    canonical✓   core
dotnet-sdk  2.1.403    23    stable    dotnetcore✓  classic

```

**Comment by jeffschwMSFT** [comment] 2018-10-16 15:32
cc @leecow

**Comment by leecow** [comment] 2018-10-16 17:48
Global tools are invoked directly rather than through `dotnet`. That said, it still doesn't work. I just gave it a go and it segfaults. Will need to work with @livarcocc to determine what's going on in this environment.

**Comment by jkotas** [comment] 2019-02-16 04:07
Duplicate of #5186. #5186 has a more details about the crash.

@stefando :beers: !

**Closed** 2019-02-16 04:26 UTC
Labels: area-SDK, area-Snaps
