### ISSUE TITLE
Why is the rc4 SDK package size over double compared to preview3?

### ISSUE THREAD

**Issue by am11** [dotnet/core-setup#1590] opened 2017-02-26 02:41 UTC
The size of https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003223/dotnet-dev-centos-x64.1.0.0-preview3-003223.tar.gz is 49.4 MB

whereas https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-rc4-004911/dotnet-dev-centos-x64.1.0.0-rc4-004911.tar.gz is 123 MB

Is it by design or the packaging error?

**Comment by Petermarcu** [comment] 2017-02-26 16:41
This is by design. The SDK grew in size for two reasons with the goal being that you only have to download one thing to do the majority of your work with 1.X.

1. It delivers you a 1.0 and a 1.1 runtime so you can develop against both LTS and Current
2. It delivers a larger NuGet cache including more of ASP.NET so you can do offline ASP.NET development and don't have to go to NuGet for any of the templates if you run `dotnet new mvc` for example.

In 2.0, we're looking at ways to make it a little smaller again. Feedback? Did you notice and wondered if it was a bug or was there something about it getting larger that created problems for you downstream?

**Comment by am11** [comment] 2017-02-26 18:27
@Petermarcu, thanks for your detailed reply!

Actually I was preparing a PR for CoreRT, to update to .NET Core 1.1 and realized that the runtime download time has significantly increased during the build tools init.

Is there a way to compose a smaller bundle, with specific needs? For example, CoreRT needs a bug fix in 1.1 runtime to be able to run on CentOS7 etc. or generally any Linux Kernel 4.6+. Thus the CoreRT CI jobs do not require 1.0 runtime at all, and yet they will waste the network resource of pulling the unrequired bits.

**Comment by MichalStrehovsky** [comment] 2017-02-26 19:00
+1 on the smaller bundles. US is a country where internet speeds below 25 MBit/second [can't even be called broadband anymore](http://www.nbcnews.com/tech/internet/faster-internet-fcc-sets-new-definition-broadband-speeds-n296276), but there are plenty of regions where less is the norm. Pay for play download sizes would be nice.

**Comment by Petermarcu** [comment] 2017-02-26 20:18
I've been looking at other CI times as well and this did significantly increase the overall time not just for download but also extraction. Yes there is a way to have something smaller for CI if you don't want everything. We should figure out a way to create that for our engineering system and any other engineering system that:

1. Knows the version of the runtime they need.
2. Does want or need the NuGet cache that is provided.

Should be a lot smaller and would shave nearly 30 seconds of every CI build, official build, clone, etc. The key will be that its for people that know what they are doing and probably won't be the thing we advertise to everyone. The easy path is to get everything you need to get started. The optimized paths will be for specific scenarios for more advanced users.

**Comment by Petermarcu** [comment] 2017-02-26 20:31
@dleeapho This is an interesting toolset conversation. The SDK that we should be using for our CI should be optimized to not have multiple runtimes, a NuGet cache, or any upstack components that are not needed.

**Comment by Petermarcu** [comment] 2017-02-26 20:48
One thing to note, I believe there is a problem with getting rid of the duplicate runtimes in 1.X because some tools bind against 1.0 and some against 1.1. I think dotnet test is still 1.0.

@am11 , is there a reason you can't use the 2.0 SDK? It still has duplicate runtimes but I'm guessing thats where the fixes will go. https://github.com/dotnet/cli/tree/master

Just with a quick experiment deleting things I know we would never need in our CI/Build, I was able to get the download size down to 32MB from 123MB.

**Comment by am11** [comment] 2017-02-26 20:57
There are some known package bundling techniques which Linux distributions use. For example, CentOS offers `minimal`, `everything` and `live` options.

.NET Core can probably have same kind of stepped-approach for most common scenarios:

Minimum == { AllCoreCLR, AllCoreFX }
Everything == { Minimum, AllASPNET }
EverythingWithALegacyGeneration = { Everythingv_vLatest, Everythingv_vLatest-1 }

and so on.

More generally, a general purpose fancy ML-aided solution could be; the download service at NuGet servers can allocate finite slots for dynamic bundles in storage. The download service then start observing the frequency of entire dependency graph and based on the demand, save cached bundles in blob storage if:

* demand of this exact recipe in past 30 days is too high and there is an empty slot
* in case no slot is left and the demand of certain recipe exceeded the frequency of existing occupancy, retire the existing bundle in favor of the new one

The WebAPI could also notify the nuget.exe utility whether or not it hit the cache. Additionally, would be epic if consumers can configure their own storage and/or CDN so there is no excessive burden on Azure servers (dotnet / nuget subscription)

**Comment by am11** [comment] 2017-02-26 20:58
@Petermarcu, I will try with 2.0. Thanks for the tip.

**Comment by Petermarcu** [comment] 2017-02-26 21:03
Interesting insight with the Centos example. I'll take a closer look at that. Making the NuGet server smarter is a great idea but I fear that will be harder to get done in the near term.

**Comment by Petermarcu** [comment] 2017-02-26 21:04
BTW, like I said, 2.0 is still going to be kinda big for now but it is something on my radar that I am looking at addressing.

**Comment by gkhanna79** [comment] 2017-03-03 21:54
Is there anything actionable on this issue?

**Comment by steveharter** [comment] 2018-01-12 20:24
Closing as assuming not actionable

**Closed by steveharter** 2018-01-12 20:24 UTC
Labels: question
