### ISSUE TITLE
Make .NET Core 3 installer HDPI aware

### ISSUE THREAD

**Issue by OliaG** [dotnet/core-setup#4840] opened 2018-12-06 19:50 UTC
Right now the installer window is blurry on >100% display settings. We should make it HDPI aware. 
![image](https://user-images.githubusercontent.com/31997351/49608305-24343780-f94d-11e8-8f74-6a8ce614a027.png)

**Comment by rakeshsinghranchi** [comment] 2018-12-19 21:30
Related : https://github.com/dotnet/core-setup/issues/3049

**Comment by dleeapho** [comment] 2019-01-23 17:13
Dupe of #3049

**Closed by dleeapho** 2019-01-23 17:13 UTC
Labels: area-Setup
